Repository Monkestation/Monkestation2.0, pull requests merged in 2024-12, with the labels that each got.

#4430 [Bug fixes] Some funny little ol map fixes
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: bug fix, Mapping

#4469 [s] interview code tweaks
  code/__DEFINES/~monkestation/admin.dm
  code/__HELPERS/~monkestation-helpers/clients.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/ticker.dm
  code/modules/mob/dead/new_player/latejoin_menu.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/login.dm
Labels: do not merge

#4534 Fix not being able to select container/pill/patch type in chemmasters
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#4514 Raising the Tower of Babel: try 3
  code/modules/admin/smites/curse_of_babel.dm
  code/modules/admin/verbs/secrets.dm
  code/modules/events/wizard/tower_of_babel.dm
  code/modules/mob/living/basic/space_fauna/carp/magicarp.dm
  code/modules/spells/spell_types/right_and_wrong.dm
  monkestation/code/modules/spells/spell_types/pointed/smite.dm
  tgui/packages/tgui/interfaces/Secrets.jsx
Labels: Minor, Removal

#4499 Syndicate implants are now properly hidden from HUDs/scanners
  monkestation/code/modules/cybernetics/augments/_base_changes.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/weapons.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/unsorted.dm
  monkestation/code/modules/cybernetics/augments/chest_augments.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/chemplants.dm
  monkestation/code/modules/cybernetics/implant_items/autosurgeons.dm
Labels: Minor, Fix

#4509 [PORT] Fixes mind traits (Curator, miner, explorer, clown)
  code/datums/elements/befriend_petting.dm
  code/datums/status_effects/debuffs/tower_of_babel.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/modules/antagonists/clown_ops/clownop.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/language/language_manuals.dm
  code/modules/mining/lavaland/tendril_loot.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/carbon/carbon_say.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/spells/spell_types/tower_of_babel.dm
  monkestation/code/game/machinery/exp_cloner.dm
Labels: Fix

#4510 Lavaland/space ruin syndicate ghost roles now know codewords
  monkestation/code/datums/memory/key_memories.dm
  monkestation/code/modules/blueshift/items/syndicate.dm
  monkestation/code/modules/syndicate_ghostroles/_base.dm
  tgstation.dme
Labels: Tweak

#4528 Rearranges the MetaStation radio booth to be less bleh
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#4536 refactors monkecoin rewards + challenges to use `/datum/player_details`
  code/__HELPERS/~monkestation-helpers/roundend.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/ticker.dm
  code/modules/client/client_defines.dm
  code/modules/client/player_details.dm
  code/modules/mob/dead/new_player/new_player.dm
  monkestation/code/modules/client/player_details.dm
  monkestation/code/modules/coin-events/challenges/challenge/_challenge_base.dm
  monkestation/code/modules/coin-events/challenges/challenge/paranoia.dm
  monkestation/code/modules/coin-events/challenges/challenge_controller.dm
  monkestation/code/modules/coin-events/challenges/challenge_selector.dm
Labels: Refactor/Rework

#4483 Rayne medkit & bugfixes & unusual hat & more
  code/datums/components/crafting/ranged_weapon.dm
  code/datums/components/gun_crank.dm
  code/game/machinery/civilian_bounties.dm
  code/modules/clothing/suits/costume.dm
  code/modules/clothing/suits/jacket.dm
  code/modules/holiday/holidays.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/crank_guns.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  monkestation/code/game/objects/items/rayne_corp/rayne_mender.dm
  monkestation/code/modules/blueshift/armaments/kemetek.dm
  monkestation/code/modules/blueshift/armaments/rayne.dm
  monkestation/code/modules/smithing/ipcs/body/internal_organs.dm
  monkestation/code/modules/smithing/ipcs/surgeries/robot_chest_repair.dm
  monkestation/code/modules/trading/unusual_effects/animation_housing/bloody.dm
  monkestation/icons/obj/rayne_corp/rayne.dmi
  strings/monkey_companies/rayne_mender.json
  tgstation.dme
Labels: enhancement, do not merge, Expansion, Fix, Balance

#4533 Fix some clothing not updating when alt clicked while worn
  monkestation/code/modules/blueshift/components/toggle_clothing.dm
Labels: Fix

#4423 turning the blushift aquarium into the monke box
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Mapping, Tweak

#4304 New old station/Charlie station
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/debug/shiptest.dmm
  code/__DEFINES/radio.dm
  code/__DEFINES/span.dm
  code/__DEFINES/~monkestation/atom_hud.dm
  code/game/communications.dm
  code/game/objects/items/cards/card_ids.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/storage/boxes/science_boxes.dm
  code/game/say.dm
  code/modules/mob/living/basic/bots/cleanbot/cleanbot.dm
  code/modules/mob/living/living_say.dm
  icons/mob/huds/hud.dmi
  interface/stylesheet.dm
  monkestation/code/datums/id_trim/ruins.dm
  monkestation/code/game/objects/items/devices/radio/encryptionkey.dm
  monkestation/code/game/objects/items/devices/radio/headset.dm
  monkestation/code/modules/NTSL/code/coding_language/implementations/telecomms_translator.dm
  monkestation/code/modules/mapfluff/ruins/spaceruin_code/oldstation.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldchef.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldcmo.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldeng.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldexplorer.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldsci.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldsec.dm
  monkestation/code/modules/research/rdconsole.dm
  tgstation.dme
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-say/constants.ts
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui/constants.ts
Labels: Mapping

#4181 Automatic weaponry, Syndicate Items and more!
  code/__DEFINES/mobfactions.dm
  code/__DEFINES/projectiles.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/crafting/equipment.dm
  code/datums/components/crafting/ranged_weapon.dm
  code/datums/components/crafting/weapon_ammo.dm
  code/datums/components/fullauto.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/granters/crafting/rebarxbowsyndie.dm
  code/game/objects/items/grenades/spawnergrenade.dm
  code/game/objects/items/hand_items.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/cargo/packs/security.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/wintercoats.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/hostile/feral.dm
  code/modules/mob/living/simple_animal/hostile/syndicat.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/uplink/uplink_items/dangerous.dm
  code/modules/uplink/uplink_items/nukeops.dm
  code/modules/uplink/uplink_items/stealthy.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt_mirror.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/pets_held_lh.dmi
  icons/mob/inhands/pets_held_rh.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/simple/pets.dmi
  icons/obj/cosmetic.dmi
  icons/obj/weapons/guns/ballistic.dmi
  icons/obj/weapons/guns/bows/quivers.dmi
  icons/obj/weapons/guns/energy.dmi
  icons/obj/weapons/guns/projectiles.dmi
  monkestation/code/modules/mob/living/basic/pets/cat.dm
  monkestation/icons/mob/pets_held.dmi
  sound/items/xbow_lock.ogg
  sound/weapons/taser3.ogg
  tgstation.dme
Labels: Expansion, Tweak

#4320 Expansion of the Emergency Response Corps (TAKE TWO)
  _maps/shuttles/ert_deathsquad.dmm
  _maps/shuttles/ert_dropship-clown.dmm
  _maps/shuttles/ert_dropship-janitor.dmm
  _maps/shuttles/ert_dropship.dmm
  _maps/shuttles/ert_generic.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/is_helpers.dm
  code/datums/elements/decals/_decal.dm
  code/datums/ert.dm
  code/datums/id_trim/centcom.dm
  code/game/objects/items/control_wand.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/modules/admin/verbs/ert.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/jobs/job_types/ert/ert_generic.dm
  code/modules/mapping/access_helpers.dm
  code/modules/mod/modules/modules_service.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  code/modules/vehicles/mecha/equipment/tools/work_tools.dm
  icons/mob/clothing/back/backpack.dmi
  icons/obj/storage/backpack.dmi
  icons/obj/storage/box.dmi
  monkestation/code/modules/ERT/ERT_outfits.dm
  monkestation/code/modules/ERT/ERT_shuttle.dm
  monkestation/code/modules/ERT/equipment/ERT_id.dm
  monkestation/code/modules/ERT/equipment/ERT_misc_equipment.dm
  monkestation/code/modules/ERT/equipment/ERT_spacesuits.dm
  monkestation/icons/mob/clothing/ERT/ERT_helmet_worn-digi.dmi
  monkestation/icons/mob/clothing/ERT/ERT_helmet_worn.dmi
  monkestation/icons/mob/clothing/ERT/ERT_spacesuit_worn-digi.dmi
  monkestation/icons/mob/clothing/ERT/ERT_spacesuit_worn.dmi
  monkestation/icons/mob/clothing/mask.dmi
  monkestation/icons/mob/clothing/species/mask_muzzled.dmi
  monkestation/icons/obj/clothing/ERT/ERT_helmet_obj.dmi
  monkestation/icons/obj/clothing/ERT/ERT_spacesuit_obj.dmi
  monkestation/icons/obj/clothing/masks.dmi
  monkestation/sound/ambience/antag/ert.ogg
  tgstation.dme
Labels: Major, Expansion

#4555 Fix railing stacking
  code/controllers/subsystem/materials.dm
Labels: Fix

#4556 Adds christmas tree spawners to Blueshift
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Mapping

#4537 fix some double-encodes in plexora/tgs stuff
  code/__HELPERS/text.dm
  code/modules/admin/verbs/adminhelp.dm
  monkestation/code/modules/mentor/mentor_pm.dm
Labels: Fix

#4564 fix random lipstick having no proper icon state
  code/game/objects/items/cosmetics.dm
Labels: Fix

#4365 [Bounty] Oozeling Membrane Murmur Ability
  monkestation/code/modules/smithing/oozelings/actions.dm
  monkestation/code/modules/smithing/oozelings/body/organs.dm
Labels: Minor, Feature

#4570 bitrunning vender console now researchable
  code/modules/bitrunning/designs.dm
Labels: Fix

#4579 Fix suiciding ghost player bodies duplicating
  monkestation/code/modules/ghost_players/ghost_player.dm
Labels: Fix

#4560 Various fixes
  _maps/map_files/MetaStation/MetaStation.dmm
  code/datums/components/supermatter_crystal.dm
  monkestation/code/modules/blueshift/appliances/colony.dm
  monkestation/code/modules/blueshift/clothing/nova_neck.dm
  monkestation/code/modules/research/designs/autolathe/materials.dm
  tgstation.dme
Labels: Fix, Balance

#4562 Expand wire knowledge
  monkestation/code/datums/wires/airalarm.dm
  monkestation/code/datums/wires/mod.dm
  monkestation/code/datums/wires/mulebot.dm
  monkestation/code/datums/wires/vending.dm
  tgstation.dme
Labels: Minor, QoL

#4600 Chrimas and zombie fixes
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/structures/flora.dm
  code/modules/events/wizard/blobies.dm
  code/modules/holiday/holidays.dm
Labels: Tweak, Fix

#4601 Prevent clown fault artifacts from creating multiple clown spawners simultaneously
  monkestation/code/modules/art_sci_overrides/faults/clowning.dm
Labels: Balance

#4599 Use `rust_g64.dll` / `librustg_64.so` on OpenDream
  .gitignore
  code/__DEFINES/rust_g.dm
Labels: Tools

#4553 Add pain immunity to some things that should prolly have it anyways
  code/modules/antagonists/heretic/knowledge/blade_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/nightmare/nightmare_species.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  monkestation/code/modules/antagonists/florida_man/_florida_man.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_sol.dm
  monkestation/code/modules/bloodsuckers/powers/fortitude.dm
  monkestation/code/modules/can_spessmen_feel_pain/pain/_base.dm
  monkestation/code/modules/clothing/spacesuits/hardsuits/heavy.dm
Labels: Balance

#4612 more blugfixes
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/gift.dm
  code/game/objects/structures/flora.dm
  code/modules/holiday/holidays.dm
  monkestation/code/game/objects/effects/anomalies/anomalies_lifebringer.dm
  monkestation/code/game/objects/items/implants/hardlight.dm
  monkestation/code/modules/art_sci_overrides/artifact_effects/bomb.dm
Labels: Fix

#4613 Adds upload to research directors remote
  code/__DEFINES/access.dm
Labels: Minor, Balance

#4591 Cargo imports UI now shows the correct price when the station has strong or distant supply lines
  monkestation/code/modules/blueshift/components/armament.dm
Labels: Fix

#4584 Various fixes part 2. Electric boogaloo :
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  code/datums/id_trim/jobs.dm
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/game/objects/items/devices/radio/encryptionkey.dm
  monkestation/code/modules/blueshield/clothing.dm
  monkestation/code/modules/blueshield/devices/sensor.dm
  monkestation/code/modules/blueshield/gun.dm
  monkestation/code/modules/blueshield/icons/device.dmi
  monkestation/code/modules/blueshield/icons/praetorian.dmi
  monkestation/code/modules/blueshield/icons/worn_praetorian.dmi
  monkestation/code/modules/blueshield/modsuit/suit.dm
  monkestation/code/modules/blueshield/modsuit/theme.dm
  monkestation/code/modules/blueshield/radio.dm
  monkestation/code/modules/jobs/departments/departments.dm
  monkestation/code/modules/jobs/job_types/blueshield.dm
  monkestation/code/modules/jobs/job_types/departments/departments.dm
  monkestation/code/modules/mapfluff/ruins/spaceruin_code/oldstation.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/oozeling.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/satyr.dm
  monkestation/code/modules/research/techweb/all_nodes.dm
  monkestation/code/modules/smithing/ipcs/body/internal_organs.dm
  monkestation/code/modules/smithing/ipcs/research.dm
  monkestation/code/modules/smithing/oozelings/body/organs.dm
  monkestation/code/modules/surgery/bodyparts/ipc_bodyparts.dm
  monkestation/code/modules/surgery/bodyparts/oozeling_bodyparts.dm
  monkestation/code/modules/surgery/bodyparts/satyr_bodyparts.dm
  monkestation/code/modules/surgery/organs/internal/brain.dm
  monkestation/code/modules/surgery/organs/internal/ears.dm
  monkestation/code/modules/surgery/organs/internal/eyes.dm
  monkestation/code/modules/surgery/organs/internal/heart.dm
  monkestation/code/modules/surgery/organs/internal/liver.dm
  monkestation/code/modules/surgery/organs/internal/lungs.dm
  monkestation/code/modules/surgery/organs/internal/stomach.dm
  monkestation/code/modules/surgery/organs/internal/tongue.dm
  monkestation/code/modules/surgery/robot_brain_healing.dm
  monkestation/code/modules/surgery/robot_chest_repair.dm
  monkestation/code/modules/surgery/robot_healing.dm
  monkestation/code/modules/surgery/steps.dm
  monkestation/icons/mob/clothing/worn_modsuit.dmi
  monkestation/icons/obj/clothing/modsuits/modsuit.dmi
  monkestation/icons/obj/device.dmi
  monkestation/icons/obj/radio.dmi
  monkestation/icons/obj/weapons/guns/tech9.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
Labels: Mapping, Fix

#4602 [Code Bounty] Makes pins display what they represent more clearly in the name (AKA: "rainbow pride pin" instead of "pride pin")
  code/datums/quirks/neutral_quirks/pride_pin.dm
  code/modules/clothing/under/accessories/badges.dm
  monkestation/code/modules/blueshift/items/badges.dm
Labels: QoL

#4589 Makes it more obvious in the lobby when there's a job overflow
  code/__HELPERS/~monkestation-helpers/icons.dm
  code/_onclick/hud/new_player.dm
  code/modules/asset_cache/asset_list.dm
  icons/hud/lobby/overflow.dmi
  monkestation/code/datums/station_traits/negative_traits.dm
  monkestation/code/modules/asset_cache/assets/job_icons.dm
  monkestation/code/modules/client/preferences/overflow.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/monkestation/overflow.tsx
Labels: Major, peak, QoL

#4603 Blob infestation
  code/game/data_huds.dm
  code/modules/events/ghost_role/blob.dm
  monkestation/code/modules/antagonist/blob/blob_antag.dm
  monkestation/code/modules/storytellers/converted_events/event_overrides.dm
  monkestation/code/modules/storytellers/converted_events/solo/blob_infection.dm
  tgstation.dme
Labels: Expansion

#4620 Properly give all xenobio slimeperson subspecies slime wings
  code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
Labels: Fix

#4619 Slime in vents/slime grinders/etc will no longer secrete ooze on the floor
  monkestation/code/modules/slimecore/components/liquid_secretion.dm
Labels: Fix

#4532 Add an "Export Lighting Info" mapping verb
  code/modules/admin/verbs/mapping.dm
  monkestation/code/modules/admin/verbs/mapping.dm
  tgstation.dme
Labels: enhancement, QoL

#4475 [TG Port] Replace Heretic Phobia with Cursed Organs
  code/__DEFINES/antagonists.dm
  code/datums/ai/_ai_controller.dm
  code/datums/elements/corrupted_organ.dm
  code/datums/elements/relay_attackers.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/antagonists/heretic/items/corrupted_organs.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_buff.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_curse.dm
  code/modules/reagents/chemistry/reagents/impure_reagents/impure_medicine_reagents.dm
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  tgstation.dme
Labels: Balance

#4414 [Code Bounty] Unreviewed Mixtape Refund + Bonus
  code/__HELPERS/roundend.dm
  code/__HELPERS/~monkestation-helpers/roundend.dm
  code/modules/admin/admin_verbs.dm
  monkestation/code/modules/cassettes/cassette_approval.dm
  tgui/packages/tgui/interfaces/CassetteManager.tsx
  tgui/packages/tgui/interfaces/CassetteReview.jsx
Labels: Fix

#4624 Removes tasers from the armory
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  monkestation/code/modules/cargo/crates/security.dm
Labels: Mapping, Balance

#4622 Linking Ooze Sucker Fix
  monkestation/code/modules/slimecore/machines/ooze_sucker.dm
  monkestation/code/modules/slimecore/machines/slime_pen_controller.dm
Labels: QoL

#4548 Debilitated Rework - Nerf
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/projectiles/projectile/energy/ebow.dm
  monkestation/code/game/objects/items/guns/crank_guns.dm
  monkestation/code/modules/blood_datum/debilitated.dm
Labels: Balance

#4270 Adds a cargo-locked disabler to the quartermaster's locker
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  monkestation/code/modules/projectiles/guns/energy/stun.dm
  monkestation/code/modules/projectiles/pins.dm
  tgstation.dme
Labels: Minor, Feature, Balance

#4576 Makes interdyne MOD actually fit people without digitigrade legs
  icons/mob/clothing/modsuit/mod_clothing.dmi
  icons/obj/clothing/modsuit/mod_clothing.dmi
  monkestation/icons/mob/mod.dmi
Labels: spriting, Fix

#4578 The monster hunter blood vial is now just a status effect instead of a weird status effect + reagent combination
  monkestation/code/modules/antagonists/monster_hunters/events/wonderland.dm
  monkestation/code/modules/antagonists/monster_hunters/tools/blood_vial.dm
  tgstation.dme
Labels: Minor, do not merge, Refactor/Rework

#4507 Doubles number of explorer role slots
  monkestation/code/modules/jobs/job_types/explorer.dm
Labels: Minor, Tweak

#4582 Fix heretic sac not restoring blood and leaving chems inside the sac target.
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
Labels: Fix

#4632 Fixes Power Gloves combat logging
  monkestation/code/modules/clothing/gloves/power_gloves.dm
Labels: Fix

#4643 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools

#4638 Prevent setting the next map from conflicting across LRP/MRP/HRP
  code/__DEFINES/maps.dm
Labels: Fix

#4635 Properly marks type and confidentiality of a few admin/mentor-related notifications
  code/modules/client/client_procs.dm
  monkestation/code/modules/mentor/mentor_follow.dm
Labels: Fix

#4633 Adds tinyfans to arrivals on Blueshift
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Mapping, Fix

#4580 [PORT] Adds unit test for effects set to "Curse of Mundanity" (and missing IDs)
  code/__DEFINES/status_effects.dm
  code/datums/elements/organ_set_bonus.dm
  code/datums/status_effects/_status_effect.dm
  code/datums/status_effects/agent_pinpointer.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/buffs/stun_asorption.dm
  code/datums/status_effects/debuffs/blindness.dm
  code/datums/status_effects/debuffs/debuffs.dm
  code/datums/status_effects/debuffs/dna_transformation.dm
  code/datums/status_effects/debuffs/drunk.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
  code/datums/status_effects/debuffs/genetic_damage.dm
  code/datums/status_effects/debuffs/hallucination.dm
  code/datums/status_effects/debuffs/speech_debuffs.dm
  code/datums/status_effects/debuffs/tower_of_babel.dm
  code/datums/status_effects/drug_effects.dm
  code/datums/status_effects/gas.dm
  code/datums/status_effects/grouped_effect.dm
  code/datums/status_effects/limited_effect.dm
  code/datums/status_effects/neutral.dm
  code/datums/status_effects/stacking_effect.dm
  code/datums/status_effects/wound_effects.dm
  code/modules/antagonists/heretic/magic/ash_ascension.dm
  code/modules/antagonists/heretic/magic/shadow_cloak.dm
  code/modules/antagonists/heretic/magic/star_touch.dm
  code/modules/antagonists/heretic/status_effects/buffs.dm
  code/modules/antagonists/heretic/status_effects/debuffs.dm
  code/modules/antagonists/heretic/status_effects/ghoul.dm
  code/modules/mining/equipment/monster_organs/brimdust_sac.dm
  code/modules/mob/living/basic/lavaland/basilisk/basilisk_overheat.dm
  code/modules/mob/living/basic/space_fauna/revenant/revenant_effects.dm
  code/modules/mob/living/status_procs.dm
  code/modules/religion/burdened/psyker.dm
  code/modules/religion/hunt/hunter_pinpointer.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/status_effect_validity.dm
  monkestation/code/datums/status_effects/buffs.dm
  monkestation/code/datums/status_effects/changeling.dm
  monkestation/code/datums/status_effects/food_buffs.dm
  monkestation/code/modules/a_medical_day/lungless.dm
  monkestation/code/modules/antagonists/borers/code/status_effects.dm
  monkestation/code/modules/antagonists/clock_cult/status_effects.dm
  monkestation/code/modules/antagonists/monster_hunters/events/wonderland_apocalypse.dm
  monkestation/code/modules/antagonists/monster_hunters/tools/bnuuy_mask.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/hunter_revolver.dm
  monkestation/code/modules/art_sci_overrides/artifact_effects/false_rod.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_frenzy.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_sol.dm
  monkestation/code/modules/bloodsuckers/powers/masquerade.dm
  monkestation/code/modules/bloodsuckers/vassals/vassal_pinpointer.dm
  monkestation/code/modules/blueshift/species/ashwalker.dm
  monkestation/code/modules/can_spessmen_feel_pain/pain/status_effects/low_blood_pressure.dm
  monkestation/code/modules/datums/status_effects/debuffs.dm
  monkestation/code/modules/ghost_players/centcom_grace.dm
  monkestation/code/modules/liquids/liquid_status_effect.dm
  monkestation/code/modules/ranching/chickens/tier1/chicken.dm
  monkestation/code/modules/slimecore/crossbreeding/regenerative/cooldown.dm
Labels: Fix

#4639 All ghosts now see PDA messages, not just observers
  code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm
Labels: Fix

#4625 makes it easier to see what items were from a gift
  code/__DEFINES/traits/monkestation/declarations.dm
  code/__DEFINES/~monkestation/vv.dm
  code/__HELPERS/~monkestation-helpers/atoms.dm
  code/_globalvars/traits/_traits.dm
  code/game/objects/items/gift.dm
  code/modules/admin/verbs/admingame.dm
  monkestation/code/datums/components/gift_item.dm
  tgstation.dme
Labels: Minor, QoL

#4636 Fire alarms no longer burn out lights
  code/modules/power/lighting/light.dm
Labels: Fix

#4653 Replaces the syndie base's passive vent with an injector
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1/mistake_inevitable.dmm
Labels: Mapping, Fix

#4659 Removes poorly named objects\items\objects\items folder. (Because "Why was that there" wasn't good apparently.)
  monkestation/code/game/objects/items/robot/items/robot_upgrades.dm
  tgstation.dme
Labels: Fix

#4615 516 prep: fix chat window z-fighting and tgui-say escape key
  code/_experiments.dm
  code/controllers/subsystem/statpanel.dm
  code/modules/admin/holder2.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/validate_assets.html
  code/modules/client/client_procs.dm
  code/modules/tgui_panel/external.dm
  interface/skin.dmf
  tgui/global.d.ts
  tgui/packages/common/keys.ts
  tgui/packages/common/storage.ts
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui-panel/index.jsx
  tgui/packages/tgui-say/TguiSay.tsx
  tgui/packages/tgui/interfaces/KeyComboModal.tsx
  tgui/public/tgui.html
Labels: Fix

#4630 [s] some internal admin tool improvements
  code/modules/admin/admin_verbs.dm
  monkestation/code/game/alternate_appearance.dm
  tgstation.dme
Labels: Tools

#4676 [PORT] Fancy boxed messages!
  code/__DEFINES/chat.dm
  code/__HELPERS/game.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/polling.dm
  code/controllers/subsystem/vote.dm
  code/datums/ai_laws/ai_laws.dm
  code/datums/components/trader/trader.dm
  code/datums/elements/weapon_description.dm
  code/datums/mind/skills.dm
  code/datums/mood.dm
  code/datums/votes/_vote_datum.dm
  code/game/objects/items/AI_modules/_AI_modules.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/scanners/gas_analyzer.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/buildmode/submodes/map_export.dm
  code/modules/client/verbs/who.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/fishing/aquarium/fish_analyzer.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/basic/space_fauna/revenant/_revenant.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/items.dm
  monkestation/code/datums/station_traits/negative_traits.dm
  monkestation/code/modules/antagonists/clock_cult/actions/add_warp_area.dm
  monkestation/code/modules/antagonists/clock_cult/antag_datums/clock_cultist.dm
  monkestation/code/modules/antagonists/teratoma/teratoma.dm
  monkestation/code/modules/blueshift/opfor/core/_base.dm
  monkestation/code/modules/blueshift/opfor/core/admin.dm
  monkestation/code/modules/can_spessmen_feel_pain/pain/_base.dm
  monkestation/code/modules/factory_type_beat/debug.dm
  monkestation/code/modules/loadouts/loadout_middleware.dm
  monkestation/code/modules/ranching/items.dm
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
Labels: QoL

#4688 Flipped the tube
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Minor, Mapping, Fix

#4662 Fixes 4648
  code/modules/research/techweb/all_nodes.dm
Labels: Fix

#4692 Engi + atmos Hardsuit sprite update
  monkestation/icons/mob/clothing/hardsuit/hardsuit_body.dmi
  monkestation/icons/mob/clothing/hardsuit/hardsuit_helm.dmi
  monkestation/icons/mob/species/misc/head_muzzled.dmi
  monkestation/icons/mob/species/misc/suit_digi.dmi
  monkestation/icons/obj/clothing/hardsuits/helmet.dmi
  monkestation/icons/obj/clothing/hardsuits/suit.dmi
Labels: enhancement, spriting, peak

#4674 Oxygen Tank Refills
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
Labels: Minor, Mapping, Balance

#4699 pipes
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Minor, peak, Mapping, Fix

#4663 [BALANCE] Nerf the Paco's magazine size
  monkestation/code/modules/security/code/weapons/paco.dm
Labels: Balance

#4702 Reorganize some modular subsystem stuff, adds verbs related to handling glowshrooms
  code/__DEFINES/subsystems.dm
  code/__DEFINES/~monkestation/misc.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/modules/admin/admin_verbs.dm
  memorystats.dll
  monkestation/code/__HELPERS/files.dm
  monkestation/code/controllers/master.dm
  monkestation/code/controllers/subsystem/glowshrooms.dm
  monkestation/code/controllers/subsystem/memory_stats.dm
  monkestation/code/controllers/subsystem/priority_effects.dm
  monkestation/code/controllers/subsystem/stamina.dm
  monkestation/code/game/objects/effects/glowshroom.dm
  monkestation/code/modules/admin/verbs/glowshrooms.dm
  monkestation/code/modules/factory_type_beat/debug.dm
  tgstation.dme
Labels: Tools, Refactor/Rework

#4714 Fixes Table flipping 4ever (I hope)
  monkestation/code/modules/blueshift/structures/flipped_table.dm
Labels: Fix

#4690 Fixes Integrated Circuit Access Checkers
  tgui/packages/tgui/interfaces/CircuitAccessChecker.tsx
Labels: Fix

#4713 Harduit sprite update2
  monkestation/icons/mob/clothing/hardsuit/hardsuit_body.dmi
  monkestation/icons/mob/clothing/hardsuit/hardsuit_helm.dmi
  monkestation/icons/mob/species/misc/head_muzzled.dmi
  monkestation/icons/mob/species/misc/suit_digi.dmi
  monkestation/icons/obj/clothing/hardsuits/helmet.dmi
  monkestation/icons/obj/clothing/hardsuits/suit.dmi
Labels: spriting

#4684 Make heart worms a preset dangerous disease
  monkestation/code/modules/virology/disease/premades/heart_attack.dm
Labels: QoL

#4586 Removes brain damage from the assops interrogator
  monkestation/code/modules/assault_ops/code/interrogator.dm
Labels: Minor, Tweak

#4637 Mark of Rust now arms grenades instead of instantly detonating them
  code/__DEFINES/~monkestation/antagonists.dm
  code/modules/antagonists/heretic/heretic_knowledge.dm
  code/modules/antagonists/heretic/status_effects/mark_effects.dm
  monkestation/code/modules/antagonists/heretic/status_effects/mark_effects.dm
  tgstation.dme
Labels: Balance

#4669 Space Hotel machine frames!
  _maps/RandomRuins/SpaceRuins/spacerealhotel.dmm
Labels: Major, Mapping, Fix

#4343 [DNM]Oozling qol fixes
  code/modules/mob/living/basic/lavaland/legion/legion.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/organs/internal/tongue/_tongue.dm
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/oozeling.dm
  monkestation/code/modules/smithing/oozelings/actions.dm
  monkestation/code/modules/surgery/bodyparts/oozeling_bodyparts.dm
  monkestation/code/modules/surgery/organs/internal/brain.dm
  monkestation/code/modules/surgery/organs/internal/heart.dm
Labels: peak, Fix, Balance

#4428 [Bounty] Graytide Sectorwide
  code/__DEFINES/~monkestation/martial_arts.dm
  icons/mob/clothing/suits/jacket.dmi
  icons/obj/clothing/suits/jacket.dmi
  monkestation/code/game/objects/items/storage/uplink_kits.dm
  monkestation/code/modules/martial_arts/granters/tunnel_arts_gr.dm
  monkestation/code/modules/martial_arts/misc/clothing.dm
  monkestation/code/modules/martial_arts/misc/martial_effects.dm
  monkestation/code/modules/martial_arts/tunnel_arts.dm
  monkestation/code/modules/uplink/uplink_items/job.dm
  tgstation.dme
Labels: Minor, Feature

#4561 Syndicate Depot and Various Unrelated Map Fixes that Pooba Asked For
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/datums/ruins/space.dm
  code/modules/mob_spawn/ghost_roles/space_roles.dm
  code/modules/recycling/disposal/outlet.dm
  monkestation/code/modules/syndicate_ghostroles/depot.dm
  tgstation.dme
Labels: Mapping, Fix

#4611 Replaced Blueshield's mantis blades with shield blades + mantis blade changes
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/~monkestation/company.dm
  code/_globalvars/traits/_traits.dm
  code/_onclick/item_attack.dm
  code/game/machinery/doors/door.dm
  icons/hud/screen_alert.dmi
  monkestation/code/modules/blueshield/gun.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/weapons.dm
  monkestation/code/modules/cybernetics/icons/items_and_weapons.dmi
  monkestation/code/modules/cybernetics/icons/swords_lefthand.dmi
  monkestation/code/modules/cybernetics/icons/swords_righthand.dmi
  monkestation/code/modules/cybernetics/implant_items/autosurgeons.dm
  monkestation/code/modules/cybernetics/implant_items/weapons/mantis_blade.dm
Labels: Feature, Balance

#4727 Makes blueshift departures airlock not security exclusive
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Mapping, Fix

#4693 Fix height filter runtime + related bugs
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/shoes/wheelys.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  icons/effects/64x64.dmi
  icons/mob/clothing/ears.dmi
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/mask.dmi
  monkestation/code/modules/clothing/masks/misc.dm
  monkestation/icons/effects/cut_64x64.dmi
  monkestation/icons/mob/clothing/mask.dmi
Labels: Fix

#4530 Costume "armor" storage buff
  code/modules/clothing/suits/costume.dm
  monkestation/code/modules/clothing/suits/coats.dm
  monkestation/code/modules/clothing/suits/costume.dm
  monkestation/code/modules/clothing/~donator/clothing.dm
Labels: Tweak, Balance

#4717 Fix the radio frequency not being heard by some types of radios/intercoms
  code/game/objects/items/devices/radio/radio.dm
  monkestation/code/game/objects/items/devices/radio/radio.dm
  monkestation/code/modules/cassettes/machines/radio_mic.dm
  tgstation.dme
Labels: Fix

#4731 Removes blindfold from maid costume
  code/game/objects/effects/spawners/costume.dm
Labels: what

#4728 Prevent Life and similar reactions from occuring in plants
  code/__DEFINES/reagents.dm
  code/modules/reagents/chemistry/holder.dm
  monkestation/code/modules/reagents/chemistry/recipes/others.dm
  tgstation.dme
Labels: Fix

#4741 Ashwalker Longbow Spawn fix
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker2.dmm
Labels: Mapping, Fix

#4715 More antag symbols + Theseus map fixes
  _maps/map_files/Theseus/Theseus.dmm
  monkestation/code/modules/antagonists/blob/blob_antag.dm
  monkestation/code/modules/antagonists/borers/code/antagonist_stuff/antagonist_datum.dm
  monkestation/code/modules/antagonists/contractor/datums/contractor_datum.dm
  monkestation/code/modules/antagonists/contractor/datums/contractor_support.dm
  monkestation/code/modules/antagonists/florida_man/_florida_man.dm
  monkestation/code/modules/antagonists/monster_hunters/hunter_datum.dm
  monkestation/code/modules/antagonists/space_ninja/space_ninja.dm
  monkestation/icons/mob/huds/antag_hud.dmi
  monkestation/icons/mob/huds/antags/monster_hunter.dmi
  tgstation.dme
Labels: spriting, Fix, QoL
