Repository Monkestation/Monkestation2.0, pull requests merged in 2025-07, with the labels that each got.

#7015 probably fix the morbillion shipbreaking hard deletes (and some other random things)
  _maps/shuttles/emergency_cruise.dmm
  code/__HELPERS/files.dm
  code/controllers/master.dm
  code/controllers/subsystem/explosions.dm
  code/datums/components/creamed.dm
  code/datums/components/shell.dm
  code/datums/components/toggle_attached_clothing.dm
  code/datums/helper_datums/teleport.dm
  code/game/atoms_movable.dm
  code/game/objects/items/holosign_creator.dm
  code/modules/antagonists/heretic/knowledge/moon_lore.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/buildmode/buildmode.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/living.dm
  code/modules/mod/modules/modules_supply.dm
  code/modules/surgery/organs/stomach/_stomach.dm
  monkestation/code/datums/meta_tokens.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/machines/console.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships.dm
  monkestation/code/modules/blueshift/components/armament.dm
  monkestation/code/modules/blueshift/components/cell_component.dm
  monkestation/code/modules/loadouts/items/pocket.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
  monkestation/code/modules/slimecore/reagents/base_colors.dm
  tgui/packages/tgui/interfaces/NtosMessenger/index.tsx
Labels: Code: Fix, Code: Performance / Optimization, Approval: admin approved, Process: should testmerge

#7094 Resource dupe and storage apparatus fix
  code/game/objects/items/robot/items/storage.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/sheets/sheets.dm
Labels: Code: Fix

#7082 Increase Max Nanite Program Limit
  code/__DEFINES/nanites.dm
Labels: QoL, Approval: admin approved

#7017 some boxing changes
  code/datums/martial/boxing.dm
Labels: Balance, Approval: admin approved

#7067 Caps antimagic plants
  code/modules/hydroponics/unique_plant_genes.dm
Labels: Balance, Approval: admin approved

#7028 [PORT] Ninja energy net now a projectile
  code/modules/antagonists/ninja/energy_net_nets.dm
  code/modules/mod/modules/modules_engineering.dm
  code/modules/mod/modules/modules_ninja.dm
Labels: Balance, Approval: admin approved

#7008 un-conversions blood brothers
  code/modules/antagonists/brother/actions/_action.dm
  code/modules/antagonists/brother/actions/communicate.dm
  code/modules/antagonists/brother/actions/gear.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/brother/brother_team.dm
  code/modules/antagonists/brother/gear/_gear.dm
  code/modules/antagonists/brother/gear/misc.dm
  code/modules/antagonists/brother/gear/recipes.dm
  monkestation/code/modules/antagonists/brother/brother.dm
  monkestation/code/modules/antagonists/brother/brother_team.dm
  monkestation/code/modules/storytellers/converted_events/solo/brother.dm
  tgstation.dme
Labels: Balance, Feature: Refactor/Rework, Approval: admin approved

#7004 Rebalances burning metal and yellow extracts
  code/modules/research/xenobiology/crossbreeding/burning.dm
Labels: Balance, Approval: admin approved

#6978 Energised Fireaxe
  code/game/objects/items/fireaxe.dm
  code/modules/mob/living/emote.dm
  code/modules/surgery/organic_steps.dm
  code/modules/uplink/uplink_items/dangerous.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/eaxe_lefthand.dmi
  icons/mob/inhands/weapons/eaxe_righthand.dmi
  icons/obj/weapons/eaxe.dmi
Labels: Feature: Feature, QoL, Approval: awaiting admin review

#6990 Budgeted meteor satellite crate
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LeadPoisoningStation/LeadPoisoningStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Feature: Feature, Approval: awaiting admin review

#6984 Not-so-Wee acarp buff
  code/datums/martial/sleeping_carp.dm
  monkestation/code/modules/martial_arts/awakened_dragon.dm
Labels: Balance, Approval: awaiting admin review

#7037 Pathology Map Stuff
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Change: Mapping, Process: should testmerge

#6481 [EVENT] Event stuff for drag
  code/__DEFINES/mod.dm
  monkestation/code/modules/veth_misc_items/moonlight_brigade/brigade_icons.dmi
  monkestation/code/modules/veth_misc_items/moonlight_brigade/brigade_onmob.dmi
  monkestation/code/modules/veth_misc_items/moonlight_brigade/moonlight_mods.dm
  tgstation.dme
Labels: Merge Conflict

#7044 Some curator whip tweaks
  code/datums/status_effects/debuffs/debuffs.dm
  code/game/objects/items/melee/curators_whip.dm
Labels: Balance, Approval: admin approved

#6910 Botany Splicer Infusion Process Rework
  monkestation/code/modules/hydroponics/machines/splicer.dm
Labels: Feature: Expansion, Balance, Approval: admin approved

#6926 Makes Hardlight spears usable again - fixes jagged xbow bolts
  code/game/objects/items/implants/hardlight.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/uplink/uplink_items/dangerous.dm
  code/modules/uplink/uplink_items/implant.dm
  code/modules/uplink/uplink_items/nukeops.dm
  code/modules/uplink/uplink_items/stealthy.dm
  monkestation/code/modules/uplink/uplink_items/nukeops.dm
  monkestation/code/modules/uplink/uplink_items/weapons.dm
  tgstation.dme
Labels: Code: Fix, Balance, Approval: awaiting admin review

#7096 Fix sacrificing oozeling cores rendering them brainless yet fully functional
  monkestation/code/modules/antagonists/heretic/heretic_living_heart.dm
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
Labels: Code: Fix, Approval: admin approved

#7072 try to restore the old quick equip behavior
  code/modules/mob/inventory.dm
Labels: QoL, Process: should testmerge

#7099 Limb relocation pain fix
  code/datums/wounds/bones.dm
  monkestation/code/modules/can_spessmen_feel_pain/pain/causes/generic.dm
Labels: Code: Fix

#7103 [BOUNTY] Ports refactors from golem rework
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_carbon.dm
  code/__DEFINES/mobs.dm
  code/datums/bodypart_overlays/emote_bodypart_overlay.dm
  code/datums/components/food/edible.dm
  code/game/atoms.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/mining/equipment/monster_organs/regenerative_core.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/lighting/light.dm
  code/modules/surgery/bodyparts/_arms.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/parts.dm
  code/modules/surgery/bodyparts/worn_feature_offset.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/stomach/_stomach.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/abductors.dm
  monkestation/code/modules/mob/living/carbon/human/worn_overlays.dm
  monkestation/code/modules/surgery/bodyparts/monkey_bodyparts.dm
  tgstation.dme
Labels: Code: Improvement, Process: should testmerge

#7109 fix the unborgable quirk not actually working
  monkestation/code/datums/quirks/neutral_quirks/unborgable.dm
Labels: Code: Fix

#7087 adds some more SDQL2/Lua wrappers
  code/__HELPERS/generators.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
  html/changelogs/AutoChangeLog-pr-91950.yml
  html/changelogs/AutoChangeLog-pr-91954.yml
  lua/SS13_base.lua
  monkestation/code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
  tgstation.dme
Labels: Tools

#7108 Always use normal, habitable air on the colony Z-level
  code/__DEFINES/~monkestation/atmospherics.dm
  monkestation/code/modules/map_gen_expansions/forest/atmosphere.dm
  monkestation/code/modules/map_gen_expansions/new_turfs.dm
  tgstation.dme
Labels: Code: Fix

#7089 Tenna AI Core
  code/modules/mob/living/silicon/ai/_preferences.dm
  icons/mob/silicon/ai.dmi
Labels: Change: spriting, Code: Fix

#7100 fix bloodsuckers being able to spam blood thickening prompts
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_misc_procs.dm
Labels: Code: Fix

#7122 fixing water
  code/modules/research/designs/biogenerator_designs.dm
Labels: Code: Fix

#7125 Ranching fixes
  monkestation/code/modules/ranching/items.dm
  monkestation/code/modules/ranching/mutations/tier2.dm
Labels: Code: Fix, QoL

#7145 Ensure Plexora cleans up HTTP requests
  code/controllers/subsystem/plexora.dm
Labels: Code: Fix, Code: Performance / Optimization

#7136 Fix weird uncapped organs
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/surgery/organs/_organ.dm
Labels: Code: Fix, Fixed Upstream

#7115 *un-links your cyber*
  _maps/RandomRuins/IceRuins/icemoon_underground_oldstation.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/__DEFINES/traits/monkestation/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/station_traits/positive_traits.dm
  code/game/objects/items/storage/boxes/job_boxes.dm
  code/game/objects/items/storage/medkit.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/antagonists/nukeop/equipment/vendor_kits/kits.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/mining/lavaland/tendril_loot.dm
  code/modules/research/techweb/cyborg_nodes.dm
  monkestation/code/datums/quirks/positive_quirks/neuralink.dm
  monkestation/code/game/objects/items/storage/uplink_kits.dm
  monkestation/code/modules/ERT/ERT_outfits.dm
  monkestation/code/modules/blueshield/gun.dm
  monkestation/code/modules/blueshift/items/nif.dm
  monkestation/code/modules/blueshift/opfor/equipment/implants.dm
  monkestation/code/modules/cybernetics/actions/base_action.dm
  monkestation/code/modules/cybernetics/augments/_base_changes.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/_base.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/_base.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/jobs.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/weapons.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/unsorted.dm
  monkestation/code/modules/cybernetics/augments/chest_augments.dm
  monkestation/code/modules/cybernetics/augments/eye_implants.dm
  monkestation/code/modules/cybernetics/augments/internal_implants.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/_base.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/chemplants.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/traits.dm
  monkestation/code/modules/cybernetics/augments/uplink/uplink.dm
  monkestation/code/modules/cybernetics/designs/item_sets.dm
  monkestation/code/modules/cybernetics/designs/medical.dm
  monkestation/code/modules/cybernetics/designs/security.dm
  monkestation/code/modules/cybernetics/implant_items/cyberlink_connector.dm
  monkestation/code/modules/cybernetics/minigame/airlock_hacking_datum.dm
  monkestation/code/modules/cybernetics/minigame/general_hacking.dm
  monkestation/code/modules/cybernetics/minigame/hacking_minigame.dm
  monkestation/code/modules/cybernetics/premade_storages/antags.dm
  monkestation/code/modules/cybernetics/skillchips.dm
  monkestation/code/modules/cybernetics/skills/implant_hacking.dm
  monkestation/code/modules/cybernetics/tech_nodes.dm
  monkestation/code/modules/factory_type_beat/yummy.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
  monkestation/code/modules/surgery/organs/augments.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/Hacking.jsx
  tgui/packages/tgui/interfaces/HackingMinigame.jsx
Labels: Removal, Approval: admin approved, Code: Improvement

#6873 Adds Free Miners from Yogstation
  _maps/RandomRuins/SpaceRuins/freeminer_asteroid.dmm
  _maps/RandomRuins/SpaceRuins/freeminer_ship.dmm
  _maps/shuttles/ruin_freeminer.dmm
  code/__DEFINES/radio.dm
  code/__DEFINES/role_preferences.dm
  code/datums/ruins/space.dm
  code/datums/shuttles/ruin.dm
  code/game/area/areas/shuttles.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/mob_spawn/ghost_roles/space_roles.dm
Labels: Feature: Feature, Approval: admin approved, Process: should testmerge

#7131 Lets ethereals wear underclothes
  monkestation/code/modules/mob/living/carbon/human/species_type/ethereal.dm
Labels: Feature: Feature

#7127 prevent becoming your own master through weird xenobio golem mind transfer shenaniganry
  code/datums/mind/antag.dm
Labels: Code: Fix

#7126 hopefully prevent storyteller from running roundstart high threat antags back-to-back
  monkestation/code/modules/storytellers/converted_events/_base_event.dm
  monkestation/code/modules/storytellers/gamemode_subsystem.dm
Labels: QoL, Approval: admin approved, Process: should testmerge

#7140 Gives NT reps a good assistant points puncher
  monkestation/code/modules/blueshift/machines/good_assistant.dm
Labels: Code: Fix, Approval: admin approved

#7106 Added antlers admin plush
  code/game/objects/items/admin_plushies.dm
  icons/obj/admin_plushies.dmi
Labels: Change: spriting, Process: do not merge, Process: do not testmerge

#7121 Add a new lint to ensure `genesis_call.dme` isn't accidentally changed
  .github/workflows/run_linters.yml
  tools/ci/check_genesis.sh
  tools/ci/genesis_call.dme.sha256sum
Labels: Tools

#7095 Evil Oni Addition of Doom and Gloom
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/dna.dm
  code/modules/mob/living/carbon/human/species_types/onis.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/species_parts/oni_bodyparts.dm
  code/modules/surgery/organs/internal/tongue/_tongue.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/unit_tests/screenshot_humanoids.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_oni.png
  config/game_options.txt
  icons/mob/species/oni/bodyparts.dmi
  monkestation/code/modules/client/preferences/species_features/goblin.dm
  monkestation/code/modules/client/preferences/species_features/oni.dm
  monkestation/code/modules/mob/dead/new_player/sprite_accessories/oni_accessories.dm
  monkestation/code/modules/ranching/satyr/external_organs.dm
  monkestation/code/modules/surgery/organs/external/goblin_accessories.dm
  monkestation/icons/mob/species/oni/oni_horns.dmi
  monkestation/icons/mob/species/oni/oni_tail.dmi
  monkestation/icons/mob/species/oni/oni_wings.dmi
  tgstation.dme
Labels: Code: Fix, Feature: Feature, Approval: admin approved, Process: should testmerge

#7147 Cleaner slimes will now target trash on dense turfs
  code/modules/mob/living/basic/bots/cleanbot/cleanbot_ai.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/behaviours/clean_target.dm
Labels: QoL

#7110 random bug fixes/debugging
  code/__HELPERS/~monkestation-helpers/roundend.dm
  code/controllers/subsystem/ambience.dm
  code/datums/mood.dm
  code/game/machinery/computer/records/security.dm
  code/game/machinery/launch_pad.dm
  code/game/objects/items/devices/broadcast_camera.dm
  code/modules/antagonists/heretic/magic/apetravulnera.dm
  code/modules/antagonists/heretic/magic/blood_siphon.dm
  code/modules/antagonists/heretic/magic/burglar_finesse.dm
  code/modules/antagonists/heretic/magic/madness_touch.dm
  code/modules/antagonists/heretic/magic/mind_gate.dm
  code/modules/antagonists/heretic/magic/moon_smile.dm
  code/modules/antagonists/heretic/magic/star_touch.dm
  code/modules/antagonists/heretic/magic/void_prison.dm
  code/modules/atmospherics/machinery/air_alarm/air_alarm_circuit.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/pipe_scrubber.dm
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  interface/interface.dm
  monkestation/code/modules/admin/verbs/ticketpanel.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
  monkestation/code/modules/client/verbs/looc.dm
  monkestation/code/modules/code_redemption/code_generator.dm
  monkestation/code/modules/twitch_bits/events/_base_event.dm
  monkestation/code/modules/virology/disease/symtoms/deadly/alkali.dm
  tgui/packages/tgui/interfaces/RequestsConsole/AnnouncementTab.tsx
Labels: Code: Fix, Process: should testmerge

#7167 Ooze-Lings no longer self destruct
  monkestation/code/datums/status_effects/changeling.dm
Labels: Code: Fix

#7164 Stops lockers ashing items when broken
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Balance, Approval: admin approved, Code: Improvement

#7188 Fix delay_round_end
  code/modules/admin/verbs/server.dm
Labels: Code: Fix

#7178 fixes the charlie station ai intercoms
  _maps/RandomRuins/IceRuins/icemoon_underground_oldstation.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/game/objects/items/devices/radio/radio.dm
Labels: Code: Fix, QoL

#7173 Giving some hecks to the ghost roles
  code/modules/mob/living/basic/drone/extra_drone_types.dm
  code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm
  code/modules/mob_spawn/ghost_roles/spider_roles.dm
  code/modules/mob_spawn/ghost_roles/venus_human_trap.dm
  monkestation/code/modules/antagonists/borers/code/items/egg.dm
Labels: Code: Fix

#7160 Prevents non-crew from rolling antag
  code/__DEFINES/traits/monkestation/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/modules/jobs/job_types/_job.dm
  monkestation/code/modules/storytellers/gamemode_subsystem.dm
Labels: Code: Fix, Process: should testmerge

#7144 Adds undershirt turtlenecks!
  code/datums/sprite_accessories.dm
  icons/mob/clothing/underwear.dmi
Labels: Feature: Feature

#7024 Fixes some issues with the mining pen pr
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  monkestation/code/modules/reagents/reagent_containers/hypospray.dm
  tgstation.dme
Labels: Approval: admin approved

#7185 Voooooooid raptor
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
Labels: Change: Mapping

#7165 High Resolution Yes Please
  .github/guides/VISUALS.md
  code/modules/client/preferences/pixel_size.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/pixel_size.tsx
Labels: QoL

#7158 Cryoing now takes you out of the lottery
  monkestation/code/modules/cryopods/_cryopod.dm
  monkestation/code/modules/store/atm/_atm.dm
Labels: Code: Fix

#7209 Fixing ice box charlie station's radiation storm issue (correctly this time)
  code/datums/weather/weather_types/radiation_storm.dm
  monkestation/code/datums/weather/weather_types/radiation_storm.dm
  tgstation.dme
Labels: Code: Fix

#7182 Pr Improving specific clothing stuff I like because it bugs me
  code/modules/clothing/chameleon.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/gloves/special.dm
  code/modules/clothing/masks/costume.dm
  code/modules/clothing/suits/costume.dm
Labels: Code: Fix, Feature: Feature, QoL

#7176 Ever want to strangle the sig tech?
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_say.dm
Labels: QoL

#7194 makes pubby's nt rep office not shit
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Change: Mapping

#7217 Fix store not giving you the right lizard plushie
  monkestation/code/modules/store/store_items/plushies.dm
Labels: Code: Fix

#7220 you can now click on the URL in the tgui audio player widget
  tgui/packages/tgui-panel/audio/NowPlayingWidget.jsx
Labels: QoL, Code: TGUI

#7214 [PORTS] Sitting on bar stools, automatic un-observe, and helping poor medibots.
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/basic/bots/medbot/medbot_ai.dm
Labels: Code: Fix, Feature: Feature, QoL

#7111 Updates Icebox's service to be on par with TG
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: Change: Mapping

#7231 automatically remove nametag keybindings from prefs
  code/modules/client/preferences_savefile.dm
Labels: Code: Fix

#7215 Theseus Fixes and Theseus Botany touchup
  _maps/map_files/Theseus/Theseus.dmm
Labels: Change: Mapping, Code: Fix

#7200 fire breath now requires your mouth to be uncovered
  code/datums/actions/mobs/fire_breath.dm
Labels: Balance, Approval: admin approved

#7227 Exodrone - tackle right click - atmos temp
  code/__DEFINES/atmospherics/atmos_core.dm
  code/datums/components/tackle.dm
  code/modules/explorer_drone/exodrone.dm
  tgui/packages/tgui/interfaces/SatelliteControl.tsx
Labels: Code: Fix, Approval: admin approved

#7251 Fix some CI failures with ghost player arenas
  monkestation/code/modules/ghost_players/arena/maps/neon.dmm
  monkestation/code/modules/ghost_players/arena/maps/snow.dmm
Labels: Code: Fix

#7205 Carved Square Pumpkin (Jackenstein Pumpkin)
  code/modules/clothing/head/hardhat.dm
  icons/mob/clothing/head/costume.dmi
  icons/obj/clothing/head/costume.dmi
  monkestation/code/modules/loadouts/items/heads.dm
Labels: Feature: Feature, Approval: admin approved

#7207 evil drones don't get passthrough
  code/modules/mob/living/basic/drone/extra_drone_types.dm
  monkestation/code/modules/antagonists/clock_cult/mobs/cogscarab.dm
Labels: Balance, Approval: admin approved

#7253 Nerfs void chill
  code/modules/antagonists/heretic/status_effects/void_chill.dm
Labels: Balance, Approval: admin approved

#7168 implement weight decay for storytellers
  code/controllers/subsystem/events.dm
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/antagonists/pirate/pirate_event.dm
  code/modules/events/_event.dm
  code/modules/events/ghost_role/operative.dm
  monkestation/code/controllers/subsystem/job.dm
  monkestation/code/modules/and_roll_credits/episode_names.dm
  monkestation/code/modules/assault_ops/code/roundstart_event.dm
  monkestation/code/modules/events/summon_wizard_event.dm
  monkestation/code/modules/storytellers/converted_events/_base_event.dm
  monkestation/code/modules/storytellers/converted_events/event_overrides.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodcult.dm
  monkestation/code/modules/storytellers/converted_events/solo/changeling.dm
  monkestation/code/modules/storytellers/converted_events/solo/clockwork_cult.dm
  monkestation/code/modules/storytellers/converted_events/solo/commando_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/malf.dm
  monkestation/code/modules/storytellers/converted_events/solo/nuclear_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/revolutionary.dm
  monkestation/code/modules/storytellers/converted_events/solo/wizard.dm
  monkestation/code/modules/storytellers/gamemode_subsystem.dm
  monkestation/code/modules/storytellers/scheduled_events.dm
  monkestation/code/modules/storytellers/storytellers/_storyteller.dm
Labels: Balance, Approval: admin approved, Process: should testmerge

#7234 Turtleneck adjustments, det holster fits more mags, adjusts and adds two items to the black market!
  code/game/objects/items/storage/holsters.dm
  code/modules/cargo/markets/market_items/misc.dm
  icons/mob/clothing/underwear.dmi
Labels: Change: spriting, Feature: Feature, Balance, Approval: admin approved

#7213 [BOUNTY] bridge assistants
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LeadPoisoningStation/LeadPoisoningStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/jobs.dm
  code/datums/id_trim/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/modules/antagonists/traitor/objectives/destroy_heirloom.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/jobs/job_types/bridgeassistant.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  icons/mob/huds/hud.dmi
  monkestation/code/datums/id_trim/jobs.dm
  monkestation/code/modules/antagonists/traitor/objectives/kidnapping.dm
  monkestation/code/modules/blueshift/machines/access_vending.dm
  monkestation/code/modules/storytellers/converted_events/solo/blob_infection.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodcult.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodsuckers.dm
  monkestation/code/modules/storytellers/converted_events/solo/brother.dm
  monkestation/code/modules/storytellers/converted_events/solo/changeling.dm
  monkestation/code/modules/storytellers/converted_events/solo/clockwork_cult.dm
  monkestation/code/modules/storytellers/converted_events/solo/commando_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/ghosts/nuclear_operative_ghost.dm
  monkestation/code/modules/storytellers/converted_events/solo/heretic.dm
  monkestation/code/modules/storytellers/converted_events/solo/monsterhunter.dm
  monkestation/code/modules/storytellers/converted_events/solo/nuclear_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/obsessed.dm
  monkestation/code/modules/storytellers/converted_events/solo/revolutionary.dm
  monkestation/code/modules/storytellers/converted_events/solo/traitor.dm
  tgstation.dme
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
Labels: Change: Mapping, Feature: Feature, Approval: admin approved

#7262 Fix Helio Asteroid Magnet
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Change: Mapping, Code: Fix

#7277 Fixes Issue #7275
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: Change: Mapping

#7271 PORT from tgstation: Fixes records console sechuds glitch, ninja sechuds glitch
  code/game/data_huds.dm
  code/game/machinery/computer/records/security.dm
  code/modules/antagonists/ninja/ninjaDrainAct.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Code: Fix, Approval: admin approved, Fixed Upstream

#7294 Reinforces metastation's singulo/tesla
  _maps/~monkestation/RandomEngines/MetaStation/singularity.dmm
Labels: Change: Mapping, Approval: admin approved

#7270 [BOUNTY] Rennovates Box Station Kitchen
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/~monkestation/RandomBars/Box/bloody_bar.dmm
  _maps/~monkestation/RandomBars/Box/clockwork_bar.dmm
  _maps/~monkestation/RandomBars/Box/default_bar.dmm
  _maps/~monkestation/RandomBars/Box/vietmoth_bar.dmm
Labels: Change: Mapping

#7212 Adjusts junior lone op weight/spawn timer, increases the chance lone ops gain weight
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/events/ghost_role/operative.dm
Labels: Balance, Approval: admin approved

#7286 Proper fix for runechat icons being too big
  icons/ui_icons/screentips/cursor_hints.dmi
  interface/skin.dmf
Labels: Code: Fix

#7298 RCD and cable map issues
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/Theseus/Theseus.dmm
Labels: Change: Mapping

#7293 Some mentor fixes
  code/__HELPERS/admin.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/job.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/ooc.dm
  code/modules/mob/dead/new_player/latejoin_menu.dm
  monkestation/code/modules/clothing/neck/cloaks.dm
  monkestation/code/modules/loadouts/loadout_middleware.dm
  monkestation/code/modules/mentor/client.dm
  monkestation/code/modules/mentor/mentor_datum.dm
  monkestation/code/modules/mentor/mentor_manager.dm
  monkestation/code/modules/mentor/mentor_ranks.dm
Labels: Code: Fix, Code: Improvement

#7300 Player Panel fix and a small NTSL optimization
  code/modules/admin/topic.dm
  monkestation/code/modules/NTSL/code/coding_language/implementations/telecomms_translator.dm
  monkestation/code/modules/NTSL/code/coding_language/interpreter/objects.dm
Labels: Code: Fix, Code: Improvement

#7326 Second Batch of Kitchen Refurbishment fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Change: Mapping, Code: Fix

#7304 Deltarune costumes!
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/gloves/costume.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/shoes/costume.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/costume.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head/wizard.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/suits/wizard.dmi
  icons/mob/clothing/under/costume.dmi
  icons/mob/species/misc/digitigrade.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/head/wizard.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits/wizard.dmi
  icons/obj/clothing/under/costume.dmi
Labels: Feature: Feature

#7341 Adds a new alternate job title for xenobiologist
  monkestation/code/modules/client/preferences/alt_jobs/titles.dm
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
Labels: Feature: Feature, Approval: admin approved

#7317 [PORT] Moves init time display out of chat (and make it hideable since most people don't care)
  code/__DEFINES/MC.dm
  code/__HELPERS/game.dm
  code/controllers/master.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/early_assets.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/title.dm
  code/datums/mapgen/CaveGenerator.dm
  code/modules/client/preferences/init_stats.dm
  code/modules/mob/dead/new_player/login.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/init_stats.tsx
Labels: QoL

#7319 [PORT] Power line switching
  code/__DEFINES/power.dm
  code/__DEFINES/~monkestation/blueshift.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/cable.dm
  code/modules/power/floodlight.dm
  code/modules/power/multiz.dm
  code/modules/power/power.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/smes.dm
  code/modules/power/terminal.dm
  code/modules/power/tesla/coil.dm
  code/modules/power/turbine/turbine.dm
  monkestation/code/modules/power/singularity/rad_collector.dm
Labels: Code: Fix

#7053 Techweb updates.
  code/modules/research/stock_parts.dm
  code/modules/research/techweb/biology_nodes.dm
  code/modules/research/techweb/cyborg_nodes.dm
  code/modules/research/techweb/engi_nodes.dm
  code/modules/research/techweb/mech_nodes.dm
  code/modules/research/techweb/medbay_nodes.dm
  code/modules/research/techweb/modsuit_nodes.dm
  code/modules/research/techweb/robo_nodes.dm
  code/modules/research/techweb/security_nodes.dm
  monkestation/code/modules/cybernetics/tech_nodes.dm
  monkestation/code/modules/microfusion/code/microfusion_techweb.dm
  monkestation/code/modules/virology/research/research.dm
Labels: Removal, Feature: Feature, Balance

#7328 Ports Investigation Mode from Daedalus
  code/datums/status_effects/noir.dm
  code/modules/client/client_colour.dm
  code/modules/clothing/head/detective_fedora.dm
  code/modules/clothing/head/jobs.dm
  tgstation.dme
Labels: peak, Feature: Feature

#7310 Hoverdog
  code/datums/components/riding/riding_vehicle.dm
  code/game/objects/items/generic_beacon.dm
  code/modules/vehicles/hoverdog.dm
  code/modules/vehicles/vehicle_key.dm
  icons/obj/car.dmi
  icons/obj/vehicles.dmi
  tgstation.dme
Labels: Balance, Funny

#7355 [PORT] Fixed false anomaly announcements
  code/modules/antagonists/pirate/pirate_event.dm
  code/modules/events/anomaly/_anomaly.dm
  code/modules/events/anomaly/anomaly_bioscrambler.dm
  code/modules/events/anomaly/anomaly_bluespace.dm
  code/modules/events/anomaly/anomaly_dimensional.dm
  code/modules/events/anomaly/anomaly_ectoplasm.dm
  code/modules/events/anomaly/anomaly_flux.dm
  code/modules/events/anomaly/anomaly_grav.dm
  code/modules/events/anomaly/anomaly_hallucination.dm
  code/modules/events/anomaly/anomaly_pyro.dm
  code/modules/events/anomaly/anomaly_vortex.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/grey_tide.dm
  code/modules/events/scrubber_clog.dm
  code/modules/events/shuttle_loan/shuttle_loan_event.dm
  monkestation/code/modules/events/anomaly/anomaly_clown.dm
  monkestation/code/modules/events/anomaly/anomaly_fluid.dm
  monkestation/code/modules/events/anomaly/anomaly_frost.dm
  monkestation/code/modules/events/anomaly/anomaly_lifebringer.dm
  monkestation/code/modules/events/anomaly/anomaly_monkey.dm
  monkestation/code/modules/events/anomaly/anomaly_radiation.dm
  monkestation/code/modules/events/anomaly/anomaly_storm.dm
  monkestation/code/modules/events/anomaly/anomaly_walterverse.dm
Labels: Code: Fix

#7359 This is the part where he kill you (Thesues and blueshift minor update)
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/Theseus/Theseus.dmm
Labels: Change: Mapping

#7375 Removes "brotherly connections" on examine
  monkestation/code/modules/blueshift/items/soul_catcher.dm
Labels: QoL

#7354 [PORT] nuke /obj/vehicle/sealed/mecha/working
  _maps/RandomRuins/LavaRuins/lavaland_surface_random_ripley.dmm
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/tramstation/maintenance_modules/atmoscilower_attachment_a_3.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/ert_deathsquad.dmm
  _maps/shuttles/ert_dropship-engineering.dmm
  _maps/~monkestation/shipbreaking/gorlex_cruiser.dmm
  code/__DEFINES/mecha.dm
  code/__DEFINES/traits/declarations.dm
  code/datums/components/armor_plate.dm
  code/game/objects/effects/spawners/random/exotic.dm
  code/modules/cargo/bounties/mech.dm
  code/modules/shuttle/shuttle_events/player_controlled.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/tools/medical_tools.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
  code/modules/vehicles/mecha/equipment/tools/work_tools.dm
  code/modules/vehicles/mecha/mecha_construction_paths.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
  code/modules/vehicles/mecha/mecha_movement.dm
  code/modules/vehicles/mecha/working/clarke.dm
  code/modules/vehicles/mecha/working/ripley.dm
  code/modules/vehicles/mecha/working/working.dm
  monkestation/code/datums/components/crafting/makeshift_mechs.dm
  monkestation/code/game/mecha/makeshift/locker_mech.dm
  monkestation/code/modules/ERT/equipment/ERT_misc_equipment.dm
  monkestation/code/modules/vehicles/mecha/working/ripley.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/Mecha/UtilityModulesPane.tsx
Labels: Code: Fix, Code: Improvement

#7348 [PORT] Decal Painter refactor + merge with tile sprayer + more decals to paint
  _maps/RandomRuins/SpaceRuins/derelict_construction.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_maints_grape.dmm
  code/__DEFINES/tools.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/decals/turfdecal/markings.dm
  code/game/objects/items/airlock_painter.dm
  code/game/objects/items/tools/painter/airlock_painter.dm
  code/game/objects/items/tools/painter/decal_painter.dm
  code/game/objects/items/tools/painter/paintable_decals.dm
  code/modules/research/designs/autolathe/engineering_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/turf/decals.dmi
  monkestation/code/modules/blueshift/decals/nova.dm
  monkestation/code/modules/blueshift/designs/colony.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/DecalPainter.tsx
Labels: Removal, QoL, Code: Improvement

#7377 Plastic Heretic Blades
  code/datums/components/crafting/melee_weapon.dm
  code/game/objects/items/toys.dm
  code/modules/vending/toys.dm
Labels: Approval: admin approved
