Repository Monkestation/Monkestation2.0, pull requests merged in 2025-02, with the labels that each got.

#5160 Fix the chat reliability subsystem being completely useless (hopefully)
  tgui/packages/tgui-panel/chat/middleware.js
Labels: Fix

#5232 Boxstations engineering disposals will no longer explode
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping, Fix

#5206 Fix a bunch of hard-dels; fix plumbing stuff being qdel'd before initialization; and make unit tests actually output `data/unit_tests.json` on CI
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/game/atoms_movable.dm
  code/modules/unit_tests/unit_test.dm
  monkestation/code/modules/botany/species/apid/hive/hive_object.dm
  monkestation/code/modules/map_gen_expansions/mushroom/extraction/structures/extractor/hub.dm
  monkestation/code/modules/map_gen_expansions/mushroom/extraction/structures/extractor/main.dm
  monkestation/code/modules/slimecore/machines/extract_requestor.dm
  monkestation/code/modules/slimecore/machines/slime_market.dm
  monkestation/code/modules/slimecore/machines/slime_market_computer.dm
Labels: Fix, Performance / Optimization

#5202 Adds NT frontier and NT Science Hub to Sci PDAs; NT Frontier to RD PDA
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
Labels: Tweak, awaiting admin review

#5090 Pathology Transformation cures.
  monkestation/code/modules/virology/disease/premades/transformations.dm
  monkestation/code/modules/virology/disease/symtoms/restricted/stage1.dm
Labels: Balance

#5114 Martial arts tweaks and fixes
  code/datums/martial/cqc.dm
  code/datums/martial/sleeping_carp.dm
  monkestation/code/modules/antagonists/cult/blood_magic.dm
  monkestation/code/modules/martial_arts/awakened_dragon.dm
  monkestation/code/modules/martial_arts/tunnel_arts.dm
  monkestation/code/modules/spells/spell_types/touch/_touch.dm
  tgstation.dme
Labels: Fix, Balance, QoL, awaiting admin review

#4995 Spess.tv
  code/__DEFINES/~monkestation/dcs/signals/signals_global.dm
  code/__DEFINES/~monkestation/hud.dm
  code/game/machinery/computer/telescreen.dm
  code/game/objects/items/devices/broadcast_camera.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/pda.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/secureye.dm
  code/modules/unit_tests/unit_test.dm
  monkestation/code/game/machinery/computer/camera.dm
  monkestation/code/game/machinery/computer/telescreen.dm
  monkestation/code/game/objects/items/devices/broadcast_camera.dm
  monkestation/code/modules/cassettes/machines/media/jukebox.dm
  monkestation/code/modules/modular_computers/file_system/programs/spesstv.dm
  tgstation.dme
Labels: Feature, Refactor/Rework, awaiting admin review

#5228 Mark of Rust can no longer damage indestructible items
  monkestation/code/modules/antagonists/heretic/status_effects/mark_effects.dm
Labels: Fix

#5223 Fix quirks not processing
  code/datums/quirks/_quirk.dm
  code/datums/quirks/negative_quirks/allergic.dm
  code/datums/quirks/negative_quirks/brain_problems.dm
  code/datums/quirks/negative_quirks/claustrophobia.dm
  code/datums/quirks/negative_quirks/junkie.dm
  code/datums/quirks/positive_quirks/drunk_healing.dm
Labels: Fix

#5087 Beepsky stuns are now closer to a stunbaton rather than an instant hardstun
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Balance, awaiting admin review

#5237 Defer the asteroid magnet's initial map generation to LateInitialize
  monkestation/code/modules/art_sci_overrides/asteroids/asteroid_magnet.dm
Labels: Fix

#5236 Dr scrubs and poppy
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/~monkestation/RandomEngines/BoxStation/supermatter.dmm
  _maps/~monkestation/RandomEngines/MetaStation/supermatter.dmm
  _maps/~monkestation/RandomEngines/TramStation/supermatter.dmm
Labels: Mapping

#5174 [PORT] Datumizes pAI screen images
  code/modules/pai/card.dm
  code/modules/pai/datums/screen_icon.dm
  code/modules/pai/death.dm
  code/modules/pai/pai.dm
  code/modules/pai/software.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PaiInterface/System.tsx
  tgui/packages/tgui/interfaces/PaiInterface/constants.ts
  tgui/packages/tgui/interfaces/PaiInterface/types.ts
Labels: Refactor/Rework

#5152 MENTOR CLOAK
  monkestation/code/modules/clothing/neck/cloaks.dm
  monkestation/icons/hud/radial_mentor_cloak.dmi
  monkestation/icons/mob/clothing/necks/mentor_cloak_overlays.dmi
  monkestation/icons/mob/clothing/necks/mentor_cloaks.dmi
  monkestation/icons/obj/clothing/necks.dmi
  monkestation/icons/obj/clothing/necks/mentor_cloaks.dmi
Labels: enhancement

#5204 Fix the "Debug Controller" verb
  code/controllers/admin.dm
Labels: Tools

#5182 Unit Test failures now output a job summary, making it easier to see what the failures are.
  .github/workflows/run_integration_tests.yml
  tools/ci/run_server.sh
Labels: Tools

#5259 Slightly raises beepsky's health
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Balance

#5231 Update VoidRaptor.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
Labels: Mapping

#5235 Magically summoned food (such as the Summon Cheese spell) no longer decomposes
  code/modules/antagonists/wizard/grand_ritual/grand_side_effect.dm
  monkestation/code/modules/antagonists/wizard/grand_ritual/grand_side_effect.dm
  monkestation/code/modules/spells/spell_types/conjure/cheese.dm
  tgstation.dme
Labels: QoL

#5178 Buffs assault ops long arms
  monkestation/code/modules/blueshift/items/company_guns.dm
Labels: Balance

#5192 Board access changes
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/mining_designs.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  monkestation/code/modules/blood_datum/designs.dm
  monkestation/code/modules/blueshift/machines/good_assistant.dm
  monkestation/code/modules/factory_type_beat/designs.dm
  monkestation/code/modules/research/designs/computer_designs.dm
  monkestation/code/modules/research/designs/machine_designs.dm
  monkestation/code/modules/slimecore/research_and_recipes.dm
  monkestation/code/modules/smithing/research/circuits_and_research.dm
  monkestation/code/modules/virology/research/research.dm
Labels: Mapping, Balance

#5162 Increases the shuttle stall time for assault operatives.
  monkestation/code/modules/assault_ops/code/interrogator.dm
Labels: Balance

#5258 Fix 3 stray "Vacant Office" tiles on MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix

#4863 Tutel - Tactical shield with integral shotgun loader
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/shields_lefthand.dmi
  icons/mob/inhands/equipment/shields_righthand.dmi
  icons/obj/weapons/shields.dmi
  monkestation/code/game/objects/items/tactical_shields.dm
  monkestation/code/modules/blueshift/armaments/nri.dm
  monkestation/code/modules/blueshift/cargo/armory.dm
  tgstation.dme
Labels: Feature

#4846 Tgui Player & Options panel - Please Review Me
  code/datums/keybinding/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/mob.dm
  code/modules/requests/request_manager.dm
  code/modules/wiremod/core/admin_panel.dm
  monkestation/code/modules/veth_misc_items/veth_player_panel/readme.md
  monkestation/code/modules/veth_misc_items/veth_player_panel/veth_player_panel.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/VUAP_personal.tsx
  tgui/packages/tgui/interfaces/VethPlayerPanel.tsx
Labels: enhancement, QoL, admin approved

#5163 Ports shared particle holders
  code/datums/components/burning.dm
  code/datums/components/unusual_effect.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
  code/game/objects/effects/particles/fire.dm
  code/game/objects/effects/shared_particle_holder.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/food_and_drinks/machinery/coffeemaker.dm
  code/modules/food_and_drinks/machinery/oven.dm
  code/modules/food_and_drinks/machinery/stove_component.dm
  monkestation/code/modules/blueshift/structures/primative.dm
  monkestation/code/modules/blueshift/structures/sauna_oven.dm
  monkestation/code/modules/botany/components/plant_growth_holder.dm
  monkestation/code/modules/factory_type_beat/ore_vent.dm
  monkestation/code/modules/visual_changes/splatter.dm
  tgstation.dme
Labels: Performance / Optimization

#5261 `TRAIT_NO_TRANSFORMATION_STING` now actually prevents transformation stings
  code/datums/status_effects/debuffs/dna_transformation.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: Fix

#5257 Fix not being able to build several vendors (+ unit test to prevent similar issues)
  _maps/multiz_debug.json
  _maps/runtimestation.json
  code/game/objects/items/circuitboards/machines/machine_circuitboards.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/vendor_boards.dm
  monkestation/code/modules/mech_comp/vending_machine.dm
Labels: Fix

#5256 Some small `SSparticle_weather` fixes
  monkestation/code/modules/outdoors/code/controllers/subsystem/particle_weather.dm
  monkestation/code/modules/outdoors/code/datum/particle_weathers/_particle_weather.dm
Labels: Fix

#5184 Fix cybernetic hacking for others
  monkestation/code/modules/cybernetics/implant_items/cyberlink_connector.dm
Labels: Fix

#5264 Adds DNA Recovery surgery
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/game/machinery/computer/cloning.dm
  monkestation/code/game/machinery/exp_cloner.dm
  monkestation/code/modules/research/designs/medical_designs.dm
  monkestation/code/modules/surgery/advanced/dna_recovery.dm
  tgstation.dme
Labels: Feature

#4805 End/Nerf Life As We Know It
  code/modules/reagents/chemistry/recipes/others.dm
Labels: enhancement, Minor, Monkeys, fuck it we ball

#4953 MY LIEGE! NO!! is what rats and tamed mice will now shout at their owner huting themselves instead of killing them for that mistake.
  code/__DEFINES/ai/ai_blackboard.dm
  code/__DEFINES/ai/pet_commands.dm
  code/datums/components/pet_commands/pet_commands_basic.dm
  code/modules/mob/living/basic/icemoon/wolf/wolf_ai.dm
  code/modules/mob/living/basic/minebots/minebot_ai.dm
  code/modules/mob/living/basic/vermin/cockroach.dm
  code/modules/mob/living/basic/vermin/frog.dm
  code/modules/mob/living/basic/vermin/mouse.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/mob_say.dm
Labels: Fix

#5260 Update `memorystats.dll` to v0.2.0
  memorystats.dll
  monkestation/code/controllers/subsystem/memory_stats.dm
Labels: Tools, Fix

#5293 Blacklists money from interaction component
  monkestation/code/modules/mech_comp/objects/interactor.dm
Labels: Fix

#5292 Blob zombie fixes
  code/modules/antagonists/blob/overmind.dm
  code/modules/mob/living/basic/blob_minions/blob_zombie.dm
Labels: Fix

#5291 Prevent bioscrambling from/into unremovable/hidden organs or limbs
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: QoL, admin approved

#5288 Convert all traits given by status effects to use `TRAIT_STATUS_EFFECT(id)`
  code/__DEFINES/traits/monkestation/sources.dm
  code/__DEFINES/traits/sources.dm
  code/datums/status_effects/buffs.dm
  code/datums/status_effects/buffs/stop_drop_roll.dm
  code/datums/status_effects/debuffs/debuffs.dm
  code/datums/status_effects/debuffs/pacifism.dm
  code/datums/status_effects/debuffs/silenced.dm
  code/datums/status_effects/debuffs/tower_of_babel.dm
  code/datums/status_effects/drug_effects.dm
  code/datums/status_effects/gas.dm
  code/datums/status_effects/neutral.dm
  code/datums/status_effects/song_effects.dm
  code/datums/status_effects/wound_effects.dm
  code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_buff.dm
  code/modules/antagonists/heretic/magic/realignment.dm
  code/modules/antagonists/heretic/magic/shadow_cloak.dm
  code/modules/antagonists/heretic/status_effects/buffs.dm
  code/modules/antagonists/heretic/status_effects/debuffs.dm
  code/modules/antagonists/heretic/status_effects/ghoul.dm
  code/modules/antagonists/heretic/status_effects/mark_effects.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/spells/spell_types/shapeshift/_shape_status.dm
  monkestation/code/datums/status_effects/buffs.dm
  monkestation/code/datums/status_effects/changeling.dm
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_buff.dm
  monkestation/code/modules/antagonists/monster_hunters/tools/bnuuy_mask.dm
  monkestation/code/modules/art_sci_overrides/artifact_effects/false_rod.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/slasher_regenerate.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_frenzy.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_sol.dm
  monkestation/code/modules/bloodsuckers/clans/_clan_flavortext.dm
  monkestation/code/modules/can_spessmen_feel_pain/pain/modifiers.dm
  monkestation/code/modules/cybernetics/implant_items/weapons/mantis_blade.dm
  monkestation/code/modules/ghost_players/centcom_grace.dm
  monkestation/code/modules/slimecore/crossbreeding/regenerative/effect.dm
Labels: Code Improvement

#5280 [PORT] Makes hoods into a component
  code/__DEFINES/dcs/signals/signals_object.dm
  code/datums/components/toggle_attached_clothing.dm
  code/game/objects/items.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/antagonists/heretic/items/heretic_armor.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/clothing/suits/ablativecoat.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/clothing/suits/wintercoats.dm
  code/modules/mod/mod_control.dm
  code/modules/unit_tests/ablative_hud.dm
  monkestation/code/modules/antagonists/clock_cult/reebe_modules.dm
  monkestation/code/modules/antagonists/monster_hunters/hunter_datum.dm
  monkestation/code/modules/clothing/under/jobs/civilian/clown_mime.dm
  tgstation.dme
Labels: Refactor/Rework

#5299 Connect the Departures Lobby's Security post's vents, in Icebox
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: Mapping, Fix

#5121 Makes advanced factories possible -- Bunch of changes to mech component and the assembler
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_recipes.dm
  monkestation/code/modules/factory_type_beat/machinery/assembler.dm
  monkestation/code/modules/mech_comp/objects/_object.dm
  monkestation/code/modules/mech_comp/objects/interactor.dm
Labels: QoL

#5326 fix: Supplypod falling sounds varying
  monkestation/code/modules/cargo/supplypod.dm
  tgstation.dme
Labels: Fix

#5313 Minor botany fixes and QoL
  monkestation/code/modules/hydroponics/machines/composter.dm
  tgui/packages/tgui/interfaces/Biogenerator.tsx
Labels: Fix, QoL

#5325 Add a `DISABLE_DREAMLUAU` define, for disabling dreamluau at compile-time
  code/__DEFINES/logging.dm
  code/__HELPERS/_dreamluau.dm
  code/__HELPERS/logging/debug.dm
  code/_compile_options.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/lua.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/lua/_wrappers.dm
  code/modules/admin/verbs/lua/helpers.dm
  code/modules/admin/verbs/lua/lua_editor.dm
  code/modules/admin/verbs/lua/lua_state.dm
  code/modules/error_handler/error_handler.dm
  code/modules/logging/categories/log_category_debug.dm
Labels: Code Improvement

#5310 [PORT] `/mob/living/simple_animal` is now frozen - subtypes should be refactored to basic mobs.
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  monkestation/code/modules/aesthetics/objects/misc.dm
  monkestation/code/modules/mob/living/simple_animal/bot/secbot.dm
  monkestation/code/modules/mob/living/simple_animal/hostile/feral.dm
  monkestation/code/modules/mob/living/simple_animal/hostile/syndicat.dm
  monkestation/code/modules/virology/disease/symtoms/annoying/cyborg_vomit.dm
  tgstation.dme
Labels: Tools, peak

#5306 [PORT] Optimizes `/proc/icon_exists()`
  code/__HELPERS/icons.dm
  code/__HELPERS/lighting.dm
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/overlays.dm
  code/datums/greyscale/layer.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/modules/admin/verbs/debug.dm
  code/modules/asset_cache/assets/crafting.dm
  code/modules/asset_cache/assets/research_designs.dm
  code/modules/projectiles/gun.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/unit_tests/suit_storage_icons.dm
Labels: Performance / Optimization

#5309 Fix the Delightful Effect symptom
  monkestation/code/modules/datums/mood_events/generic_positive_events.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/delightful.dm
Labels: Fix

#5305 Fix blades equipped to a void cloak having visible sprites
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/traits/_traits.dm
  code/datums/brain_damage/phobia.dm
  code/datums/elements/dextrous.dm
  code/datums/elements/strippable.dm
  code/game/objects/items.dm
  code/modules/antagonists/heretic/items/heretic_armor.dm
  code/modules/antagonists/traitor/objectives/steal.dm
  code/modules/clothing/head/wig.dm
  code/modules/hallucination/inhand_fake_item.dm
  code/modules/mob/living/basic/drone/_drone.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mod/modules/modules_antag.dm
  monkestation/code/datums/components/basic_inhands.dm
  monkestation/code/modules/antagonists/heretic/status_effects/mark_effects.dm
Labels: Fix

#5335 stinky mentor bonus
  code/__HELPERS/~monkestation-helpers/roundend.dm
Labels: Major, QoL

#5344 Biogenerator UI followup fixes
  tgui/packages/tgui/interfaces/Biogenerator.tsx
Labels: Minor, Fix

#4961 (Bounty) Combine footsteps for jackboots + more + new element
  code/__DEFINES/footsteps.dm
  code/__DEFINES/~monkestation/dcs/signals/signals_mob/signals_mob_main.dm
  code/datums/elements/footstep.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/cowboy.dm
  monkestation/code/datums/elements/shoesteps.dm
  monkestation/code/modules/clothing/shoes/shoe.dm
  monkestation/sound/effects/hl2/footstep/combine1.ogg
  monkestation/sound/effects/hl2/footstep/combine2.ogg
  monkestation/sound/effects/hl2/footstep/combine3.ogg
  monkestation/sound/effects/hl2/footstep/combine4.ogg
  monkestation/sound/effects/hl2/footstep/combine5.ogg
  monkestation/sound/effects/hl2/footstep/combinedirt1.ogg
  monkestation/sound/effects/hl2/footstep/combinedirt2.ogg
  monkestation/sound/effects/hl2/footstep/combinedirt3.ogg
  monkestation/sound/effects/hl2/footstep/combinedirt4.ogg
  monkestation/sound/effects/hl2/footstep/combinedirt5.ogg
  monkestation/sound/effects/hl2/footstep/combinemetal1.ogg
  monkestation/sound/effects/hl2/footstep/combinemetal2.ogg
  monkestation/sound/effects/hl2/footstep/combinemetal3.ogg
  monkestation/sound/effects/hl2/footstep/combinemetal4.ogg
  monkestation/sound/effects/hl2/footstep/combinemetal5.ogg
  monkestation/sound/effects/hl2/footstep/combinemetalwalkway1.ogg
  monkestation/sound/effects/hl2/footstep/combinemetalwalkway2.ogg
  monkestation/sound/effects/hl2/footstep/combinemetalwalkway3.ogg
  monkestation/sound/effects/hl2/footstep/combinemetalwalkway4.ogg
  monkestation/sound/effects/hl2/footstep/combinemetalwalkway5.ogg
  monkestation/sound/effects/hl2/footstep/combinewood1.ogg
  monkestation/sound/effects/hl2/footstep/combinewood2.ogg
  monkestation/sound/effects/hl2/footstep/combinewood3.ogg
  monkestation/sound/effects/hl2/footstep/combinewood4.ogg
  monkestation/sound/effects/hl2/footstep/combinewood5.ogg
  monkestation/sound/effects/hl2/footstep/sources.txt
  tgstation.dme
Labels: Tweak

#5342 Amber and Yellow alert now have the same shuttle call time as Blue alert
  code/modules/security_levels/security_level_datums.dm
Labels: QoL

#5343 Prevent the effects of certain plant genes from scaling past 100 potency
  code/__DEFINES/~monkestation/botany.dm
  code/modules/hydroponics/plant_genes.dm
  monkestation/code/controllers/subsystem/glowshrooms.dm
  monkestation/code/game/objects/effects/glowshroom.dm
Labels: Balance, QoL

#5336 Feburary Issue Report fixes
  code/datums/actions/mobs/assume_form.dm
  code/modules/food_and_drinks/machinery/smartfridge.dm
  code/modules/mining/lavaland/tendril_loot.dm
  code/modules/power/tesla/coil.dm
  monkestation/code/modules/blueshift/effects/ash_walker.dm
  monkestation/code/modules/factory_type_beat/ore_vent.dm
  monkestation/code/modules/ghost_players/job_helpers/organ_printer.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ethereal.dm
Labels: Fix

#5370 Fix opening the Lua editor being broken
  code/modules/admin/verbs/lua/lua_editor.dm
Labels: Fix

#5369 plane debugger now checks for +DEBUG
  code/modules/admin/verbs/plane_debugger.dm
Labels: Tools, Fix

#5246 Syndicate Depot Updates and Shipbreaking Is Now Ruin-Friendly
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/black_peregrine.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/gasstation.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/goonshuttlesmall.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/gorlex_cruiser.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/mcsail.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/mcsteal_sloop.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/mess.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/mule.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_altar.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_banana.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_bathroom.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_chapel.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_diner.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_escape_pod.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/old_repair.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/robotics.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/squid.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/torus.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/true_church.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/wanglius.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/whale.dmm
  monkestation/code/modules/syndicate_ghostroles/depot.dm
Labels: Expansion

#5368 TRAIT_NOHUNGER and TRAIT_FAT refactor stuff
  code/modules/surgery/organs/stomach/_stomach.dm
  monkestation/code/modules/mob/living/carbon/human/init_signals.dm
  monkestation/code/modules/mob/living/init_signals.dm
  monkestation/code/modules/mob/living/living.dm
Labels: Refactor/Rework

#5385 Seedlings and Craig now use JPS pathfinding instead of basic avoidance
  code/modules/mob/living/basic/jungle/seedling/seedling_ai.dm
  monkestation/code/modules/botany/potty.dm
Labels: QoL, admin approved

#5386 [PORT] Allows Signers to send COMSIG_MOB_SAY
  code/modules/mob/living/living_say.dm
Labels: Fix, admin approved

#5383 Nerf delightful effect syndrome's moodlet
  monkestation/code/modules/datums/mood_events/generic_positive_events.dm
Labels: Balance, admin approved

#5381 Better rechargers for goldeneye and fixes surgery disk
  _maps/shuttles/nova/goldeneye_cruiser.dmm
  code/modules/antagonists/pirate/pirate_shuttle_equipment.dm
  monkestation/code/game/machinery/rechargestation.dm
  monkestation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  tgstation.dme
Labels: Mapping, Fix, Balance, admin approved

#5391 blacklist die of fate from being tossed out while searching a trash pile
  monkestation/code/game/objects/structures/trash_pile.dm
Labels: QoL, admin approved

#5397 fix broken replay thingy
  monkestation/code/modules/replays/subsystem/replay.dm
Labels: Major, Fix

#5395 [PORT] Fixes species/tongue-based speech modification altering sign language
  code/modules/surgery/organs/internal/tongue/_tongue.dm
Labels: Fix

#5380 [PORTS] A bunch of sanitization fixes
  code/controllers/subsystem/pai.dm
  code/game/machinery/computer/records/medical.dm
  code/game/machinery/computer/records/records.dm
  code/game/machinery/computer/records/security.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/wiremod/core/integrated_circuit.dm
  monkestation/code/modules/mech_comp/objects/messages/_messaging.dm
  monkestation/code/modules/mech_comp/objects/messages/association.dm
  monkestation/code/modules/mech_comp/objects/messages/dispatch.dm
  monkestation/code/modules/mech_comp/objects/messages/toggle.dm
  monkestation/code/modules/virology/machines/disease_records.dm
Labels: Major, Fix

#5389 Shields now properly block thrown plants
  code/modules/hydroponics/plant_genes.dm
Labels: Major, Fix, admin approved

#5382 nerfs Moffer (hides centcom fax machines so they can't be used to break in)
  _maps/map_files/generic/CentCom.dmm
Labels: Fix

#5286 you can now construct reinforced plastitanium walls
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  _maps/RandomRuins/SpaceRuins/old_infiltrator.dmm
  _maps/shuttles/ert_deathsquad.dmm
  _maps/shuttles/infiltrator_advanced.dmm
  _maps/shuttles/infiltrator_basic.dmm
  _maps/virtual_domains/syndicate_assault.dmm
  code/game/objects/structures/girders.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/gorlex_cruiser.dmm
Labels: QoL

#5410 [PORT] Fix player panel encoding
  code/modules/admin/player_panel.dm
Labels: Minor, Fix

#5400 [PORT] Updates TGUI to v4.3.2
  tgui/.eslintrc.yml
  tgui/.yarnrc.yml
  tgui/babel.config.js
  tgui/package.json
  tgui/packages/tgui-bench/index.js
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/interfaces/BountyBoard.jsx
  tgui/packages/tgui/interfaces/HotkeysHelp.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/QuantumConsole.tsx
  tgui/packages/tgui/interfaces/StackCrafting.tsx
  tgui/packages/tgui/interfaces/common/GasmixParser.tsx
  tgui/packages/tgui/package.json
  tgui/yarn.lock
Labels: Minor

#5138 [PORT] Two new brain traumas; plus, a rewritten Kleptomania
  code/datums/ai/_ai_controller.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/severe.dm
  code/datums/brain_damage/special.dm
  code/modules/religion/honorbound/honorbound_trauma.dm
  monkestation/code/datums/brain_damage/severe.dm
  monkestation/code/datums/quirks/negative_quirks/kleptomaniac.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_traumas.dm
  monkestation/code/modules/datums/brain_damage/mild.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/simian.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/teratoma.dm
  tgstation.dme
Labels: Feature, Monkeys, admin approved

#5290 Adds the Super Syndie-Kitty Ears for 16 TC (+ minor super kitty ear changes)
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/~monkestation/lighting.dm
  code/_onclick/hud/fullscreen.dm
  code/modules/spells/spell_types/shapeshift/_shape_status.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  monkestation/code/modules/mapfluff/ruins/spaceruin_code/mrow_thats_right.dm
  monkestation/code/modules/mob/living/simple_animal/friendly/cat.dm
  monkestation/code/modules/mob/living/simple_animal/hostile/syndicat.dm
  monkestation/code/modules/spells/spell_types/shapeshift/_shapeshift.dm
  monkestation/code/modules/uplink/uplink_items/misc.dm
  tgstation.dme
Labels: Feature, Balance, QoL, admin approved, Code Improvement

#5429 Fixes Bobr reload bug, tweaks the Tutel
  monkestation/code/game/objects/items/tactical_shields.dm
  monkestation/code/modules/blueshift/items/ammo.dm
Labels: Minor, Tweak, Fix

#5374 Mods adjustment
  _maps/map_files/Blueshift/Blueshift.dmm
  monkestation/code/game/area/areas/station.dm
  monkestation/code/game/objects/items/storage/garment.dm
  monkestation/code/modules/assault_ops/code/covert_modsuit.dm
  monkestation/code/modules/blueshield/areas.dm
  monkestation/code/modules/blueshield/closet.dm
  monkestation/code/modules/blueshield/landmarks.dm
  monkestation/code/modules/blueshield/modsuit/suit.dm
  monkestation/code/modules/blueshield/modsuit/theme.dm
  monkestation/code/modules/mod/mod_theme.dm
  monkestation/code/modules/mod/mod_types.dm
  tgstation.dme
Labels: enhancement, QoL, admin approved, Code Improvement

#5390 Fix smite ignoring antimagic, also tell the caster what the smite was
  monkestation/code/modules/spells/spell_types/pointed/smite.dm
Labels: Fix, QoL

#5409 Feburary Fixes part 2
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/wiremod/components/action/radio.dm
  monkestation/code/modules/mech_comp/objects/_object.dm
  monkestation/code/modules/mech_comp/objects/messages/money.dm
Labels: Minor, Fix

#5378 Dying oozelings now properly unequip items before moving them to their core
  monkestation/code/modules/surgery/organs/internal/brain.dm
Labels: Fix

#5420 Fixes Tram shipbreaking hut being spaced roundstart
  _maps/map_files/tramstation/tramstation.dmm
Labels: Fix

#5419 Fixes Fluffy Tongue applying to sign language
  monkestation/code/datums/quirks/positive_quirks/fluffy_tongue.dm
Labels: Fix

#5379 Coloring greyscale loadout items now updates the character preview
  monkestation/code/modules/loadouts/loadout_middleware.dm
Labels: Fix, QoL

#5371 blueshift stuffs
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Mapping, Fix

#5328 Ribboned Gown - Code request
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/greyscale/json_configs/ribbondress.json
  code/datums/greyscale/json_configs/ribbondress_worn.json
  code/modules/clothing/under/skirt_dress.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/under/dress.dmi
  icons/obj/clothing/under/dress.dmi
  monkestation/code/modules/loadouts/items/under/under.dm
  monkestation/code/modules/store/store_items/under.dm
Labels: enhancement, peak

#5424 Ports some valentine's day stuff from tg
  _maps/RandomRuins/IceRuins/icemoon_underground_mailroom.dmm
  _maps/map_files/Theseus/Theseus.dmm
  code/__HELPERS/pronouns.dm
  code/datums/status_effects/neutral.dm
  code/game/alternate_appearance.dm
  code/modules/antagonists/valentines/heartbreaker.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/cargo/goodies.dm
  code/modules/events/holiday/vday.dm
  code/modules/wiremod/components/bci/hud/bar_overlay.dm
  code/modules/wiremod/components/bci/hud/counter_overlay.dm
  code/modules/wiremod/components/bci/hud/object_overlay.dm
Labels: Fix, Feature, QoL, admin approved

#5212 Quarad rebalance, minor nukie + import gun changes
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/projectile/bullets/lmg.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/projectiles/projectile/reusable/foam_dart.dm
  monkestation/code/__DEFINES/projectile.dm
  monkestation/code/modules/blueshift/armaments/sol.dm
  monkestation/code/modules/blueshift/items/ammo.dm
  monkestation/code/modules/blueshift/items/company_guns.dm
  monkestation/code/modules/blueshift/items/gunset.dm
  monkestation/code/modules/blueshift/spawners/armory.dm
  monkestation/code/modules/projectiles/ammunition/ballistic/machine_guns.dm
  monkestation/code/modules/projectiles/guns/ballistic/machine_guns.dm
  monkestation/code/modules/projectiles/projectile/bullets/machine_guns.dm
  monkestation/code/modules/uplink/uplink_items/nukeops.dm
  monkestation/icons/mob/clothing/back.dmi
  monkestation/icons/mob/inhands/gunsx48_worn.dmi
  monkestation/icons/mob/inhands/weapons/guns_lefthandx48.dmi
  monkestation/icons/mob/inhands/weapons/guns_righthandx48.dmi
  monkestation/icons/obj/weapons/guns/ammo.dmi
  monkestation/icons/obj/weapons/guns/guns48x.dmi
  tgstation.dme
Labels: Tweak, Balance, admin approved

#5457 [PORT] Fixes smokey remains flaky
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/fluids.dm
Labels: Fix

#5387 Renames plasmaflood license to murderbone
  monkestation/code/game/objects/items/plasma_license.dm
  monkestation/code/modules/uplink/uplink_items/misc.dm
Labels: Minor, Tweak, admin approved

#5168 Allow mentors/admins/donators to bypass the popcap
  code/__DEFINES/~monkestation/_patreon.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/job.dm
  code/modules/admin/IsBanned.dm
  code/modules/mob/dead/new_player/latejoin_menu.dm
  monkestation/code/datums/patreon_data.dm
  monkestation/code/modules/mentor/client.dm
Labels: Tools, Fix

#5307 Add the fancy block formatting to the Show Server Revision verb
  code/datums/helper_datums/getrev.dm
Labels: QoL

#3233 Adds pathology goggles and their variants
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/templates/lazy_templates/nukie_base.dmm
  code/__DEFINES/traits/monkestation/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/datums/actions/items/toggles.dm
  monkestation/code/datums/components/crafting/tailoring.dm
  monkestation/code/datums/components/pathology_glasses.dm
  monkestation/code/datums/elements/virus_viewer.dm
  monkestation/code/modules/client/client_colour.dm
  monkestation/code/modules/clothing/glasses/glasses.dm
  monkestation/code/modules/jobs/job_types/virologist.dm
  monkestation/code/modules/mob/living/init_signals.dm
  monkestation/code/modules/research/designs/medical_designs.dm
  monkestation/code/modules/virology/disease/base_disease_folder/_base.dm
  monkestation/code/modules/virology/disease/base_disease_folder/admin.dm
  monkestation/code/modules/virology/disease/base_disease_folder/general_procs.dm
  monkestation/code/modules/virology/effects/cleanables.dm
  monkestation/code/modules/virology/effects/pathogen_cloud.dm
  monkestation/code/modules/virology/items/_base_item_additions.dm
  monkestation/code/modules/virology/items/pathology_glasses.dm
  monkestation/code/modules/virology/items/science_goggles.dm
  monkestation/icons/obj/clothing/eyes.dmi
  monkestation/icons/obj/clothing/glasses.dmi
  tgstation.dme
Labels: Tweak, Balance

#5377 Charlie Station now has a unique ID console program and ID painter.
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/__DEFINES/access.dm
  code/controllers/subsystem/id_access.dm
  code/datums/id_trim/ruins.dm
  code/game/objects/items/cards/card_ids.dm
  code/game/objects/items/cards_ids.dm
  code/modules/research/designs/autolathe/engineering_designs.dm
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/datums/id_trim/ruins.dm
  monkestation/code/modules/blueshift/structures/fluff.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldchef.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldcmo.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldeng.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldexplorer.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldsci.dm
  monkestation/code/modules/mob_spawn/ghost_roles/space_roles/oldsec.dm
  monkestation/code/modules/oldstation_idconsole/oldstation_airlock_board.dm
  monkestation/code/modules/oldstation_idconsole/oldstation_idconsole.dm
  tgstation.dme
Labels: QoL, admin approved

#4966 Big Lizard Update Part 1: The Addition-ization of More (Reptilian) Stuff
  code/modules/clothing/clothing.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_ashwalker.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_silverscale.png
  icons/mob/clothing/under/masking_helpers.dmi
  icons/mob/species/lizard/bodyparts.dmi
  icons/mob/species/lizard/lizard_misc.dmi
  icons/mob/species/lizard/lizard_spines.dmi
  icons/mob/species/lizard/lizard_tails.dmi
  monkestation/code/modules/mob/dead/new_player/sprite_accessories/multi_part.dm
  monkestation/icons/mob/species/lizard/multipart.dmi
Labels: spriting, Expansion

#5445 [PORT] Boomboots Clown Exclusive Traitor Item
  code/modules/uplink/uplink_items/job.dm
  monkestation/code/modules/veth_misc_items/boomboots/boomboot.dm
  tgstation.dme
Labels: Feature

#5263 Slasher updates
  code/game/machinery/doors/airlock.dm
  code/modules/unit_tests/screenshots/screenshot_antag_icons_slasher.png
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/envelope_darkness.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/recall_machette.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/slasher_regenerate.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/soul_steal.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/stalk_target.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/terror_screech.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/ghost_role.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_outfit/slasher_clothing.dm
Labels: do not merge, testmerge only, Fix

#5435 Lung Popping Rework
  code/modules/surgery/organs/lungs.dm
Labels: what, Balance, Refactor/Rework, admin approved

#5275 Blueshield shield blades buff
  monkestation/code/modules/cybernetics/implant_items/weapons/mantis_blade.dm
Labels: Balance

#5366 Removes pain on being damaged
  monkestation/code/modules/can_spessmen_feel_pain/pain/_base.dm
Labels: Removal

#5224 Sneaky cybernetics
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/surgery/organs/autosurgeon.dm
  monkestation/code/modules/assault_ops/code/armaments/implants.dm
  monkestation/code/modules/blueshift/items/implants.dm
  monkestation/code/modules/blueshift/opfor/equipment/implants.dm
  monkestation/code/modules/cybernetics/augments/_base_changes.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/jobs.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/weapons.dm
  monkestation/code/modules/cybernetics/augments/chest_augments.dm
  monkestation/code/modules/cybernetics/augments/eye_implants.dm
  monkestation/code/modules/cybernetics/augments/internal_implants.dm
  monkestation/code/modules/cybernetics/augments/uplink/uplink.dm
  monkestation/code/modules/cybernetics/designs/item_sets.dm
  monkestation/code/modules/cybernetics/premade_storages/antags.dm
  monkestation/code/modules/cybernetics/tech_nodes.dm
  monkestation/code/modules/research/designs/mechfabricator_designs.dm
  monkestation/code/modules/surgery/organs/augments.dm
  monkestation/code/modules/surgery/organs/internal/eyes.dm
  monkestation/code/modules/surgery/organs/internal/tongue.dm
Labels: enhancement, Balance

#5478 More Slasher fixes
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
Labels: Fix

#5462 Proper bomb check, genturf description change
  code/datums/mapgen/JungleGenerator.dm
  monkestation/code/game/machinery/bomb_actualizer.dm
Labels: Fix, QoL

#5463 Ribboned Gown Bugfix + Sprite tweak
  icons/mob/clothing/under/dress.dmi
  monkestation/code/modules/loadouts/items/under/under.dm
Labels: Fix

#5459 Mentor cloak fixes
  monkestation/code/modules/clothing/neck/cloaks.dm
  monkestation/code/modules/loadouts/items/admin.dm
Labels: Fix, QoL

#5476 Remove the call to `install_node.sh` from the Windows CI build script
  tools/ci/build.ps1
Labels: Tools

#5475 [PORT] Drops ie8 support from TGUI
  tgui/package.json
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-polyfill/00-html5shiv.js
  tgui/packages/tgui-polyfill/01-ie8.js
  tgui/packages/tgui-polyfill/02-dom4.js
  tgui/packages/tgui-polyfill/03-css-om.js
  tgui/packages/tgui-polyfill/1-misc.js
  tgui/packages/tgui-polyfill/10-misc.js
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/package.json
  tgui/public/tgui-polyfill.min.js
  tgui/tsconfig.json
  tgui/webpack.config.js
Labels: Removal

#5465 Ghost control poll timer increase
  code/modules/mob/mob_helpers.dm
Labels: enhancement, QoL

#5461 [PORT] Improves text readability in some parts of the PDA retro theme
  tgui/packages/tgui/styles/themes/ntOS95.scss
Labels: Minor

#5471 You can now hide items in potted plants!
  monkestation/code/modules/blueshift/structures/kirbyplants.dm
  monkestation/icons/obj/plants.dmi
Labels: Feature

#5491 The even more most fixes
  _maps/shuttles/nova/goldeneye_cruiser.dmm
  code/modules/antagonists/pirate/pirate_outfits.dm
  interface/skin.dmf
  monkestation/code/modules/assault_ops/code/cyborg.dm
  monkestation/code/modules/blueshift/machines/vending_additions.dm
  monkestation/code/modules/food_and_drinks/machinery/smartfridge.dm
  monkestation/code/modules/jobs/job_types/blueshield.dm
  monkestation/code/modules/jobs/job_types/roboticist.dm
  tgstation.dme
Labels: Minor, Fix

#5453 Valentine's day rework (part 2 I guess?)
  code/__DEFINES/span.dm
  code/modules/events/holiday/vday.dm
  monkestation/code/modules/antagonists/valentines/valentine.dm
  monkestation/code/modules/events/holiday/vday.dm
  tgstation.dme
Labels: Feature, Refactor/Rework

#5485 Add a SS13.check_tick lua function
  lua/SS13_base.lua
Labels: Tools

#5483 [PORT] Changes entertainment radio to be darker
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-say/styles/colors.scss
Labels: Minor, Tweak

#5454 finally make heart worms not a royal pain in the ass to deal with
  code/modules/mob/living/carbon/life.dm
  monkestation/code/modules/virology/disease/premades/heart_attack.dm
  monkestation/code/modules/virology/disease/symtoms/restricted/stage4.dm
Labels: Fix

#5487 Detective's office/Courtroom maints on Blueshift should now be properly radiation shielded
  _maps/map_files/Blueshift/Blueshift.dmm
  monkestation/code/modules/blueshift/areas/station.dm
  monkestation/code/modules/blueshift/icons/areas/areas_station.dmi
Labels: Mapping, Fix

#5432 Vim Internal Life Support
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/cars/vim.dm
Labels: Minor, QoL, admin approved

#5124 If it meows, it hates getting sprayed with water
  code/datums/mood_events/generic_negative_events.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, QoL, admin approved

#5488 [Port from TG] Computers act like barricades
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/orders/order_computer/mining_order.dm
  code/game/machinery/computer/records/medical.dm
  code/game/machinery/computer/records/security.dm
  code/game/machinery/computer/telescreen.dm
  code/game/machinery/constructable_frame.dm
Labels: Fix, Balance, awaiting admin review

#5460 Return of Nanofrost + Pre-equipped Station Modsuit Changes + Firefighting Foam Adjustments + Space Gear Adjustment + Utility Clothing Audit (Electric Boogaloo)
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits/monkestation/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/effect_system/fluid_spread/effects_foam.dm
  code/game/objects/effects/effect_system/fluid_spread/effects_smoke.dm
  code/game/objects/items/grenades/smokebomb.dm
  code/game/objects/items/storage/boxes/engineering_boxes.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/objects/items/tanks/watertank.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/clothing/head/costume.dm
  code/modules/clothing/shoes/galoshes.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/costume.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mod/mod_types.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/uplink/uplink_items/suits.dm
  code/modules/vending/engivend.dm
  icons/mob/clothing/head/spacehelm.dmi
  icons/mob/clothing/suits/spacesuit.dmi
  monkestation/code/modules/ERT/ERT_outfits.dm
  monkestation/code/modules/ERT/equipment/ERT_spacesuits.dm
  monkestation/code/modules/cargo/packs/hardsuit_crates.dm
  monkestation/code/modules/clothing/spacesuits/hardsuits/_hardsuit.dm
  monkestation/code/modules/clothing/spacesuits/hardsuits/heavy.dm
  monkestation/code/modules/clothing/spacesuits/hardsuits/misc.dm
  monkestation/code/modules/loadouts/items/heads.dm
  monkestation/code/modules/loadouts/items/suits.dm
  monkestation/code/modules/slimecore/components/latch_feeding.dm
  monkestation/code/modules/slimecore/mobs/_base_slime.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/behaviours/feed.dm
  monkestation/code/modules/uplink/uplink_items/misc.dm
  monkestation/icons/effects/stabilized_plasma.dmi
Labels: enhancement, spriting, Mapping, do not merge, testmerge only, Fix, Feature, Balance, QoL, awaiting admin review

#4767 Heliostation from fulp
  _maps/_basemap.dm
  _maps/heliostation.json
  _maps/map_files/Heliostation/Heliostation.dmm
  config/maps.txt
  monkestation/code/modules/cargoborg/icons/cargo_teleporter.dmi
Labels: Mapping, do not merge, Feature

#5511 Enable hard deletes when reftracking
  code/controllers/subsystem/garbage.dm
  code/modules/admin/sql_ban_system.dm
Labels: Tools

#5474 You can make hollow windows using RCDs again.
  code/game/objects/structures/grille.dm
Labels: enhancement, Fix

#3011 Brings back NIF hiveminds, this time they are fully functional and not broken
  code/datums/components/mind_linker.dm
  monkestation/code/modules/blueshift/items/nif.dm
  monkestation/code/modules/blueshift/nifsoft/_base.dm
  monkestation/code/modules/blueshift/nifsoft/types.dm
Labels: Fix

#5422 Remove a period from the regex used to determine valid youtube IDs
  monkestation/code/modules/cassettes/machines/stationary_mixer.dm
Labels: Minor

#5484 `/mob/living/infect_disease()` now compares the uniqueID and subID directly
  monkestation/code/modules/virology/living/spread_disease.dm
Labels: Performance / Optimization, Code Improvement

#5434 Add character savedata migration to sanitize previous alt job titles
  code/modules/client/preferences_savefile.dm
  monkestation/code/modules/client/preference_savefile.dm
  monkestation/code/modules/client/preferences/migrations/sanitize_alt_job_titles.dm
  tgstation.dme
Labels: Fix

#5521 Flusher component fixes + make ticker component obtainable
  monkestation/code/modules/cargo/packs/vending_restock.dm
  monkestation/code/modules/mech_comp/objects/flush.dm
  monkestation/code/modules/mech_comp/objects/messages/ticker.dm
  monkestation/code/modules/mech_comp/vending_machine.dm
  tgstation.dme
Labels: Fix, Feature, Refactor/Rework, admin approved

#5506 Clockwork slabs no longer shock on pickup (+ minor damage reduction)
  monkestation/code/modules/antagonists/clock_cult/items/clockwork_slab.dm
  monkestation/code/modules/antagonists/clock_cult/pickup_element.dm
Labels: Balance, admin approved

#5455 Bloodsucker bugfixes and qol tweaks
  code/__DEFINES/bloodsuckers.dm
  code/__DEFINES/~monkestation/do_afters.dm
  code/__DEFINES/~monkestation/level_traits.dm
  code/__HELPERS/~monkestation-helpers/areas.dm
  code/__HELPERS/~monkestation-helpers/spatial_info.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_sol.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_traumas.dm
  monkestation/code/modules/bloodsuckers/powers/cloak.dm
  monkestation/code/modules/bloodsuckers/powers/feed.dm
  monkestation/code/modules/bloodsuckers/powers/go_home.dm
  monkestation/code/modules/bloodsuckers/powers/masquerade.dm
  monkestation/code/modules/bloodsuckers/powers/targeted/lunge.dm
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_coffin.dm
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_crypt.dm
  monkestation/icons/bloodsuckers/vamp_obj.dmi
  tgstation.dme
Labels: Fix, Balance, QoL, admin approved

#5526 Fix the "Open Map" escape menu option
  code/modules/escape_menu/home_page.dm
Labels: Fix

#5540 fix admin logging with antag tokens
  code/modules/admin/topic.dm
Labels: Fix, admin approved

#5567 [PORT] Uses icon_exists in getflaticon instead of iconstates
  code/__HELPERS/icons.dm
  code/modules/asset_cache/assets/research_designs.dm
  monkestation/code/modules/mob/living/carbon/human/custom_bodytype.dm
Labels: Performance / Optimization

#5563 ERT Code Yellow
  _maps/shuttles/ert_dropship-engineering.dmm
  code/datums/ert.dm
  code/modules/vehicles/mecha/working/ripley.dm
  monkestation/code/modules/ERT/ERT_shuttle.dm
  monkestation/code/modules/vehicles/mecha/working/ripley.dm
  tgstation.dme
Labels: Expansion

#5545 Storyteller + events touchup
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/antagonists/pirate/pirate_event.dm
  code/modules/events/creep_awakening.dm
  code/modules/events/ghost_role/alien_infestation.dm
  code/modules/events/ghost_role/operative.dm
  monkestation/code/modules/antagonists/borers/code/antagonist_stuff/midround_event.dm
  monkestation/code/modules/antagonists/evil_clone/evil_event.dm
  monkestation/code/modules/antagonists/florida_man/florida_events.dm
  monkestation/code/modules/antagonists/monster_hunters/events/wonderland_apocalypse.dm
  monkestation/code/modules/assault_ops/code/midround_event.dm
  monkestation/code/modules/assault_ops/code/roundstart_event.dm
  monkestation/code/modules/assault_ops/code/sunbeam.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/ghost_role.dm
  monkestation/code/modules/events/anomaly/anomaly_radiation.dm
  monkestation/code/modules/storytellers/converted_events/event_overrides.dm
  monkestation/code/modules/storytellers/converted_events/solo/blob_infection.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodsuckers.dm
  monkestation/code/modules/storytellers/converted_events/solo/brother.dm
  monkestation/code/modules/storytellers/converted_events/solo/changeling.dm
  monkestation/code/modules/storytellers/converted_events/solo/clockwork_cult.dm
  monkestation/code/modules/storytellers/converted_events/solo/clown_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/ghosts/nuclear_operative_ghost.dm
  monkestation/code/modules/storytellers/converted_events/solo/ghosts/paradox_clone.dm
  monkestation/code/modules/storytellers/converted_events/solo/ghosts/wizard.dm
  monkestation/code/modules/storytellers/converted_events/solo/heretic.dm
  monkestation/code/modules/storytellers/converted_events/solo/malf.dm
  monkestation/code/modules/storytellers/converted_events/solo/nuclear_operative.dm
  monkestation/code/modules/storytellers/converted_events/solo/obsessed.dm
  monkestation/code/modules/storytellers/converted_events/solo/revolutionary.dm
  monkestation/code/modules/storytellers/converted_events/solo/traitor.dm
  monkestation/code/modules/storytellers/converted_events/solo/wizard.dm
  monkestation/code/modules/storytellers/storytellers/brute.dm
  monkestation/code/modules/storytellers/storytellers/guide.dm
  monkestation/code/modules/storytellers/storytellers/hermit.dm
  monkestation/code/modules/storytellers/storytellers/sleeper.dm
  monkestation/code/modules/virology/disease/plague_rat/event.dm
  tgstation.dme
Labels: Expansion, Balance, fuck it we ball, should testmerge

#5496 Syndicate Depot Revision 3: Black-Box Data Storage
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  code/__DEFINES/is_helpers.dm
  code/modules/cargo/exports/spaceloot.dm
  monkestation/code/modules/cargoborg/code/cargo_teleporter.dm
  monkestation/code/modules/syndicate_ghostroles/depot.dm
  tgstation.dme
Labels: enhancement, Expansion, admin approved, should testmerge

#5490 More spooky fixes
  code/modules/events/holiday/vday.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/recall_machette.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/stalk_target.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
Labels: do not merge, testmerge only, Fix

#5543 Add unique clockwork slurring, and the Rat'vander Cocktail
  monkestation/code/datums/status_effects/debuffs/speech_debuffs.dm
  monkestation/code/modules/antagonists/clock_cult/scriptures/servitude/kindle.dm
  monkestation/code/modules/antagonists/clock_cult/structures/sigil/sigil_submission.dm
  monkestation/code/modules/food_and_drinks/recipes/drinks/drinks_alcoholic.dm
  monkestation/code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
  monkestation/code/modules/reagents/chemistry/reagents/drinks/glass_styles/mixed_alcohol.dm
  monkestation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  monkestation/icons/obj/drinks/mixed_drinks.dmi
  strings/slurring_clock_text.json
  tgstation.dme
Labels: Feature, admin approved

#5549 Adds spaceruins by Hal-9000
  _maps/RandomRuins/SpaceRuins/InfestedFlotilla.dmm
  _maps/RandomRuins/SpaceRuins/interstellar_modular_hulls.dmm
  code/game/area/areas/ruins/space.dm
Labels: Balance, admin approved

#5505 small changes to abandoned syndicate infiltrator
  _maps/RandomRuins/SpaceRuins/old_infiltrator.dmm
  monkestation/code/game/area/areas/ruins/space.dm
  tgstation.dme
Labels: Expansion, Fix, admin approved

#5399 [PORT] Basic mob Pirates, which now plunder your money with every hit
  _maps/RandomRuins/IceRuins/icemoon_surface_mining_site.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/derelict_construction.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/virtual_domains/pirates.dmm
  code/__DEFINES/mobs.dm
  code/datums/components/plundering_attacks.dm
  code/modules/mob/living/basic/basic.dm
  code/modules/mob/living/basic/trooper/nanotrasen.dm
  code/modules/mob/living/basic/trooper/pirate.dm
  code/modules/mob/living/basic/trooper/russian.dm
  code/modules/mob/living/basic/trooper/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/unit_tests/simple_animal_freeze.dm
  tgstation.dme
  tools/UpdatePaths/Scripts/79284_simple_to_basic_pirates.txt
Labels: Minor, Refactor/Rework, admin approved

#5560 Florans will no longer place their hats atop an invisible gigapompadour
  code/modules/clothing/head/_head.dm
Labels: spriting, Fix, admin approved

#5384 Refactors silicon emotes slightly - port of tgstation 84912
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/emotes.dm
  code/modules/mob/living/basic/bots/_bots.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/surgery/organs/internal/tongue/_tongue.dm
  monkestation/code/modules/emotes/code/emote.dm
  monkestation/code/modules/surgery/organs/internal/tongue.dm
Labels: Expansion, QoL, admin approved

#5529 Some helio fixes
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix, admin approved

#5535 Changes coritical borer threats to medical and medical adjacent staff.
  monkestation/code/modules/antagonists/borers/code/antagonist_stuff/midround_event.dm
  monkestation/code/modules/cargo/crates/medical.dm
  monkestation/code/modules/cargo/crates/security.dm
Labels: Tweak, Balance, admin approved

#5562 Weapons implant for assault operatives
  code/modules/projectiles/guns/energy/stun.dm
  monkestation/code/game/objects/items/implants/implant_misc.dm
  monkestation/code/modules/assault_ops/code/armaments/_base.dm
  monkestation/code/modules/assault_ops/code/outfits.dm
  monkestation/code/modules/blueshift/items/company_guns.dm
  monkestation/code/modules/blueshift/opfor/equipment/guns.dm
  tgstation.dme
Labels: Tweak, admin approved

#5533 Shipbreaker map template organization
  _maps/~monkestation/shipbreaking/black_peregrine.dmm
  _maps/~monkestation/shipbreaking/gasstation.dmm
  _maps/~monkestation/shipbreaking/goonshuttlesmall.dmm
  _maps/~monkestation/shipbreaking/gorlex_cruiser.dmm
  _maps/~monkestation/shipbreaking/mcsail.dmm
  _maps/~monkestation/shipbreaking/mcsteal_sloop.dmm
  _maps/~monkestation/shipbreaking/mess.dmm
  _maps/~monkestation/shipbreaking/mule.dmm
  _maps/~monkestation/shipbreaking/old_altar.dmm
  _maps/~monkestation/shipbreaking/old_banana.dmm
  _maps/~monkestation/shipbreaking/old_bathroom.dmm
  _maps/~monkestation/shipbreaking/old_chapel.dmm
  _maps/~monkestation/shipbreaking/old_diner.dmm
  _maps/~monkestation/shipbreaking/old_escape_pod.dmm
  _maps/~monkestation/shipbreaking/old_repair.dmm
  _maps/~monkestation/shipbreaking/robotics.dmm
  _maps/~monkestation/shipbreaking/squid.dmm
  _maps/~monkestation/shipbreaking/torus.dmm
  _maps/~monkestation/shipbreaking/true_church.dmm
  _maps/~monkestation/shipbreaking/wanglius.dmm
  _maps/~monkestation/shipbreaking/whale.dmm
  monkestation/code/modules/a_ship_in_need_of_breaking/code/controllers/subsystem/mapping.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/machines/console.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/_base_ship.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/black_peregrine.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/gasstation.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/goonshuttlesmall.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/gorlex_cruiser.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/mcsail.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/mcsteal_sloop.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/mess.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/mule.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_altar.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_banana.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_bathroom.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_chapel.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_diner.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_escape_pod.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/old_repair.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/robotics.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/squid.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/torus.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/true_church.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/ships/wanglius.dm
  monkestation/code/modules/antagonists/clock_cult/structures/brass_window.dm
  tgstation.dme
Labels: Minor, Mapping, Fix, Refactor/Rework, admin approved, Code Improvement

#5568 PENLITE buff and Immunity scanners storage
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/medkit.dm
  monkestation/code/game/objects/items/holosign_creator.dm
Labels: Balance, QoL

#5578 Fix ticker component
  monkestation/code/modules/mech_comp/objects/messages/ticker.dm
Labels: Fix

#5542 Makes zombies actually be able to roll
  monkestation/code/modules/antagonists/zombies/zombie_meteor_storm.dm
  monkestation/code/modules/antagonists/zombies/zombie_types/base_zombie.dm
Labels: Fix, Feature, admin approved, Code Improvement

#5512 Lone Op weight changes
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/events/ghost_role/operative.dm
Labels: Balance, admin approved, should testmerge

#4608 Makes Borers Unsquishable but have a bigger sprite
  monkestation/code/modules/antagonists/borers/code/mobs/cortical_borer.dm
Labels: Balance, admin approved, should testmerge

#5573 Window sill fixes + qol
  code/game/objects/structures/window.dm
  monkestation/code/modules/aesthetics/objects/window_sill.dm
  monkestation/code/modules/aesthetics/objects/windows.dm
Labels: Minor, Fix, Feature, QoL
