Repository Monkestation/Monkestation2.0, pull requests merged in 2025-08, with the labels that each got.

#7367 Spiders now see their current directive in the status panel (+ spider type check fix)
  code/__DEFINES/is_helpers.dm
  code/game/objects/effects/spiderwebs.dm
  code/modules/mob/living/basic/space_fauna/spider/spider.dm
  code/modules/mob/living/basic/space_fauna/spider/spider_abilities/hivemind.dm
Labels: Code: Fix, QoL

#7363 [Port] Bridge Assistant Axe Delusions
  code/datums/brain_damage/special.dm
  code/datums/mood_events/axe_events.dm
  code/game/objects/items/fireaxe.dm
  code/modules/jobs/job_types/bridgeassistant.dm
  tgstation.dme
Labels: Feature: Feature, Balance, Approval: admin approved

#7397 Shuttle alignment
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_doubleleaded.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/shuttles/emergency_medisim.dmm
Labels: Change: Mapping

#7408 Update meta_central.dmm
  _maps/virtual_domains/meta_central.dmm
Labels: Code: Fix

#7390 require 30+ crew for blood brothers to get the tank
  code/modules/antagonists/brother/actions/gear.dm
  code/modules/antagonists/brother/gear/_gear.dm
  code/modules/antagonists/brother/gear/misc.dm
Labels: Balance, Approval: admin approved

#7321 Industrial precursor chemicals intoxicate IPCs
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
Labels: Feature: Feature, Funny

#7413 subsystem/MC improvements
  code/controllers/configuration/entries/general.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/profiler.dm
  code/modules/unit_tests/subsystem_init.dm
  config/config.txt
  tgui/packages/tgui/interfaces/ControllerOverview/OverviewSection.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemDialog.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemRow.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemViews.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/contants.ts
  tgui/packages/tgui/interfaces/ControllerOverview/filters.ts
  tgui/packages/tgui/interfaces/ControllerOverview/index.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/types.ts
Labels: Tools, Code: Performance / Optimization, Code: Improvement, Code: TGUI

#7412 Donoticket 865, 888, 904, 920
  monkestation/code/modules/donator/code/datum/loadout.dm
  monkestation/code/modules/donator/code/item/choice_beacon.dm
  monkestation/code/modules/donator/code/item/clothing.dm
  monkestation/code/modules/donator/code/item/plush.dm
  monkestation/code/modules/donator/code/mob/pet_huds.dm
  monkestation/code/modules/donator/code/mob/pets.dm
  monkestation/code/modules/donator/icons/mob/clothing.dmi
  monkestation/code/modules/donator/icons/mob/clothing_32x48.dmi
  monkestation/code/modules/donator/icons/mob/pets.dmi
  monkestation/code/modules/donator/icons/obj/clothing.dmi
  monkestation/code/modules/donator/icons/obj/plushes.dmi
  tgstation.dme
Labels: Process: do not merge

#7415 Adding the Dealmaker to the loadout
  code/modules/clothing/glasses/_glasses.dm
  monkestation/code/modules/loadouts/items/glasses.dm
  monkestation/code/modules/store/store_items/glasses.dm
Labels: Feature: Feature

#7430 fix being able to move sometimes during timestop
  code/datums/proximity_monitor/fields/timestop.dm
  code/modules/unit_tests/spell_timestop.dm
Labels: Code: Fix

#7435 You can no longer enter torpor in a frenzy
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_sol.dm
Labels: Code: Fix

#7389 Adds MonkeTech AutoTranslators to the Sci and Medical Techfabs
  code/modules/research/designs/autolathe/medsci_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature: Feature, Approval: awaiting admin review

#7237 [BOUNTY] Adds Jaundice (as a monkecoin purchase)
  code/modules/surgery/bodyparts/helpers.dm
  monkestation/code/game/objects/items/effects/jaundice.dm
  monkestation/code/modules/store/pre_round/roundstart_items/effects.dm
  monkestation/icons/obj/effect_granters.dmi
  tgstation.dme
Labels: what, Feature: Feature

#7441 Changes assault operative's sunbeam alert level
  monkestation/code/modules/assault_ops/code/sunbeam.dm
Labels: Balance, Approval: admin approved

#7446 The Kings chariot cannot be stopped.
  code/datums/components/riding/riding_vehicle.dm
  code/modules/vehicles/kingschariot.dm
  icons/obj/car.dmi
  tgstation.dme
Labels: Feature: Feature, Funny

#7434 Bumps comically larges spoons wound bonus down
  monkestation/code/game/objects/items/comically_large_spoon.dm
Labels: Balance, Approval: admin approved

#7414 More BM Guns and Goodie Items
  code/game/objects/items/storage/belt.dm
  code/modules/cargo/goodies.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/security.dm
  monkestation/code/modules/blueshift/items/company_guns.dm
  monkestation/code/modules/modular_guns/blackmarket/auction_items/gun_parts.dm
  monkestation/code/modules/modular_guns/blackmarket/auction_items/restock_gun_parts.dm
Labels: Feature: Feature, Balance, QoL, Approval: admin approved

#7475 Bingle pits now properly count item stacks
  monkestation/code/modules/veth_misc_items/bingle/bingle_pit.dm
Labels: Code: Fix, Approval: admin approved

#7473 minor CI improvements
  .github/workflows/compile_changelogs.yml
  .github/workflows/run_integration_tests.yml
  tools/ci/mysql_config.cnf
Labels: Tools

#7456 Slasher ability Redo
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/storage/backpack.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/creepy_breathing.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/envelope_darkness.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/recall_machette.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/soul_steal.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/stalk_target.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/summon_kitchenspike.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_outfit/slasher_clothing.dm
  monkestation/code/modules/emotes/code/emote.dm
  monkestation/sound/voice/breathein.ogg
  monkestation/sound/voice/breatheout.ogg
  tgstation.dme
Labels: Removal, Feature: Feature

#7490 Adds Robert McPlushie
  code/game/objects/items/admin_plushies.dm
  icons/obj/admin_plushies.dmi
Labels: Change: spriting, Feature: Feature

#7474 ports some planemaster code organization
  code/_onclick/hud/rendering/plane_masters/_plane_master.dm
  code/_onclick/hud/rendering/plane_masters/plane_master_subtypes.dm
  monkestation/code/modules/outdoors/code/_onclick/hud/rendering/plane_master.dm
  tgstation.dme
Labels: i hate plane cube, Code: Improvement

#7107 Armory consistency update
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  monkestation/code/modules/blueshift/items/gunset.dm
Labels: Change: Mapping, Balance, QoL

#7497 -15 mood is required to become "crazy", rather than -7 (+ some mood fixes)
  code/datums/mood.dm
Labels: Code: Fix, Balance, Approval: admin approved

#7498 Makes the Analgesia quirk -4 instead of -2
  code/datums/quirks/negative_quirks/numb.dm
Labels: Balance, Approval: admin approved

#7449 Cryoing now saves persistent scars
  code/modules/client/preferences/persistent_scars.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  monkestation/code/modules/cryopods/_cryopod.dm
Labels: QoL

#7500 searching in the loot panel now properly updates as you type
  tgui/packages/tgui/interfaces/LootPanel/index.tsx
Labels: Code: Fix, Code: TGUI

#7476 fix scissors not properly being able to give haircuits
  monkestation/code/modules/blueshift/items/barber.dm
Labels: Code: Fix

#7520 [PORT] moves the movement subsystem off background
  code/controllers/subsystem/movement/movement.dm
Labels: Code: Fix, Code: Performance / Optimization

#7429 Revert "Mothroach Improvements"
  code/datums/elements/basic_eating.dm
  code/modules/mob/living/basic/vermin/mothroach.dm
  code/modules/mob/living/basic/vermin/mothroach/mothroach_ai.dm
  icons/mob/clothing/head/pets_head.dmi
  icons/mob/inhands/animal_item_lefthand.dmi
  icons/mob/inhands/animal_item_righthand.dmi
  icons/mob/simple/animal.dmi
  tgstation.dme
Labels: Process: do not merge, Process: testmerge only, Code: Performance / Optimization

#7505 Anesthetic QOL
  _maps/RandomRuins/SpaceRuins/the_outlet.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/shuttles/pirate_irs.dmm
  code/__DEFINES/dcs/signals/signals_medical.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/muzzle.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/surgery/surgery.dm
  icons/obj/medical/surgery_table.dmi
  tools/UpdatePaths/Scripts/91112_breath_muzzle.txt
Labels: Feature: Feature, Fixed Upstream

#7443 ports some playsound optimizations
  code/__DEFINES/sound.dm
  code/__DEFINES/traits/declarations.dm
  code/__HELPERS/spatial_info.dm
  code/_globalvars/traits/_traits.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items/storage/boxes/engineering_boxes.dm
  code/game/sound.dm
  code/modules/clothing/ears/_ears.dm
Labels: Process: do not merge, Code: Performance / Optimization, Code: Improvement, Change: Sound, Process: should testmerge

#7557 End of Gatekeeping to Ranching
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LeadPoisoningStation/LeadPoisoningStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: peak, Approval: admin approved

#7517 Deleting of diseases who live
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/role_preferences.dm
  code/_globalvars/lists/mobs.dm
  code/datums/hud.dm
  code/game/data_huds.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/disease/disease_abilities.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/disease/disease_disease.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/events/ghost_role/sentient_disease.dm
  code/modules/jobs/job_types/antagonists/sentient_disease.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/unit_tests/screenshots/screenshot_antag_icons_sentientdisease.png
  config/dynamic.json
  interface/stylesheet.dm
  monkestation/code/modules/storytellers/converted_events/event_overrides.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/sentientdisease.ts
  tgui/packages/tgui/interfaces/XpMenu.jsx
Labels: Removal

#7360 Reduces lone op starting/minimum weight
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/events/ghost_role/operative.dm
Labels: Balance, Stale, Approval: awaiting admin review

#7559 [BOUNTY] Departmental Bells
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LeadPoisoningStation/LeadPoisoningStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/modules/paperwork/department_bell.dm
  code/modules/paperwork/desk_bell.dm
  icons/obj/yogstation/credits.txt
  icons/obj/yogstation/yogbell.dmi
  tgstation.dme
Labels: Feature: Feature, Approval: admin approved

#7581 Fix some missing disposals pipes in Tram engineering
  _maps/map_files/tramstation/tramstation.dmm
Labels: Change: Mapping, Code: Fix

#7470 Pro Skater Quirk
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/quirks/positive_quirks/pro_skater.dm
  code/modules/vehicles/scooter.dm
  code/modules/vehicles/vehicle_actions.dm
  tgstation.dme
Labels: Feature: Feature

#7607 [PORT] Make a global list of items that any suit storage can hold, also make suit storage able to hold any "tiny" item
  code/__DEFINES/inventory.dm
  code/modules/mob/living/carbon/human/_species.dm
Labels: Balance, QoL, Approval: admin approved

#7616 Fxies disposal bin shove message
  code/modules/recycling/disposal/bin.dm
Labels: Code: Fix

#7612 I finally figured out what was up with my strongdmm at least
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/turfs/open/floor/plating/misc_plating.dm
  monkestation/code/game/objects/items/storage/garment.dm
  monkestation/code/modules/ghost_players/arena/maps/jungle.dmm
  monkestation/code/modules/ghost_players/arena/maps/snow.dmm
  monkestation/code/modules/ghost_players/arena/maps/two_forts.dmm
  tgui/packages/tgui/interfaces/AutomatedAnnouncement.tsx
Labels: Change: Mapping, Code: TGUI

#7601 Cannibalizing/retracting limbs as an oozeling now drops any implants in that limb
  monkestation/code/modules/surgery/organs/internal/heart.dm
Labels: Code: Fix

#7605 Custom objectives now alert admins audibly. Cassettes now ask you twice to confirm
  code/modules/antagonists/_common/antag_datum.dm
  monkestation/code/modules/cassettes/machines/postbox.dm
Labels: Feature: Feature

#7555 Blood makes great Lubricant: Adds running people over to some of the vehicles
  code/modules/vehicles/kingschariot.dm
  code/modules/vehicles/mecha/combat/devitt.dm
  monkestation/code/game/mecha/makeshift/trash_tank.dm
Labels: Feature: Feature, Funny

#7626 Automated CC Firing range cleanup + Bullet drive bugfix
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/dish_drive.dm
  code/modules/mob/living/basic/bots/cleanbot/cleanbot.dm
  monkestation/code/modules/blueshift/machines/bullet_drive.dm
  monkestation/code/modules/ghost_players/job_helpers/firing_range_helper.dm
Labels: Feature: enhancement, Change: Mapping

#7637 TRAIT_SNOWSTORM_IMMUNE no longer makes you plasma proof
  code/game/turfs/open/lava.dm
Labels: Code: Fix

#7658 I forgor a single tile....
  _maps/RandomRuins/IceRuins/icemoon_surface_asteroid.dmm
Labels: Change: Mapping

#7640 Uncloneable Neurons quirk
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/quirks/neutral_quirks/unclonable_neurons.dm
  monkestation/code/game/machinery/computer/cloning.dm
  tgstation.dme
Labels: Feature: Feature, QoL, Approval: admin approved

#7661 Regeneration Coma and No healing
  monkestation/code/modules/virology/disease/symtoms/helpful/coma.dm
Labels: Code: Fix

#7650 Oozelings can now extinguish people on fire by hugging them!
  code/__DEFINES/do_afters.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Feature: Feature

#7648 [HELIOS] Disposal fixes and cleanup
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Change: Mapping

#7638 make bingle healing not lag the shit out of the server
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  monkestation/code/modules/veth_misc_items/bingle/bingle_datum.dm
  monkestation/code/modules/veth_misc_items/bingle/bingle_pit.dm
  monkestation/code/modules/veth_misc_items/bingle/mob.dm
Labels: Code: Fix, Code: Performance / Optimization

#7675 Rapid PK Pistol Fix
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Code: Fix, Balance

#7590 My highly explosive chariot
  code/modules/reagents/reagent_dispenser.dm
Labels: Balance

#7625 Battlecruiser adjustment.
  _maps/templates/battlecruiser_starfury.dmm
Labels: Change: Mapping, Balance

#7720 Antag stingers are now defined on the datum
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/battlecruiser/battlecruiser.dm
  code/modules/antagonists/blob/blob_antag.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/heretic/heretic_antag.dm
  code/modules/antagonists/heretic/heretic_monsters.dm
  code/modules/antagonists/malf_ai/malf_ai.dm
  code/modules/antagonists/monster_hunters/hunter_datum.dm
  code/modules/antagonists/nukeop/commando_nukeop/commando_nukeop.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/obsessed/obsessed.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  monkestation/code/modules/antagonists/clock_cult/antag_datums/clock_cultist.dm
  monkestation/code/modules/antagonists/evil_clone/evil_clone.dm
  monkestation/code/modules/antagonists/obsessed/obsessed.dm
Labels: Code: Improvement

#7731 Purification in Progress
  attributions.txt.txt
  code/modules/vending/autodrobe.dm
  monkestation/code/modules/clothing/head/costume.dm
  monkestation/code/modules/clothing/under/costume.dm
  monkestation/icons/mob/clothing/head.dmi
  monkestation/icons/mob/clothing/uniform.dmi
  monkestation/icons/obj/clothing/hats.dmi
  monkestation/icons/obj/clothing/uniforms.dmi
Labels: Change: spriting, Feature: Feature

#7748 Makes Hiero staff use Magic channel for its dash instead of Bluespace
  code/datums/dash_weapon.dm
  code/modules/mining/lavaland/megafauna_loot.dm
Labels: Balance, Approval: admin approved

#6736 Removes Bloom (additive lighting)
  code/__DEFINES/layers.dm
  code/_onclick/hud/rendering/plane_masters/plane_master_subtypes.dm
  code/modules/lighting/lighting_object.dm
  code/modules/mob/mob.dm
  monkestation/code/modules/client/preferences/bloom.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/bloom.tsx
Labels: Removal

#7767 Heads of staff PDAs start with twice as much disk space (#84874)
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
Labels: QoL

#7552 Makes tremere good again
  code/__DEFINES/bloodsuckers.dm
  code/__DEFINES/span.dm
  code/__DEFINES/traits/monkestation/sources.dm
  code/modules/buildmode/buttons.dm
  monkestation/code/datums/_onclick/hud/screen_objects/hud_timer.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_objectives.dm
  monkestation/code/modules/bloodsuckers/clans/_clan_base.dm
  monkestation/code/modules/bloodsuckers/clans/tremere.dm
  monkestation/code/modules/bloodsuckers/powers/_base_power.dm
  monkestation/code/modules/bloodsuckers/powers/targeted/_base_targeted.dm
  monkestation/code/modules/bloodsuckers/powers/targeted/mesmerize.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/_base_tremere.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/auspex.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/dominate.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/obfuscation.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/thaumaturgey.dm
  monkestation/code/modules/bloodsuckers/powers/tremere/thaumaturgy.dm
  monkestation/code/modules/bloodsuckers/powers/veil.dm
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_objects.dm
  monkestation/icons/bloodsuckers/actions_tremere_bloodsucker.dmi
  monkestation/icons/bloodsuckers/bloodsucker_lefthand.dmi
  monkestation/icons/bloodsuckers/bloodsucker_righthand.dmi
  monkestation/icons/bloodsuckers/bs_leftinhand.dmi
  monkestation/icons/bloodsuckers/bs_rightinhand.dmi
  tgstation.dme
Labels: peak, Feature: Expansion, Approval: admin approved, Process: should testmerge

#7709 Slime washing now eats grime off the floor when moving
  monkestation/code/modules/smithing/oozelings/actions.dm
Labels: QoL, Approval: admin approved, Code: Improvement

#4191 Bloodlings!
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/say.dm
  code/__DEFINES/~monkestation/antagonists.dm
  code/_onclick/hud/hud.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/client/preferences/middleware/antags.dm
  code/modules/unit_tests/screenshots/screenshot_antag_icons_bloodling.png
  icons/mob/huds/antag_hud.dmi
  monkestation/code/__DEFINES/mobfactions.dm
  monkestation/code/modules/antagonists/bloodling/abilities/absorb_biomass.dm
  monkestation/code/modules/antagonists/bloodling/abilities/ascension.dm
  monkestation/code/modules/antagonists/bloodling/abilities/bloodling_abilities.dm
  monkestation/code/modules/antagonists/bloodling/abilities/bloodling_hivespeak.dm
  monkestation/code/modules/antagonists/bloodling/abilities/build.dm
  monkestation/code/modules/antagonists/bloodling/abilities/devour.dm
  monkestation/code/modules/antagonists/bloodling/abilities/dissonant_shriek.dm
  monkestation/code/modules/antagonists/bloodling/abilities/give_life.dm
  monkestation/code/modules/antagonists/bloodling/abilities/heal.dm
  monkestation/code/modules/antagonists/bloodling/abilities/hide.dm
  monkestation/code/modules/antagonists/bloodling/abilities/infect.dm
  monkestation/code/modules/antagonists/bloodling/abilities/infest.dm
  monkestation/code/modules/antagonists/bloodling/abilities/transfer_biomass.dm
  monkestation/code/modules/antagonists/bloodling/abilities/whiplash.dm
  monkestation/code/modules/antagonists/bloodling/bloodling.dm
  monkestation/code/modules/antagonists/bloodling/bloodling_hud.dm
  monkestation/code/modules/antagonists/bloodling/bloodling_ruleset.dm
  monkestation/code/modules/antagonists/bloodling/bloodling_structures.dm
  monkestation/code/modules/antagonists/bloodling/bloodling_team.dm
  monkestation/code/modules/antagonists/bloodling/infested_thrall.dm
  monkestation/code/modules/antagonists/bloodling/mobs/bloodling_mob.dm
  monkestation/code/modules/antagonists/bloodling/mobs/minions.dm
  monkestation/code/modules/antagonists/bloodling/objectives.dm
  monkestation/code/modules/antagonists/bloodling/sprites/bloodling_abilities.dmi
  monkestation/code/modules/antagonists/bloodling/sprites/bloodling_sprites.dmi
  monkestation/code/modules/antagonists/bloodling/sprites/flesh_tile.dmi
  monkestation/code/modules/blueshift/optin/mind.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodling.dm
  monkestation/icons/mob/actions/backgrounds.dmi
  monkestation/sound/effects/fleshyheal.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/AntagInfoBloodling.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/bloodling.ts
Labels: Feature: Expansion, Feature: Feature, RED LABEL

#7812 A
  _maps/map_files/tramstation/tramstation.dmm
Labels: Change: Mapping

#7669 Added Slasher Variants
  code/datums/components/squeak.dm
  code/modules/clothing/shoes/clown.dm
  goon/icons/obj/items/attribution.txt
  goon/icons/obj/items/weapons.dmi
  icons/mob/clothing/attribution.txt
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/inhands/clothing/attribution.txt
  icons/mob/inhands/clothing/shoes_lefthand.dmi
  icons/mob/inhands/clothing/shoes_righthand.dmi
  icons/mob/inhands/equipment/attribution.txt
  icons/mob/inhands/equipment/belt_lefthand.dmi
  icons/mob/inhands/equipment/belt_righthand.dmi
  icons/mob/inhands/weapons/attribution.txt
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/clothing/attribution.txt
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/shoes.dmi
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/recall_machette.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/abilities/terror_screech.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_outfit/slasher_clothing.dm
  monkestation/icons/mob/slasher/attribution.txt
  monkestation/icons/mob/slasher/slasher_items.dmi
  monkestation/icons/mob/slasher/slasher_wornstates.dmi
  monkestation/sound/voice/attribution.txt
  monkestation/sound/voice/brute-terror.ogg
  monkestation/sound/voice/cluwne-terror.ogg
Labels: Change: spriting, Code: Fix, Feature: Feature, Change: Sound

#7130 there be cluwnes
  code/__DEFINES/cluwne.dm
  code/__DEFINES/lighting.dm
  code/__DEFINES/traits/declarations.dm
  code/__HELPERS/honkerblast.dm
  code/_globalvars/traits/_traits.dm
  code/game/atoms/atoms_movable.dm
  code/game/objects/effects/effect_system/fluid_spread/effects_smoke.dm
  code/modules/admin/smites/cluwne_smite.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/shoes/clown.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/cluwne/cluwne_brain.dm
  code/modules/cluwne/cluwne_clothing.dm
  code/modules/cluwne/cluwne_component.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/emote.dm
  icons/mob/clothing/attribution.txt
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/under/civilian.dmi
  icons/obj/clothing/attribution.txt
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/under/civilian.dmi
  icons/obj/medical/organs/organs.dmi
  monkestation/code/modules/mob/living/carbon/human/human_defines.dm
  sound/voice/cluwne/chuckle/cluwne_chuckle1.ogg
  sound/voice/cluwne/chuckle/cluwne_chuckle2.ogg
  sound/voice/cluwne/chuckle/cluwne_chuckle3.ogg
  sound/voice/cluwne/chuckle/cluwne_chuckle4.ogg
  sound/voice/cluwne/cluwne_conversion.ogg
  sound/voice/cluwne/cluwne_deathgasp1.ogg
  sound/voice/cluwne/cluwne_deathgasp2.ogg
  sound/voice/cluwne/cluwne_deconversion.ogg
  sound/voice/cluwne/laugh/cluwne_laugh1.ogg
  sound/voice/cluwne/laugh/cluwne_laugh2.ogg
  sound/voice/cluwne/laugh/cluwne_laugh3.ogg
  sound/voice/cluwne/laugh/cluwne_laugh4.ogg
  sound/voice/cluwne/laugh/cluwne_laugh5.ogg
  sound/voice/cluwne/laugh/cluwne_laugh6.ogg
  sound/voice/cluwne/scream/cluwne_scream1.ogg
  sound/voice/cluwne/scream/cluwne_scream2.ogg
  sound/voice/cluwne/scream/cluwne_scream3.ogg
  sound/voice/cluwne/scream/cluwne_scream4.ogg
  sound/voice/cluwne/scream/cluwne_scream5.ogg
  sound/voice/cluwne/scream/cluwne_scream6.ogg
  tgstation.dme
Labels: Code: Fix, Stale, fuck it we ball, Code: Improvement

#7541 [BOUNTY] Ports Yogstation's Combat Mech restrictions
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/shuttles/ruin_freeminer.dmm
  code/__DEFINES/machines.dm
  code/modules/research/designs.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  tgui/packages/tgui/interfaces/ExosuitFabricator.tsx
Labels: Balance, Approval: admin approved

#7831 Fix dna vault
  code/game/objects/items/dna_probe.dm
  code/modules/station_goals/dna_vault.dm
Labels: Code: Fix

#7839 fix vacpacks not being able to suck up adjacent mobs
  monkestation/code/modules/slimecore/items/vacuum_pack.dm
Labels: Code: Fix

#7411 [PORT] [BALANCE] Buffs Lasers (READ DESC)
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
  code/modules/antagonists/blob/structures/shield.dm
  code/modules/projectiles/projectile/beams.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/floran.dm
  monkestation/code/modules/surgery/bodyparts/floran_bodyparts.dm
Labels: Process: testmerge only, Balance, Approval: admin approved

#7843 [BALANCE] Auspex/Obfuscation Nerf
  monkestation/code/modules/bloodsuckers/powers/tremere/obfuscation.dm
Labels: Balance, Approval: admin approved

#7818 Making baton drain less insane.
  code/game/objects/items/melee/baton.dm
Labels: Balance, Approval: admin approved

#7462 Patho standardization part 2
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/LeadPoisoningStation/LeadPoisoningStation.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
Labels: Change: Mapping, Balance
