Repository Monkestation/Monkestation2.0, pull requests merged in 2025-01, with the labels that each got.

#4716 [BOUNTY] Adds Straw Hat and Straw Coat to loadout store
  code/modules/clothing/head/hat.dm
  icons/mob/clothing/head/straw.dmi
  icons/obj/clothing/head/costume.dmi
  monkestation/code/modules/clothing/neck/cloaks.dm
  monkestation/code/modules/loadouts/items/heads.dm
  monkestation/code/modules/loadouts/items/neck.dm
  monkestation/code/modules/store/store_items/head.dm
  monkestation/code/modules/store/store_items/neck.dm
  monkestation/icons/mob/clothing/neck.dmi
  monkestation/icons/obj/clothing/necks.dmi
Labels: Minor

#4706 Shock touch respects his grace
  code/datums/mutations/touch.dm
Labels: Fix

#4670 Adds explosive flashes and door charges
  code/modules/antagonists/traitor/objectives/sabotage_machinery.dm
  monkestation/code/game/objects/items/door_charge.dm
  monkestation/code/game/objects/items/explosive_flash.dm
  monkestation/code/modules/uplink/uplink_items/explosive.dm
  tgstation.dme
Labels: Minor, Feature

#4502 Evil Clone event changes, and removes "peaceful" evil clone objective
  monkestation/code/modules/antagonists/evil_clone/evil_clone_objective.dm
  monkestation/code/modules/antagonists/evil_clone/evil_event.dm
Labels: Minor, Tweak

#2464 Spears are pointy, and have better wound bonus.
  code/game/objects/items/spear.dm
Labels: Tweak, Balance

#4661 Ports new body cameras & Jammers
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/traitordevices.dm
  monkestation/code/modules/clothing/suit_accessories/bodycamera.dm
  monkestation/code/modules/clothing/suit_accessories/bodycamera_box.dm
  monkestation/code/modules/clothing/suit_accessories/camera.dm
  monkestation/icons/mob/clothing/bodycamera_overlay.dmi
  monkestation/icons/obj/clothing/bodycamera.dmi
  tgstation.dme
Labels: Refactor/Rework

#4563 [BOUNTY] A.T.P. engineer mask from Madness Combat
  icons/mob/effects/talk.dmi
  monkestation/code/modules/clothing/masks/misc.dm
  monkestation/code/modules/loadouts/items/masks.dm
  monkestation/code/modules/store/store_items/masks.dm
  monkestation/icons/mob/clothing/mask.dmi
  monkestation/icons/obj/clothing/masks.dmi
  monkestation/sound/items/atp_death_sound.ogg
  monkestation/sound/items/atp_speak1.ogg
  monkestation/sound/items/atp_speak2.ogg
  monkestation/sound/items/atp_speak3.ogg
  monkestation/sound/items/atp_speak4.ogg
  monkestation/sound/items/atp_speak5.ogg
Labels: spriting

#4743 Minor fixes for Slime Grinder and Slime Market Pad
  monkestation/code/modules/slimecore/machines/slime_grinder.dm
  monkestation/code/modules/slimecore/machines/slime_market.dm
Labels: Fix, QoL

#4745 Makes slime vacuum not break lights
  code/modules/power/lighting/light.dm
Labels: Fix

#4765 Server and "you are here" buttons now properly setup during init
  code/_onclick/hud/new_player.dm
Labels: Fix

#4757 Ook's antag weight change requests
  monkestation/code/modules/storytellers/converted_events/solo/blob_infection.dm
  monkestation/code/modules/storytellers/converted_events/solo/bloodsuckers.dm
  monkestation/code/modules/storytellers/converted_events/solo/brother.dm
  monkestation/code/modules/storytellers/converted_events/solo/changeling.dm
  monkestation/code/modules/storytellers/converted_events/solo/malf.dm
  monkestation/code/modules/storytellers/converted_events/solo/obsessed.dm
  monkestation/code/modules/storytellers/converted_events/solo/traitor.dm
Labels: Major, Tweak

#4758 Gun case is now a gun case
  monkestation/code/modules/blueshift/items/gunset.dm
Labels: Balance

#4626 Removes TWitch from normal rounds, and blacklists key chems from stra
  monkestation/code/modules/blueshift/armaments/deforest_medical.dm
  monkestation/code/modules/blueshift/opfor/equipment/medical.dm
  monkestation/code/modules/blueshift/reagents/deforest.dm
Labels: Removal, Balance

#4658 Crew hud for ghosts and silicons
  code/__DEFINES/atom_hud.dm
  code/datums/hud.dm
  code/datums/records/manifest.dm
  code/game/data_huds.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/silicon.dm
  icons/mob/huds/hud.dmi
Labels: Feature, Balance, QoL

#4656 Reverts batons to their previous state (somewhat)
  code/game/objects/items/melee/baton.dm
Labels: Balance

#4689 regal rat minions are now immune to viruses
  monkestation/code/modules/mob/living/basic/space_fauna/regal_rat/regal_rat_actions.dm
  tgstation.dme
Labels: do not merge, testmerge only, Fix

#4776 Slipping and Smashing.
  code/controllers/subsystem/movement/movement_types.dm
  code/datums/components/force_move.dm
  code/modules/recycling/disposal/bin.dm
Labels: enhancement, Fix, Feature

#4736 Oozling Gibbing Patch
  monkestation/code/modules/mob/living/carbon/human/species_type/oozeling.dm
  monkestation/code/modules/surgery/organs/internal/brain.dm
Labels: Fix

#4777 Gives the plant growing subsystem a proper name
  monkestation/code/controllers/subsystem/plants.dm
  monkestation/code/modules/botany/components/plant_growing.dm
  tgstation.dme
Labels: Fix

#4753 Cassette Manager Fixes
  code/__HELPERS/~monkestation-helpers/roundend.dm
  monkestation/code/modules/cassettes/cassette_approval.dm
  tgui/packages/tgui/interfaces/CassetteManager.tsx
Labels: Fix

#4746 Goonstation Style Floor Signs (they're turf decals)
  monkestation/code/modules/floorsigns/floorsigns.dm
  monkestation/icons/turf/floorsign.dmi
  tgstation.dme
Labels: Feature

#4748 Ports the improved prompt sound from /tg/
  code/controllers/subsystem/polling.dm
  monkestation/sound/effects/prompt.ogg
  sound/misc/prompt.ogg
Labels: Tweak

#4703 double checks to make sure patreon token data is added before loading
  monkestation/code/datums/meta_tokens.dm
Labels: Fix

#4707 New AI lawset: Jermov
  monkestation/code/datums/ai_laws/laws_monke.dm
  monkestation/code/game/objects/items/AI_modules/full_lawsets.dm
  tgstation.dme
Labels: peak, Balance

#4779 what if fire was deadlier + halves burning damage component
  code/datums/components/burning.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: do not merge, testmerge only, Balance

#4710 try to fix weird runtime causing people to spawn naked
  monkestation/code/modules/loadouts/loadout_outfit_helper.dm
Labels: Fix

#4695 Nukes some of the overpowered imports, rebalances some of the weapons (ESPECIALLY bogseo)
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  monkestation/code/modules/blueshift/armaments/deforest_medical.dm
  monkestation/code/modules/blueshift/armaments/microstar.dm
  monkestation/code/modules/blueshift/armaments/nakamura.dm
  monkestation/code/modules/blueshift/armaments/sol.dm
  monkestation/code/modules/blueshift/clothing/specialist_armor.dm
  monkestation/code/modules/blueshift/items/ammo.dm
  monkestation/code/modules/blueshift/items/company_guns.dm
  monkestation/code/modules/blueshift/projectiles/__projectile_changes.dm
  strings/nova/long_modular_laser.json
  strings/nova/short_modular_laser.json
Labels: Removal, Balance

#4764 Stampderization (Approval and Denied stamps in all head offices.)
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Mapping, QoL

#4754 Adds a comically large spoon
  code/__DEFINES/traits/monkestation/sources.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_onclick/click.dm
  monkestation/code/game/objects/items/comically_large_spoon.dm
  monkestation/code/modules/cargo/markets/market_items/weapons.dm
  monkestation/icons/mob/clothing/back.dmi
  monkestation/icons/mob/inhands/weapons/melee_lefthand.dmi
  monkestation/icons/mob/inhands/weapons/melee_righthand.dmi
  monkestation/icons/obj/items_and_weapons.dmi
  monkestation/sound/weapons/bat_hit.ogg
  tgstation.dme
Labels: Feature

#4760 fixes emitter beams causing the SM to play supermatter.ogg (dust sound)
  code/modules/power/supermatter/supermatter_hit_procs.dm
Labels: Minor, Fix

#4712 Fixes and balances some problems with satyrs
  monkestation/code/modules/ranching/satyr/components/living_drunk.dm
Labels: Fix, Balance

#4794 jackary's admin office
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping

#4802 Adds a .NET 9 SDK setup action to linters
  .github/workflows/ci_suite.yml
Labels: Fix

#4774 Shotgun Ammo Box Nerf
  monkestation/code/modules/blueshift/items/ammo.dm
Labels: Balance

#4806 Better trash piles!
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/~monkestation/do_afters.dm
  code/_globalvars/lists/maintenance_loot.dm
  monkestation/code/game/objects/structures/trash_pile.dm
  monkestation/code/modules/blueshift/structures/trash_pile.dm
  monkestation/icons/obj/trash_piles.dmi
  tgstation.dme
Labels: Feature

#4789 Ore Processing QOLs
  monkestation/code/modules/factory_type_beat/machinery/brine_chamber.dm
  monkestation/code/modules/factory_type_beat/processing/bouldertech.dm
  monkestation/code/modules/factory_type_beat/processing/checmial_washer.dm
  monkestation/code/modules/factory_type_beat/processing/chemical_injector.dm
  monkestation/code/modules/factory_type_beat/processing/crusher.dm
  monkestation/code/modules/factory_type_beat/processing/crystalizer.dm
  monkestation/code/modules/factory_type_beat/processing/dissolution_chamber.dm
  monkestation/code/modules/factory_type_beat/processing/enricher.dm
  monkestation/code/modules/factory_type_beat/processing/holding_types.dm
  monkestation/code/modules/factory_type_beat/processing/purification_chamber.dm
  monkestation/code/modules/factory_type_beat/processing/refinery.dm
Labels: QoL, fuck it we ball

#4823 Adds Administrator, an admin-only lawset.
  code/datums/ai_laws/laws_neutral.dm
  code/game/objects/items/AI_modules/full_lawsets.dm
Labels: Feature

#4831 Lower the volume of the polling sound
  code/controllers/subsystem/polling.dm
Labels: QoL

#4797 [PORT] sorting code improvements+optimizations
  code/__HELPERS/hallucinations.dm
  code/__HELPERS/sorts/InsertSort.dm
  code/__HELPERS/sorts/MergeSort.dm
  code/__HELPERS/sorts/TimSort.dm
  code/__HELPERS/sorts/helpers.dm
  code/__HELPERS/sorts/sort_instance.dm
  code/controllers/subsystem/dcs.dm
  code/datums/datum.dm
  code/modules/admin/verbs/debug.dm
  code/modules/antagonists/malf_ai/malf_ai_module_picker.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/asset_cache/assets/uplink.dm
  code/modules/modular_computers/file_system/programs/emojipedia.dm
  code/modules/research/stock_parts.dm
  code/modules/unit_tests/unit_test.dm
  tgstation.dme
Labels: Performance / Optimization

#4812 Cleans up a lot of PTL-related code
  code/modules/unit_tests/unit_test.dm
  monkestation/code/modules/power/power_transmission_laser/announcement.dm
  monkestation/code/modules/power/power_transmission_laser/beam.dm
  monkestation/code/modules/power/power_transmission_laser/machine.dm
  tgstation.dme
Labels: Fix

#4817 Fixes the shipbreaker conveyors on theseus
  _maps/map_files/Theseus/Theseus.dmm
Labels: Fix

#4617 AWAKEN THE DRAGON!
  code/__DEFINES/melee.dm
  code/__DEFINES/traits/monkestation/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/martial/sleeping_carp.dm
  code/game/objects/items/granters/martial_arts/sleeping_carp.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/projectiles/gun.dm
  code/modules/uplink/uplink_items/stealthy.dm
  monkestation/code/datums/martial_arts/awakened_dragon.dm
  monkestation/code/modules/antagonists/cult/blood_magic.dm
  monkestation/code/modules/uplink/uplink_items/weapons.dm
  tgstation.dme
Labels: enhancement, Balance

#4464 Sabo borg and more medical tools for assault operatives
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/nova/goldeneye_cruiser.dmm
  monkestation/code/modules/assault_ops/code/armaments/utility.dm
  monkestation/code/modules/assault_ops/code/cyborg.dm
  monkestation/code/modules/food_and_drinks/machinery/smartfridge.dm
  monkestation/code/modules/reagents/reagent_containers/cups/_cup.dm
  tgstation.dme
Labels: Minor

#4879 Port two of my smaller upstream fixes
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/shuttle/shuttle.dm
Labels: Fix

#4830 Convert botany + ranching manuals to use DMIcon (+ related code cleanup)
  monkestation/code/modules/asset_cache/assets/botanical_lexicon.dm
  monkestation/code/modules/asset_cache/assets/chicken_book.dm
  monkestation/code/modules/hydroponics/botanical_lexicon.dm
  monkestation/code/modules/ranching/chicken_book.dm
  monkestation/code/modules/ranching/mutations/_mutations.dm
  tgstation.dme
  tgui/packages/tgui/components/DmIcon.tsx
  tgui/packages/tgui/interfaces/BotanicalLexicon.jsx
  tgui/packages/tgui/interfaces/BotanicalLexicon.tsx
  tgui/packages/tgui/interfaces/RanchingEncyclopedia.tsx
Labels: Refactor/Rework, QoL, Performance / Optimization

#4875 Let people under examine text that you can microwave emags
  code/game/objects/items/emags.dm
  monkestation/code/game/objects/items/emags.dm
Labels: Tweak

#4836 Fix junkie/smoker quirks not processing
  code/datums/quirks/negative_quirks/junkie.dm
Labels: Fix

#4888 Reduces the amount of banana peels from trash piles
  code/_globalvars/lists/maintenance_loot.dm
Labels: QoL

#4905 Fix being able to toss out infinite trash from a trash pile
  monkestation/code/game/objects/structures/trash_pile.dm
Labels: Fix

#4880 Wizard mass mind/species/name swap now only affects the station
  code/modules/events/wizard/race.dm
  code/modules/events/wizard/shuffle.dm
Labels: QoL

#4775 Removes northstar from the code
  _maps/_basemap.dm
  _maps/map_files/NorthStar/north_star.dmm
  _maps/northstar.json.unused
  config/maps.txt
Labels: Mapping, Removal

#4898 Ensures the Tenacity trauma now properly negates all pain as intended
  code/datums/brain_damage/special.dm
  monkestation/code/datums/brain_damage/special.dm
  tgstation.dme
Labels: Fix

#4916 [#4901] Prevent drones from interacting with fireaxe cabinets.
  monkestation/code/game/objects/structures/fireaxe.dm
  tgstation.dme
Labels: Fix, Balance

#4771 Replay subsystem fixes + optimizations
  code/__DEFINES/overlays.dm
  code/__HELPERS/announcements.dm
  code/__HELPERS/mobs.dm
  code/modules/admin/verbs/server.dm
  code/modules/client/verbs/ooc.dm
  monkestation/code/modules/replays/hooks/generic_hooks.dm
  monkestation/code/modules/replays/readme.md
  monkestation/code/modules/replays/subsystem/replay.dm
Labels: Fix, Performance / Optimization

#4895 Move fake virus event later into the round
  monkestation/code/modules/events/fake_virus.dm
  tgstation.dme
Labels: Balance

#4920 Fix Gary being able to steal items from borgs and such
  monkestation/code/modules/ranching/chickens/misc/gary.dm
Labels: what, Fix

#4826 nerfs 45 long ammo
  monkestation/code/game/objects/items/guns/long_guns.dm
Labels: Balance

#4837 You know what Fuck you *uncaps your stando limit*
  code/modules/mob/living/basic/guardian/guardian_creator.dm
Labels: Tweak, Balance

#4967 Fixes Knock path not getting Relentless Heartbeat
  code/modules/antagonists/heretic/knowledge/knock_lore.dm
Labels: Fix

#4972 All public gardens now have botany vendors and a composter
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/Ouroboros/Ouroboros.dmm
  _maps/map_files/Voidraptor/VoidRaptor.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/modules/vending/plushvendor.dm
  monkestation/code/modules/blueshift/icons/obj/vending.dmi
  monkestation/code/modules/blueshift/icons/vending.dmi
  monkestation/code/modules/blueshift/icons/vendor.dmi
  monkestation/code/modules/blueshift/items/barber.dm
  monkestation/code/modules/blueshift/machines/access_vending.dm
  monkestation/code/modules/blueshift/structures/ash_walker.dm
  monkestation/code/modules/vending/megaseed_wall.dm
  monkestation/code/modules/vending/nutrimax_wall.dm
  monkestation/icons/obj/vending.dmi
  tgstation.dme
Labels: Mapping, Feature

#4979 Improve admin logging for antag/event tokens
  code/modules/admin/topic.dm
Labels: QoL

#4886 Some minor bloodsucker fixes
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_moodlets.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_objectives.dm
  monkestation/code/modules/bloodsuckers/clans/_clan_base.dm
  monkestation/code/modules/bloodsuckers/clans/venture.dm
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_crypt.dm
Labels: Fix

#4992 Fixes some duped code, RDS punishment, northwest blueshift, and BDM pathfinding
  _maps/map_files/Blueshift/Blueshift.dmm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/projectiles/projectile/beams.dm
  monkestation/code/datums/quirks/negative_quirks/insanity.dm
  monkestation/code/game/objects/items/guns/crank_guns.dm
  tgstation.dme
Labels: Fix, Balance

#4962 Prevents recall/security level change on assault operative shuttle
  code/game/machinery/computer/communications.dm
Labels: Fix, Balance

#4914 Readds missing antitox symptom back to the game
  monkestation/code/modules/virology/disease/symtoms/helpful/antitoxin.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/delightful.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/invisible.dm
  tgstation.dme
Labels: Minor, Fix

#4833 Adds a second bartender slot
  code/modules/jobs/job_types/bartender.dm
Labels: Tweak

#4947 Removes foreigner+bilingual quirk conflict
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#4928 Prison loaves no longer decompose
  monkestation/code/modules/loafing/code/loaf.dm
Labels: Balance

#4996 Returns Captains antique to its former glory
  code/game/objects/structures/displaycase.dm
  monkestation/code/modules/guns/laser.dm
  tgstation.dme
Labels: Removal

#4884 Update tramstation robotics
  _maps/map_files/tramstation/tramstation.dmm
Labels: Mapping, QoL

#4887 More Various fixes
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/infested_frigate.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/spacerealhotel.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/~monkestation/jobs.dm
  code/game/area/areas/ruins/space.dm
  code/game/machinery/computer/crew.dm
  code/modules/research/designs/limbgrower_designs.dm
  monkestation/code/modules/antagonists/traitor/objectives/kidnapping.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/_base.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/jobs.dm
  monkestation/code/modules/cybernetics/augments/chest_augments.dm
  monkestation/code/modules/cybernetics/augments/eye_implants.dm
  monkestation/code/modules/jobs/job_types/barber.dm
  monkestation/code/modules/jobs/job_types/yellowclown.dm
  tgui/packages/tgui/interfaces/CrewConsoleNova.tsx
Labels: Fix

#4956 Roundstart equipment adjustments for command
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  monkestation/code/datums/id_trim/jobs.dm
  monkestation/code/game/machinery/suit_storage_unit.dm
  monkestation/code/game/objects/effects/landmark.dm
  monkestation/code/game/objects/items/storage/medkit.dm
  monkestation/code/game/objects/structures/crates_lockers/closets/secure/blueshield.dm
  monkestation/code/game/objects/structures/crates_lockers/closets/secure/nanotrasen_rep.dm
  monkestation/code/modules/NTrep/NTrep_spawn.dm
  monkestation/code/modules/blueshield/closet.dm
  monkestation/code/modules/blueshield/landmarks.dm
  monkestation/code/modules/blueshield/trim.dm
  monkestation/code/modules/jobs/job_types/nanotrasen_representative.dm
  monkestation/code/modules/modular_computers/computers/item/role_tablet_presets.dm
  monkestation/code/modules/photography/photo/album.dm
  tgstation.dme
Labels: QoL

#4957 Fixes laser carbines being able to akimbo and rounds their firing delay to 0.2 seconds
  code/datums/components/fullauto.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Fix, Balance

#4893 You can no longer "cheese" killing bloodsuckers via beheading
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_datum.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_life.dm
Labels: Fix

#4882 Makes reagent explosions obey the max cap.
  code/controllers/subsystem/explosions.dm
  code/game/objects/effects/effect_system/effects_other.dm
Labels: Balance

#4944 Potential fix for give alert getting stuck, maybe?
  code/datums/status_effects/neutral.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Fix

#4908 Fix food buffs potentially resulting in negative stamina
  code/datums/components/food/edible.dm
  monkestation/code/datums/stamina_container.dm
  monkestation/code/datums/status_effects/food_buffs.dm
Labels: Fix

#4989 Fix latejoin cyborgs sometimes ending up in walls and such
  code/modules/jobs/job_types/cyborg.dm
Labels: Fix

#4991 Fix borers sometimes losing Galactic Common
  code/datums/mind/_mind.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/living_say.dm
  monkestation/code/modules/antagonists/borers/code/abilities/enter_host.dm
  monkestation/code/modules/antagonists/borers/code/mobs/cortical_borer.dm
  monkestation/code/modules/language/language_holder.dm
  tgstation.dme
Labels: Fix

#4990 [PORT] Fixes things being statistically weighted to drop in security
  code/__HELPERS/turfs.dm
  code/controllers/subsystem/blackmarket.dm
  code/game/objects/items/crab17.dm
  code/modules/admin/admin_verbs.dm
  code/modules/antagonists/heretic/influences.dm
  code/modules/antagonists/wizard/grand_ritual/grand_rune.dm
  code/modules/events/portal_storm.dm
  code/modules/events/wisdomcow.dm
  code/modules/explorer_drone/exodrone.dm
  code/modules/religion/hunt/hunting_rites.dm
  monkestation/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
  monkestation/code/modules/antagonists/monster_hunters/events/wonderland_apocalypse.dm
  monkestation/code/modules/antagonists/monster_hunters/hunter_datum.dm
  monkestation/code/modules/antagonists/traitor/objectives/kidnapping.dm
  monkestation/code/modules/art_sci_overrides/faults/warps.dm
  monkestation/code/modules/assault_ops/code/interrogator.dm
  monkestation/code/modules/assault_ops/code/sunbeam.dm
Labels: Fix

#4927 Prevent rat kings from shitting out oil/vomit from inside of vents
  code/modules/mob/living/basic/space_fauna/regal_rat/regal_rat_actions.dm
Labels: Fix

#4950 Ghost runechat now shows to anyone who can both see and hear ghosts
  code/modules/mob/mob_say.dm
Labels: QoL

#4970 [PORT] Heretics dream of objects around unused influences
  code/__DEFINES/traits/declarations.dm
  code/__HELPERS/files.dm
  code/__HELPERS/text.dm
  code/_globalvars/traits/_traits.dm
  code/controllers/subsystem/sounds.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  strings/tips.txt
  tgui/packages/tgui/interfaces/AntagInfoHeretic.tsx
Labels: Feature, Refactor/Rework

#4988 Adds *annoyed and *sweatdrop emotes
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
  monkestation/code/modules/mob/living/carbon/emote.dm
  monkestation/icons/mob/species/human/emote_visuals.dmi
  monkestation/sound/effects/annoyed.ogg
  monkestation/sound/effects/sweatdrop.ogg
Labels: Fix, Feature

#4768 [PORT] ports tg's void heretic rework
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/proximity_monitor/fields/void_storm.dm
  code/datums/weather/weather_types/void_storm.dm
  code/game/objects/effects/anomalies/anomalies_bioscrambler.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/modules/antagonists/heretic/knowledge/side_flesh_void.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
  code/modules/antagonists/heretic/magic/void_conduit.dm
  code/modules/antagonists/heretic/magic/void_phase.dm
  code/modules/antagonists/heretic/magic/void_prison.dm
  code/modules/antagonists/heretic/magic/void_pull.dm
  code/modules/antagonists/heretic/status_effects/debuffs.dm
  code/modules/antagonists/heretic/status_effects/mark_effects.dm
  code/modules/antagonists/heretic/status_effects/void_chill.dm
  icons/effects/effects.dmi
  icons/hud/screen_alert.dmi
  icons/mob/actions/actions_ecult.dmi
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
  icons/obj/eldritch.dmi
  icons/turf/overlays.dmi
  monkestation/code/modules/temperature_overhaul/temperature_proc.dm
  sound/magic/voiddeflect01.ogg
  sound/magic/voiddeflect02.ogg
  sound/magic/voiddeflect03.ogg
  tgstation.dme
Labels: Tweak, Balance, Refactor/Rework, awaiting admin review

#4835 Port various UX improvements from tg
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/ai.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/guardian.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/status_effects/debuffs/debuffs.dm
  code/datums/status_effects/debuffs/strandling.dm
  code/datums/status_effects/neutral.dm
  code/game/machinery/buttons.dm
  code/game/machinery/embedded_controller/access_controller.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/lightswitch.dm
  code/modules/bitrunning/alerts.dm
  code/modules/buildmode/buttons.dm
  code/modules/escape_menu/home_page.dm
  code/modules/escape_menu/leave_body.dm
  code/modules/industrial_lift/elevator/elevator_panel.dm
  code/modules/mob/living/living.dm
  code/modules/pai/hud.dm
  code/modules/spells/spell_types/shapeshift/_shape_status.dm
  code/modules/tutorials/_tutorial.dm
  code/modules/tutorials/tutorial_instruction.dm
  code/modules/tutorials/tutorial_skip.dm
  monkestation/code/modules/trading/box_rolling.dm
  tgstation.dme
Labels: Fix, QoL

#5013 Update Yarn (3.3.1 -> 4.5.1) and Node (20.13.0 -> 22.11.0)
  dependencies.sh
  tgui/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  tgui/.yarn/releases/yarn-3.3.1.cjs
  tgui/.yarn/releases/yarn-4.5.1.cjs
  tgui/.yarnrc.yml
  tgui/README.md
  tgui/package.json
  tgui/yarn.lock
  tools/bootstrap/node_.ps1
  tools/ci/install_node.sh
Labels: Tools

#4825 Icon and filter optimization stuff
  code/datums/datum.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
Labels: Performance / Optimization

#4894 Revert "Fixes and balances some problems with satyrs (#4712)"
  monkestation/code/modules/ranching/satyr/components/living_drunk.dm
Labels: Fix

#5009 Phobias should not prevent forced says
  code/datums/brain_damage/phobia.dm
Labels: Fix

#5008 Phobia regex should not be a global expression
  code/_globalvars/phobias.dm
Labels: Fix

#4772 What makes me a good demoman?
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/templates/battlecruiser_starfury.dmm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/projectile/bullets/grenade.dm
  code/modules/uplink/uplink_items/nukeops.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt_mirror.dmi
  monkestation/code/modules/blueshift/items/gunset.dm
  monkestation/code/modules/blueshift/projectiles/__projectile_changes.dm
  monkestation/code/modules/guns/40mm_grenade.dm
  monkestation/code/modules/guns/china_lake.dm
  monkestation/code/modules/uplink/uplink_items/explosive.dm
  monkestation/icons/mob/inhands/china_lake_lefthand.dmi
  monkestation/icons/mob/inhands/china_lake_righthand.dmi
  monkestation/icons/obj/guns/40mm_grenade.dmi
  monkestation/icons/obj/guns/china_lake_obj.dmi
  monkestation/sound/misc/china_lake_sfx/china_lake_drop.ogg
  monkestation/sound/misc/china_lake_sfx/china_lake_fire.ogg
  monkestation/sound/misc/china_lake_sfx/china_lake_pickup.ogg
  monkestation/sound/misc/china_lake_sfx/china_lake_rack.ogg
  monkestation/sound/misc/china_lake_sfx/china_lake_rack2.ogg
  tgstation.dme
Labels: enhancement, spriting, Mapping, Feature

#4921 Doubles lionhunter range, Eldritch and Unholy water painkiller
  code/modules/antagonists/heretic/items/hunter_rifle.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Balance

#4976 [Code Bounty] No-swearing quirks
  code/_globalvars/phobias.dm
  code/controllers/subsystem/processing/quirks.dm
  monkestation/code/datums/brain_damage/phobia.dm
  monkestation/code/datums/quirks/negative_quirks/kakologophobia.dm
  strings/phobia.json
  tgstation.dme
Labels: Minor, Feature

#5025 The CMO's Hypospray now pierces
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance

#5000 Adds plague rats to biohazard
  monkestation/code/modules/virology/disease/plague_rat/antagonist.dm
Labels: Minor, QoL

#5014 Various internal mechcomp fixes
  code/modules/tgchat/to_chat.dm
  monkestation/code/modules/mech_comp/objects/_object.dm
  monkestation/code/modules/mech_comp/objects/collector.dm
  monkestation/code/modules/mech_comp/objects/flush.dm
  monkestation/code/modules/mech_comp/objects/interactor.dm
  monkestation/code/modules/mech_comp/objects/messages/button.dm
  monkestation/code/modules/mech_comp/objects/messages/money.dm
  monkestation/code/modules/mech_comp/objects/messages/radioscanner.dm
  monkestation/code/modules/mech_comp/objects/screen.dm
  monkestation/code/modules/mech_comp/objects/signal_output.dm
  monkestation/code/modules/mech_comp/objects/teleporter.dm
  monkestation/code/modules/mech_comp/objects/thermal_printer.dm
Labels: Minor, Fix, Performance / Optimization

#5055 Painter Law 4
  code/datums/ai_laws/laws_neutral.dm
Labels: Feature

#5037 Can no longer pee into containers forever
  monkestation/code/modules/pissing/bladder.dm
Labels: Fix

#5088 Asset cleanup
  monkestation/code/game/objects/items/plushies.dm
  monkestation/code/modules/loadouts/items/plushies.dm
  monkestation/code/modules/store/store_items/plushies.dm
  monkestation/icons/obj/plushes.dmi
Labels: Removal, Performance / Optimization, admin approved

#5075 Lowers Atlatls damage
  code/modules/religion/hunt/atlatl.dm
Labels: Balance

#5082 [PORT] Changes mob height from getter -> updater
  code/modules/clothing/head/_head.dm
  code/modules/mob/living/carbon/carbon_update_icons.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/init_signals.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/surgery/organs/lungs.dm
Labels: Performance / Optimization

#4783 [BOUNTY] Port Skyrat's feature to be able to play the character we want in a ghost role (using character loadouts
  code/controllers/subsystem/processing/quirks.dm
  code/datums/quirks/_quirk.dm
  code/modules/antagonists/pirate/pirate_roles.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/mob.dm
  code/modules/mob_spawn/ghost_roles/away_roles.dm
  code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm
  code/modules/mob_spawn/ghost_roles/golem_roles.dm
  code/modules/mob_spawn/ghost_roles/mining_roles.dm
  code/modules/mob_spawn/mob_spawn.dm
  monkestation/code/modules/loadouts/items/_loadout_datum.dm
  monkestation/code/modules/loadouts/items/accessories.dm
  monkestation/code/modules/loadouts/items/belts.dm
  monkestation/code/modules/loadouts/items/ears.dm
  monkestation/code/modules/loadouts/items/glasses.dm
  monkestation/code/modules/loadouts/items/gloves.dm
  monkestation/code/modules/loadouts/items/heads.dm
  monkestation/code/modules/loadouts/items/inhand.dm
  monkestation/code/modules/loadouts/items/masks.dm
  monkestation/code/modules/loadouts/items/neck.dm
  monkestation/code/modules/loadouts/items/shoes.dm
  monkestation/code/modules/loadouts/items/suits.dm
  monkestation/code/modules/loadouts/items/under/under.dm
  monkestation/code/modules/syndicate_ghostroles/depot.dm
Labels: Major, QoL

#5089 Hopefully fix antag tokens, unusuals, and keybindings being wiped
  code/modules/client/preferences.dm
  code/modules/client/preferences/migrations/convert_to_json_savefile.dm
  code/modules/client/preferences_savefile.dm
  monkestation/code/modules/job_xp/preferences/base_preferences.dm
  monkestation/code/modules/loadouts/loadout_middleware.dm
  monkestation/code/modules/storytellers/antag_rep/helper_procs.dm
Labels: Major, Fix

#5085 Prevent keycard auth from lowering alert to red during delta alert and such
  code/modules/security_levels/keycard_authentication.dm
  tgui/packages/tgui/interfaces/KeycardAuth.jsx
Labels: Fix

#5063 Fix some stuff related to antag token config loading
  monkestation/code/modules/client/verbs.dm
Labels: Fix

#5059 Hypospray buff and MOD injector bug fix
  code/modules/mod/modules/modules_medical.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/medical/reagent_fillings.dmi
Labels: spriting, Balance

#5058 inline some replay marking procs
  code/__DEFINES/overlays.dm
  code/_onclick/item_attack.dm
  code/datums/components/overlay_lighting.dm
  code/game/turfs/change_turf.dm
  code/modules/lighting/lighting_source.dm
  code/modules/shuttle/docking.dm
  monkestation/code/modules/replays/hooks/generic_hooks.dm
  monkestation/code/modules/replays/subsystem/replay.dm
Labels: Performance / Optimization

#5083 [PORT] Navigate verb now indicates areas above or below you
  code/modules/mob/living/navigation.dm
Labels: QoL

#5039 Runtime station QOL and nukie base space
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping, QoL

#5061 Tells you the amount of donator tokens
  monkestation/code/modules/client/verbs.dm
Labels: QoL

#5046 Moves boxstation's engineering mail destination to the foyer
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Mapping

#4815 The shot gun
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/special/syringe_gun.dm
  code/modules/reagents/reagent_containers/cups/drinkingglass.dm
Labels: Minor, Feature

#4997 Update Medical cyborgs.
  code/modules/mob/living/silicon/robot/robot_model.dm
Labels: Balance, awaiting admin review

#5016 Paramedic Gps
  code/modules/jobs/job_types/paramedic.dm
  monkestation/code/game/objects/items/devices/gps.dm
  monkestation/icons/obj/devices/tracker.dmi
Labels: Minor, Feature

#5019 Even more various fixes
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  monkestation/code/modules/blueshift/items/deforest.dm
Labels: Fix, Balance, awaiting admin review

#5050 Adding more tramstation areas/bar touchups
  _maps/map_files/tramstation/tramstation.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_base.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_biodome.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_cult.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_maints_grape.dmm
  _maps/~monkestation/RandomBars/Tram/tram_bar_ocean.dmm
  _maps/~monkestation/RandomBars/Tram/tram_rvb_bar.dmm
  _maps/~monkestation/RandomBars/Tram/tram_slum_bar.dmm
  monkestation/code/game/area/areas/station.dm
Labels: Mapping, QoL

#5111 Fixes typo, cleans up sabre code, lowers cargo sabres stats, higher sledge demo
  code/game/objects/items/melee/misc.dm
  code/modules/cargo/packs/service.dm
  monkestation/code/game/machinery/bomb_actualizer.dm
  monkestation/code/modules/a_ship_in_need_of_breaking/tool/sledgehammer.dm
  monkestation/code/modules/blueshift/items/melee.dm
Labels: Fix, Balance

#5099 Gives voting a custom action icon
  monkestation/code/controllers/subsystem/vote.dm
  monkestation/icons/hud/actions.dmi
  tgstation.dme
Labels: spriting, QoL

#5116 Gary no longer randomly dies for seemingly no reason
  monkestation/code/modules/ranching/chickens/misc/gary.dm
Labels: Fix

#5084 Makes large parcels gigantic to prevent pickup cheese
  code/modules/recycling/sortingmachinery.dm
Labels: Fix

#5105 [PORT] Small and tiny mobs no longer trigger the squeak component
  code/datums/components/squeak.dm
Labels: QoL

#5104 [PORT] Removes the arbitrary limit of 10 maximum chat highlights
  tgui/packages/tgui-panel/settings/SettingsPanel.jsx
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/reducer.js
Labels: QoL

#5120 [PORT] fix: add support for multibyte chars for `truncate`, `stripped_input`, `tgui_input_text`
  code/__HELPERS/text.dm
  code/modules/tgui_input/text.dm
Labels: Fix

#5167 Fix map issues found in CI
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
Labels: Fix

#4762 [Code Bounty] Makes IPC's spew ion laws for a little while after being emagged
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
Labels: Feature

#5048 Makes some space ruin changes, basic mobs a few simples, ports some upstream space ruins
  _maps/RandomRuins/IceRuins/icemoon_underground_abandoned_plasma_facility.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/anomaly_research.dmm
  _maps/RandomRuins/SpaceRuins/dangerous_research.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/derelict_sulaco.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/RandomRuins/SpaceRuins/infested_frigate.dmm
  _maps/RandomRuins/SpaceRuins/interdyne.dmm
  _maps/RandomRuins/SpaceRuins/meateor.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/RandomRuins/SpaceRuins/the_outlet.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_personalshuttle.dmm
  _maps/virtual_domains/psyker_shuffle.dmm
  _maps/virtual_domains/psyker_zombies.dmm
  code/__DEFINES/ai/monsters.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/phobias.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/modules/admin/verbs/spawnobjasmob.dm
  code/modules/antagonists/malf_ai/malf_ai_modules.dm
  code/modules/mapfluff/ruins/spaceruin_code/meateor.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/basic/ruin_defender/mimic/mimic.dm
  code/modules/mob/living/basic/ruin_defender/mimic/mimic_ai.dm
  code/modules/mob/living/basic/ruin_defender/zombie.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/mob_spawn/corpses/mob_corpses.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/research/anomaly/anomaly_core.dm
  icons/obj/clothing/head/costume.dmi
  monkestation/code/modules/a_ship_in_need_of_breaking/ship_maps/mule.dmm
  monkestation/code/modules/clothing/spacesuits/hardsuits/misc.dm
  monkestation/code/modules/mapfluff/ruins/spaceruin_code/mrow_thats_right.dm
  sound/items/weapons/punch1.ogg
  tgstation.dme
Labels: Mapping, Feature, Balance

#5137 Syndicate depot update
  monkestation/code/modules/syndicate_ghostroles/depot.dm
Labels: Minor, Tweak

#5147 Adds a cooldown to the corrupted lungs and appendix
  code/modules/antagonists/heretic/items/corrupted_organs.dm
Labels: QoL

#5129 A little disease, as a treat
  code/modules/events/disease_outbreak.dm
  monkestation/code/modules/events/fake_virus.dm
  monkestation/code/modules/virology/disease/plague_rat/event.dm
Labels: Balance

#5017 The Derelict / KS13 Engineering Update
  _maps/RandomRuins/SpaceRuins/russian_derelict.dmm
  code/game/area/areas/ruins/space.dm
  monkestation/icons/area/areas_derelict.dmi
Labels: Mapping, Fix, QoL, awaiting admin review

#5098 Implements a fix for donator tokens being unlimited
  monkestation/code/datums/meta_tokens.dm
Labels: Fix

#5134 Various minor runtime fixes
  code/datums/components/armor_plate.dm
  code/datums/components/fov_handler.dm
  code/datums/datum.dm
  code/datums/progressbar.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/effects/misc.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/spells/spell_types/jaunt/shadow_walk.dm
  monkestation/code/modules/blueshift/items/armor/ash_walker.dm
  monkestation/code/modules/blueshift/wounds/muscle_wounds.dm
  monkestation/code/modules/research/nanites/nanite_programs/buffing.dm
Labels: Fix, Performance / Optimization

#5142 Fix scrollbars on BYOND 516
  tgui/packages/tgui/interfaces/Fabrication/DesignBrowser.tsx
  tgui/packages/tgui/styles/layouts/Layout.scss
  tgui/packages/tgui/styles/main.scss
Labels: Fix

#5187 fixes null plane debuggers for admins
  code/modules/admin/holder2.dm
Labels: Fix

#5173 [PORT] Group Integration Tests together on the left side of each CI Suite run
  .github/workflows/ci_suite.yml
  .github/workflows/perform_alternate_version_tests.yml
  .github/workflows/perform_regular_version_tests.yml
  .github/workflows/run_integration_tests.yml
Labels: Tools

#5195 Fix crew transfer votes being spammed if nobody votes on them
  monkestation/code/controllers/subsystem/autotransfer.dm
Labels: Fix

#5193 Fixing engineering access on blueshift
  _maps/map_files/Blueshift/Blueshift.dmm
Labels: Fix

#5158 Add a new unit test to ensure floor lights aren't obscured by dense objects
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/floor_lights.dm
Labels: Tools, Fix

#5171 Some additional even more various fixes
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/Blueshift/Blueshift.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/~monkestation/RandomEngines/TramStation/supermatter.dmm
  code/modules/food_and_drinks/machinery/smartfridge.dm
  monkestation/code/modules/slimecore/machines/biomass_recycler.dm
  monkestation/code/modules/slimecore/machines/slime_store/mutators.dm
  monkestation/code/modules/slimecore/slime_color_mutations/colors.dm
Labels: Mapping, Fix

#5196 Lower the CHIMPCON level (fix random CI failures related to exploding monkeys)
  code/modules/mob/living/carbon/death.dm
Labels: Fix
