Repository Monkestation/Monkestation2.0, pull requests merged in 2025-03, with the labels that each got.

#5675 Ghost and LOOC Typing Bubbles
  code/datums/brain_damage/imaginary_friend.dm
  code/modules/mob/living/living_defines.dm
  code/modules/tgui_input/say_modal/modal.dm
  code/modules/tgui_input/say_modal/typing.dm
  icons/mob/effects/talk.dmi
  monkestation/code/modules/mob/mob_defines.dm
  monkestation/code/modules/tgui_input/say_modal/typing.dm
  tgstation.dme
Labels: QoL, admin approved

#5693 Allow bloodsuckers to vassalize xenos
  monkestation/code/modules/bloodsuckers/powers/fortitude.dm
  monkestation/code/modules/bloodsuckers/structures/bloodsucker_crypt.dm
Labels: what, Balance, admin approved, Funny

#4364 Abandoned Containment Site Space ruins
  _maps/RandomRuins/SpaceRuins/abandonedunknownsite1.dmm
  code/__DEFINES/mobfactions.dm
  code/datums/id_trim/ruins.dm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/space.dm
  code/game/objects/items/cards_ids.dm
  code/modules/mob/living/basic/space_fauna/plague_doc/minion_zombies.dm
  code/modules/mob/living/basic/space_fauna/plague_doc/plague_ability.dm
  code/modules/mob/living/basic/space_fauna/plague_doc/plague_doc.dm
  code/modules/mob_spawn/corpses/mob_corpses.dm
  icons/mob/actions/actions_minor_antag.dmi
  tgstation.dme
Labels: Mapping, admin approved

#5724 Fixes ghost critter cooldowns not working (plus, refactors them to use the cooldown macros)
  monkestation/code/modules/ghost_critters/client_addons.dm
  monkestation/code/modules/ghost_critters/ghost_critter_spawnpoint.dm
Labels: Fix

#5715 Fix chem smoke runtiming when it tries to cancel its spread
  code/game/objects/effects/effect_system/fluid_spread/effects_smoke.dm
Labels: Fix

#5713 Charlie Station's equipment access ID can now open the on-station secure engineering crate
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/datums/id_trim/ruins.dm
  code/game/objects/items/cards_ids.dm
  monkestation/code/datums/id_trim/ruins.dm
Labels: Fix, QoL

#5696 [Port] Several atom renaming improvements
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/datums/components/food/ice_cream_holder.dm
  code/datums/components/label.dm
  code/datums/components/rename.dm
  code/datums/components/takes_reagent_appearance.dm
  code/game/objects/objs.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/binary_devices.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/reagents/reagent_containers/cups/drinkingglass.dm
  code/modules/reagents/reagent_containers/cups/drinks.dm
  icons/obj/objects.dmi
Labels: enhancement, QoL

#5695 [PORT] fixes the audio player in BYOND 516
  code/controllers/subsystem/statpanel.dm
  code/modules/tgui_panel/audio.dm
  tgui/packages/tgui-panel/audio/player.js
  tgui/packages/tgui-panel/audio/player.ts
Labels: Fix

#5716 [PORT] Doafter cleanup, disables stoplag dynamic sleeping in unit tests
  code/__HELPERS/mobs.dm
  code/__HELPERS/stoplag.dm
  code/controllers/subsystem/ticker.dm
  code/modules/antagonists/nukeop/equipment/nuclear_bomb/_nuclear_bomb.dm
  code/modules/mob/mob.dm
Labels: Fix, Feature, Refactor/Rework, Code Improvement

#5443 500th Import Gun Rebalance PR.
  code/modules/projectiles/projectile/bullets/shotgun.dm
  monkestation/code/game/objects/items/guns/long_guns.dm
  monkestation/code/modules/blueshift/items/ammo.dm
  monkestation/code/modules/blueshift/items/company_guns.dm
  monkestation/code/modules/blueshift/projectiles/__projectile_changes.dm
  monkestation/code/modules/security/code/weapons/paco.dm
Labels: Major, Tweak, Balance

#5539 Thematic obsessions
  code/_globalvars/traits/_traits.dm
  code/datums/brain_damage/creepy_trauma.dm
Labels: Expansion, admin approved, should testmerge

#5658 Remove some ai voxlines that I can't see being used in a non-rule-breaking way
  code/modules/mob/living/silicon/ai/vox_sounds.dm
  sound/vox_fem/abortions.ogg
  sound/vox_fem/coomer.ogg
Labels: Minor, Removal, awaiting admin review

#5694 Fungal TB, sensory restoration, and disease balancing.
  code/__DEFINES/~monkestation/virology.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/food_and_drinks/machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/cups/bottle.dm
  monkestation/code/modules/virology/disease/premades/debug_disease.dm
  monkestation/code/modules/virology/disease/premades/fungal_tb.dm
  monkestation/code/modules/virology/disease/symtoms/_symptom.dm
  monkestation/code/modules/virology/disease/symtoms/deadly/rhumba_beat.dm
  monkestation/code/modules/virology/disease/symtoms/flavor/special_adaptation.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/antitoxin.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/delightful.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/invisible.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/mind_restoration.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/self_respiration.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/sensory_restoration.dm
  monkestation/code/modules/virology/disease/symtoms/helpful/space_adapt.dm
  monkestation/code/modules/virology/disease/symtoms/restricted/stage4.dm
  tgstation.dme
Labels: Expansion, Tweak, Balance, should testmerge

#5451 Unholy Select Equipment
  monkestation/code/modules/admin/verbs/selectequipment.dm
  monkestation/code/modules/veth_misc_items/unholy_spawn/adminspawn1.ogg
  monkestation/code/modules/veth_misc_items/unholy_spawn/unholy_spawn.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/SelectEquipment.jsx
Labels: enhancement, do not merge, Funny

#5742 Remove double text from ghost role description
  monkestation/code/modules/syndicate_ghostroles/listeningpost.dm
Labels: Minor, Fix

#5712 Like #5636 but for the slime targeting code (Ports tgstation/tgstation#80602 to the slime targeting code)
  monkestation/code/modules/slimecore/mobs/ai_controller/behaviours/find_target_without_trait.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/behaviours/flee_from_item.dm
Labels: Performance / Optimization

#5665 BoxStation Post-Merge Fixes 4.5
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix

#5730 Fix the component printer not showing item icons in its UI
  code/modules/wiremod/core/component_printer.dm
Labels: Fix

#5756 Prevent stacking ATM interactions
  code/__DEFINES/do_afters.dm
  monkestation/code/modules/store/atm/_atm.dm
Labels: Major, Fix

#5758 monkecoin dupe fix part 2
  monkestation/code/modules/client/preferences/inventory.dm
Labels: Major, Fix

#5760 Fix random TGchat BSOD on 516
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
Labels: Fix

#5690 [BOUNTY] Adds random mutations to DNA disk maints loot
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/computer/dna_console.dm
  code/game/objects/effects/spawners/random/techstorage.dm
  monkestation/code/datums/mutations.dm
  monkestation/code/game/machinery/dna_scanner.dm
  tgstation.dme
Labels: Feature, admin approved

#5743 Fixed accidentally doubling metacoin
  monkestation/code/modules/store/admin/admin_coin_modification.dm
Labels: Fix

#5747 Stamina HUD Threshold Changes
  code/modules/mob/living/carbon/carbon.dm
Labels: QoL

#5750 BugfixesGaloreV2
  code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
Labels: Feature

#5509 Junior Lone Operative + Ablative Coat Fix (third time's the charm)
  code/_globalvars/lists/objects.dm
  code/game/objects/effects/countdown.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminevents.dm
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/clothing/suits/ablativecoat.dm
  monkestation/code/modules/antagonists/nukeop/nukeop.dm
Labels: enhancement, Major, do not merge, testmerge only, Fix, Balance, admin approved

#5678 Satyr balancing and fixing rerevert
  monkestation/code/modules/mob/living/carbon/human/species_type/satyr.dm
  monkestation/code/modules/ranching/satyr/components/living_drunk.dm
Labels: Fix, Balance, admin approved

#5746 Gives back NT rep and Blueshield their CC comms + Blueshield Outfit Changes
  code/_globalvars/lists/objects.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminevents.dm
  code/modules/bitrunning/server/obj_generation.dm
  monkestation/code/game/objects/structures/crates_lockers/closets/secure/blueshield.dm
  monkestation/code/modules/blueshield/clothing.dm
  monkestation/code/modules/jobs/job_types/blueshield.dm
Labels: Balance, admin approved

#5740 Adds stuff to centcoms z level
  _maps/map_files/generic/CentCom.dmm
Labels: enhancement, Mapping, Fix

#5587 IPC and Silicon Brain Type Preference
  code/game/objects/structures/ai_core.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/silicon/ai.dmi
  monkestation/code/modules/client/preferences/silicon_brain.dm
  monkestation/code/modules/client/preferences/species_features/ipc.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/monkestation/ipc.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/monkestation/silicon_brain.tsx
Labels: enhancement, admin approved

#5792 tgchat highlight fixes
  tgui/packages/tgui-panel/chat/renderer.jsx
Labels: Fix

#5797 qol: improve metacoin adjustment logs
  monkestation/code/modules/cassettes/machines/postbox.dm
  monkestation/code/modules/client/preferences/inventory.dm
  monkestation/code/modules/store/admin/admin_coin_modification.dm
  monkestation/code/modules/store/atm/_atm.dm
  monkestation/code/modules/store/pre_round/_pre_round_store.dm
  monkestation/code/modules/store/store_items/_store_items.dm
  monkestation/code/modules/trading/lootbox_buying.dm
Labels: QoL

#5796 [PORT] Fix some runtimes in mutation code
  code/datums/mutations/_mutations.dm
  code/datums/mutations/radioactive.dm
Labels: Fix

#5815 Surgery Fixes
  code/modules/surgery/implant_removal.dm
  monkestation/code/modules/antagonists/abductor/equipment/glands/abduction_surgery.dm
  monkestation/code/modules/surgery/splenorrhaphy.dm
  monkestation/code/modules/surgery/steps.dm
  tgstation.dme
Labels: Fix, Balance

#5787 Several mapping fixes, runtime qol
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Fix, QoL

#5759 Wizard "invincibility" event (+ adminordrazine) no longer spams skillchip messages
  code/modules/library/skill_learning/skillchip.dm
  monkestation/code/modules/mob/living/carbon/human/_species.dm
Labels: Fix

#5739 Give blueshield access to their tac locker
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Balance

#5731 [PORT] Dropdowns v2; plus, dropdowns now highlight their selected element
  tgui/docs/component-reference.md
  tgui/packages/tgui/components/Dropdown.tsx
  tgui/packages/tgui/interfaces/AirlockController.tsx
  tgui/packages/tgui/interfaces/DnaConsole/MutationInfo.jsx
  tgui/packages/tgui/interfaces/IntegratedCircuit/FundamentalTypes.jsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/styles/components/Dropdown.scss
Labels: Fix, Refactor/Rework, QoL

#5729 Port-als from portal-related PRs from tg
  code/datums/brain_damage/special.dm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/anomalies/anomalies_bluespace.dm
  code/game/objects/effects/anomalies/anomalies_flux.dm
  code/game/objects/effects/anomalies/anomalies_gravity.dm
  code/game/objects/effects/anomalies/anomalies_hallucination.dm
  code/game/objects/effects/anomalies/anomalies_pyroclastic.dm
  code/game/objects/effects/portals.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/events/wormholes.dm
  code/modules/hallucination/hazard.dm
  code/modules/mining/equipment/wormhole_jaunter.dm
  code/modules/projectiles/projectile/special/wormhole.dm
  sound/attributions.txt
  sound/effects/portal_close.ogg
  sound/effects/portal_open_1.ogg
  sound/effects/portal_open_2.ogg
  sound/effects/portal_open_3.ogg
  sound/effects/portal_travel.ogg
Labels: Feature, QoL, Sound

#5826 [PORTS] Fixes shadows on 516 (and fixes some weather stuff, too)
  code/__DEFINES/dcs/signals/signals_area.dm
  code/__DEFINES/dcs/signals/signals_hud.dm
  code/__DEFINES/dcs/signals/signals_plane_master_group.dm
  code/__DEFINES/layers.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_group.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/datums/components/hide_weather_planes.dm
  code/datums/components/storm_hating.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/modules/admin/verbs/plane_debugger.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PlaneMasterDebug.tsx
Labels: Fix, should testmerge

#5803 Ports VV improvements from upstream
  .github/guides/VISUALS.md
  code/__DEFINES/_helpers.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/vv.dm
  code/_globalvars/admin.dm
  code/_globalvars/bitfields.dm
  code/controllers/globals.dm
  code/datums/armor/_armor.dm
  code/datums/datumvars.dm
  code/modules/admin/view_variables/debug_variable_appearance.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/unit_tests/unit_test.dm
  monkestation/code/modules/cryopods/persistance/base_persistance.dm
  tgstation.dme
Labels: Tools, Performance / Optimization, Code Improvement

#5770 Document Monkestation-specific changes made in #5750
  code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
Labels: documentation

#5591 Negative Language Quirks
  code/__DEFINES/~monkestation/quirk_costs.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/quirks/neutral_quirks/foreigner.dm
  code/datums/quirks/positive_quirks/bilingual.dm
  code/game/say.dm
  monkestation/code/datums/quirks/negative_quirks/language_quirks.dm
  monkestation/code/game/objects/items/translator.dm
  tgstation.dme
Labels: Minor, Feature, admin approved

#5829 More heliostation fixes
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix

#5778 Doomsday Device no longer affects non-organic life
  code/modules/antagonists/malf_ai/malf_ai_modules.dm
Labels: Balance

#5753 Paco Balancing
  code/modules/research/techweb/all_nodes.dm
  monkestation/code/game/objects/items/guns/wt_ammo.dm
  monkestation/code/modules/cargo/crates/security.dm
  monkestation/code/modules/security/code/weapons/paco.dm
Labels: Balance, admin approved

#5828 Duct-tape some more bloodsucker jank by preventing them from being mindswapped
  code/modules/spells/spell_types/pointed/mind_transfer.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_datum.dm
  monkestation/code/modules/spells/spell_types/aoe_spell/mind_swap.dm
Labels: Fix, admin approved

#5764 Reduce some memory usage
  code/__DEFINES/~monkestation/dcs/signals/signals_atom.dm
  code/datums/wires/_wires.dm
  code/game/machinery/doors/airlock.dm
  code/game/turfs/open/space/space.dm
  code/modules/forensics/forensics_helpers.dm
  monkestation/code/modules/blood_datum/forensics_helpers.dm
  monkestation/code/modules/cybernetics/minigame/airlock_hacking_datum.dm
  monkestation/code/modules/cybernetics/minigame/general_hacking.dm
  monkestation/code/modules/outdoors/code/datum/particle_weathers/weather_types/snow.dm
  monkestation/code/modules/outdoors/code/sunlight/sunlight_object.dm
Labels: Performance / Optimization, should testmerge

#5823 Fix some IPC and loadout prefs
  code/modules/client/preferences/species.dm
  code/modules/mob/living/carbon/human/_species.dm
  monkestation/code/datums/quirks/neutral_quirks/anime.dm
  monkestation/code/modules/client/preferences/body.dm
  monkestation/code/modules/client/preferences/species_features/ipc.dm
  monkestation/code/modules/loadouts/loadout_outfit_helper.dm
  monkestation/code/modules/mob/living/carbon/human/species_type/ipc.dm
Labels: do not merge, Fix, Performance / Optimization, should testmerge

#5834 [PORT] Fixes a bug that made it so radios inside objects would blare out their comms to everyone around them
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#5827 Prevent NPC cats from having kittens with player-controlled cats
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: what, Fix, FUCK

#5800 Some various entertainment channel/monitor QoL
  code/__DEFINES/chat.dm
  code/game/machinery/computer/telescreen.dm
  code/game/objects/items/devices/radio/radio.dm
  tgui/packages/tgui-panel/chat/constants.js
Labels: Fix, QoL, admin approved

#5794 Lowers disabler weak disabler beam debilitated mod
  code/modules/projectiles/projectile/beams.dm
Labels: Balance, admin approved

#5782 Mentor cloak no longer has mechanical effects
  monkestation/code/modules/clothing/neck/cloaks.dm
Labels: what, Removal, admin approved

#5833 Unopened goody cases can no longer be sent back on the cargo shuttle
  code/game/objects/items/storage/lockbox.dm
Labels: QoL, admin approved

#5867 Fix replays bloating init times even when they're disabled
  monkestation/code/modules/replays/subsystem/replay.dm
Labels: Fix, Performance / Optimization

#5861 More 516 fixups
  code/__DEFINES/html_assistant.dm
  code/__HELPERS/stat_tracking.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/objects/items/storage/secure.dm
  code/modules/admin/known_alts.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/getlogs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/client/client_procs.dm
  code/modules/mob/dead/new_player/poll.dm
  monkestation/code/modules/admin/verbs/getlogs.dm
  monkestation/code/modules/antimatter/code/control.dm
  monkestation/code/modules/blueshift/opfor/core/admin.dm
  monkestation/code/modules/virology/machines/curer.dm
  monkestation/code/modules/virology/machines/isolator.dm
  tgstation.dme
Labels: Fix

#5868 Don't initialize the materials box in a horribly slow and inefficient way
  code/game/objects/items/storage/boxes/engineering_boxes.dm
Labels: Performance / Optimization

#5848 [PORT] Taking items from your inventory while flying over lava or a chasm will NOT set them on fire or drop them ANYMORE
  code/game/objects/items.dm
Labels: Fix

#5830 [PORTS] HUD Screen stuff
  code/_onclick/click.dm
  code/_onclick/hud/action_button.dm
  code/_onclick/hud/ai.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/alien.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/blob_overmind.dm
  code/_onclick/hud/blobbernaut.dm
  code/_onclick/hud/drones.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/guardian.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/living.dm
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/ooze.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/picture_in_picture.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/plane_master_group.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/_onclick/hud/revenanthud.dm
  code/_onclick/hud/robot.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screentip.dm
  code/datums/components/admin_popup.dm
  code/datums/components/echolocation.dm
  code/datums/interactions/combat_mode.dm
  code/datums/interactions/cyborg_combat_mode.dm
  code/datums/interactions/intents.dm
  code/datums/storage/storage.dm
  code/game/atoms_movable.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/awaymissions/gateway.dm
  code/modules/escape_menu/details.dm
  code/modules/escape_menu/home_page.dm
  code/modules/escape_menu/leave_body.dm
  code/modules/escape_menu/title.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/pai/hud.dm
  code/modules/tutorials/_tutorial.dm
  code/modules/tutorials/tutorial_instruction.dm
  monkestation/code/_onclick/hud/alert.dm
  monkestation/code/datums/status_effects/changeling.dm
  monkestation/code/modules/and_roll_credits/_credits.dm
  monkestation/code/modules/blood_for_the_blood_gods/slasher/components/team_monitor.dm
  monkestation/code/modules/bloodsuckers/bloodsucker/bloodsucker_datum.dm
  monkestation/code/modules/botany/species/apid/species.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/unsorted.dm
  monkestation/code/modules/outdoors/code/_onclick/hud/fullscreen.dm
  monkestation/code/modules/outdoors/code/_onclick/hud/rendering/plane_master.dm
  monkestation/code/modules/possession/possessed_hud.dm
  monkestation/code/modules/ranching/name_tags/name_tag.dm
Labels: Refactor/Rework

#5733 Makes Syndicate Depot shipbreaking work like normal shipbreaking
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
  monkestation/code/modules/syndicate_ghostroles/depot.dm
Labels: Mapping, Fix

#5870 pAIs now have inherent maintenance access
  code/modules/pai/pai.dm
Labels: QoL, admin approved

#5763 New Security Clothing!
  code/modules/vending/wardrobes.dm
  monkestation/code/game/objects/effects/posters/contraband.dm
  monkestation/code/modules/clothing/head/hat.dm
  monkestation/code/modules/clothing/suits/armor.dm
  monkestation/code/modules/clothing/under/jobs/security.dm
  monkestation/icons/mob/clothing/head.dmi
  monkestation/icons/mob/clothing/security.dmi
  monkestation/icons/mob/clothing/suit.dmi
  monkestation/icons/obj/clothing/hats.dmi
  monkestation/icons/obj/clothing/security.dmi
  monkestation/icons/obj/clothing/suits.dmi
  monkestation/icons/obj/poster.dmi
  tgstation.dme
Labels: Expansion

#5876 Fix the Experimental Destructive Scanner's UI
  tgui/packages/tgui/interfaces/ExperimentConfigure.jsx
Labels: Fix

#5883 Revert "Allows admins to adjust monkecoins to negative"
  monkestation/code/modules/store/admin/admin_coin_modification.dm
Labels: Scope: Fix

#5871 Readds mentor cloak appearance change
  monkestation/code/modules/clothing/neck/cloaks.dm
Labels: Scope: Fix

#5886 Bowie, combat, and sabre damage change
  code/game/objects/items/knives.dm
  monkestation/code/modules/blueshift/items/knives.dm
  monkestation/code/modules/blueshift/items/melee.dm
Labels: Balance

#5885 Fix a hard-del related to `/datum/symptom/bee_vomit`
  monkestation/code/modules/virology/disease/symtoms/annoying/bee_vomit.dm
Labels: Scope: Fix

#5737 god is dead we killed him
  code/datums/components/riding/riding_vehicle.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/events/supermatter_surge.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/vehicles/magicbroom.dm
  icons/mob/inhands/weapons/staves_lefthand.dmi
  icons/mob/inhands/weapons/staves_righthand.dmi
  icons/obj/engine/supermatter.dmi
  icons/obj/vehicles.dmi
  icons/obj/weapons/guns/magic.dmi
  monkestation/code/modules/blood_for_the_blood_gods/slasher/slasher_datum.dm
  monkestation/code/modules/mech_comp/objects/interactor.dm
  monkestation/code/modules/mech_comp/vending_machine.dm
  monkestation/sound/ambience/antag/slasher.ogg
  tgstation.dme
Labels: peak

#5896 Actually give pAIs maints access, for real this time
  code/modules/jobs/access.dm
Labels: Code: Fix, FUCK

#5898 [PORT] *Properly* rebuild plane masters after client login if switching between 515 and 516
  code/_onclick/hud/hud.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
Labels: Code: Fix

#5891 [PORT] TGUI Stack Zebra Mode
  tgui/packages/tgui/components/Stack.tsx
  tgui/packages/tgui/stories/Stack.stories.jsx
  tgui/packages/tgui/styles/components/Stack.scss
Labels: Code: TGUI

#5657 Refactors some cleaning slimes behaviors to be subtypes of cleanbot behaviors
  code/__DEFINES/ai/bot_keys.dm
  code/datums/ai/basic_mobs/basic_ai_behaviors/travel_towards.dm
  code/datums/ai/generic/find_and_set.dm
  code/datums/ai/movement/ai_movement_jps.dm
  code/modules/mob/living/basic/bots/bot_ai.dm
  code/modules/mob/living/basic/bots/cleanbot/cleanbot_ai.dm
  code/modules/mob/living/basic/bots/hygienebot/hygienebot_ai.dm
  code/modules/mob/living/basic/bots/medbot/medbot_ai.dm
  monkestation/code/modules/slimecore/mobs/_base_slime.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/behaviours/clean_target.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/controller.dm
  monkestation/code/modules/slimecore/mobs/ai_controller/subtrees/cleaning_tree.dm
  monkestation/code/modules/slimecore/slime_traits/cleaner.dm
Labels: Code: Fix, Feature: Refactor/Rework

#5869 Stamina container optimizations
  code/modules/mob/living/living.dm
  monkestation/code/controllers/subsystem/stamina.dm
  monkestation/code/datums/stamina_container.dm
  monkestation/code/modules/mob/living/living_defines.dm
Labels: Code: Performance / Optimization

#5900 [PORT] HACK: Fixes 516 small character creator bug by shaking screen_loc
  code/_onclick/hud/map_popups.dm
  code/modules/client/preferences.dm
Labels: what, Code: Fix, Code: TGUI

#5903 Prevents normal players from messing with event controls.
  code/modules/events/_event.dm
Labels: Severity: Minor, Code: Improvement

#5653 Murderbone Cape & Hat
  code/modules/clothing/head/tophat.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/clothing/mask.dmi
  monkestation/code/game/objects/items/plasma_license.dm
  monkestation/code/modules/clothing/costumes/syndicate.dm
  monkestation/code/modules/uplink/uplink_items/misc.dm
  monkestation/icons/mob/clothing/costumes/syndicate/evil_clothing_obj.dmi
  monkestation/icons/mob/clothing/costumes/syndicate/evil_clothing_worn.dmi
  monkestation/sound/voice/robotic/crime.ogg
  monkestation/sound/voice/robotic/for.ogg
  monkestation/sound/voice/robotic/time.ogg
  tgstation.dme
Labels: Balance, Approval: admin approved

#5884 [PORT] Fixes broken drone UI on 516
  code/controllers/subsystem/statpanel.dm
  code/datums/elements/dextrous.dm
Labels: Code: Fix

#5907 [PORT] Fixes a runtime at shutdown caused by incorrect arguments
  code/controllers/subsystem/title.dm
Labels: Code: Fix

#5913 Adds henchmen lawset
  monkestation/code/datums/ai_laws/laws_monke.dm
  monkestation/code/game/objects/items/AI_modules/full_lawsets.dm
Labels: Feature: Expansion, Misc: Funny

#2807 Polyglot Tongue
  code/modules/mapfluff/ruins/lavalandruin_code/syndicate_base.dm
  monkestation/code/modules/surgery/organs/autosurgeon.dm
  monkestation/code/modules/surgery/organs/internal/tongue.dm
  monkestation/code/modules/uplink/uplink_items/device_tools.dm
Labels: Severity: Minor, Feature: Expansion, Balance

#5914 [Port] Several fried food fixes
  code/datums/elements/food/fried_item.dm
  code/game/objects/items/tongs.dm
  code/modules/food_and_drinks/machinery/oven.dm
  code/modules/food_and_drinks/plate.dm
Labels: Code: Fix

#5927 Borgs are no longer crowbar proof, barber vender on heliostation, fixes ion storms
  _maps/map_files/Heliostation/Heliostation.dmm
  code/modules/events/ion_storm.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
Labels: Code: Fix

#5703 Donator Jobs and Holiday checks[DNM]
  code/__DEFINES/jobs.dm
  code/__DEFINES/~monkestation/_patreon.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  monkestation/code/datums/patreon_data.dm
  monkestation/code/modules/jobs/donar-holiday-README.md
  monkestation/code/modules/jobs/job_types/candysalesman.dm
  monkestation/code/modules/jobs/job_types/dietwizard.dm
  monkestation/code/modules/jobs/job_types/ghost.dm
  monkestation/code/modules/jobs/job_types/godzilla.dm
  monkestation/code/modules/jobs/job_types/gorilla.dm
  monkestation/code/modules/jobs/job_types/skeleton.dm
  monkestation/code/modules/jobs/job_types/yellowclown.dm
Labels: Process: do not merge, Code: Improvement

#5862 New uplink UI
  code/__DEFINES/uplink.dm
  code/datums/components/uplink.dm
  code/modules/antagonists/malf_ai/malf_ai.dm
  code/modules/antagonists/traitor/uplink_handler.dm
  code/modules/asset_cache/assets/uplink.dm
  code/modules/uplink/uplink_items/bundle.dm
  code/modules/uplink/uplink_items/device_tools.dm
  code/modules/uplink/uplink_items/stealthy_tools.dm
  monkestation/code/modules/blueshift/opfor/equipment/uplinks.dm
  tgui/packages/tgui/components/Image.tsx
  tgui/packages/tgui/interfaces/AntagInfoAssaultops.tsx
  tgui/packages/tgui/interfaces/AntagInfoBloodsucker.tsx
  tgui/packages/tgui/interfaces/AntagInfoBorer.tsx
  tgui/packages/tgui/interfaces/AntagInfoClock.tsx
  tgui/packages/tgui/interfaces/AntagInfoMalf.tsx
  tgui/packages/tgui/interfaces/AntagInfoRevengeVassal.tsx
  tgui/packages/tgui/interfaces/BlackMarketUplink.jsx
  tgui/packages/tgui/interfaces/MalfunctionModulePicker.jsx
  tgui/packages/tgui/interfaces/MalfunctionModulePicker.tsx
  tgui/packages/tgui/interfaces/Uplink/ContractorMenu.tsx
  tgui/packages/tgui/interfaces/Uplink/GenericUplink.tsx
  tgui/packages/tgui/interfaces/Uplink/ObjectiveMenu.tsx
  tgui/packages/tgui/interfaces/Uplink/PrimaryObjectiveMenu.tsx
  tgui/packages/tgui/interfaces/Uplink/calculateDangerLevel.tsx
  tgui/packages/tgui/interfaces/Uplink/index.tsx
  tgui/packages/tgui/interfaces/common/MalfAiModules.tsx
Labels: Code: Fix, QoL, Code: TGUI

#5919 Moon heretic no longer pacifies forever
  code/modules/antagonists/heretic/status_effects/mark_effects.dm
Labels: Code: Fix

#5878 Fixes Lone Ops Final Chapter Prologue
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
Labels: Code: Fix, Approval: awaiting admin review, FUCK

#5864 [Code Bounty] Polyglot Quirk
  code/controllers/subsystem/processing/quirks.dm
  monkestation/code/datums/quirks/positive_quirks/polyglot.dm
  tgstation.dme
Labels: Feature: Feature, Approval: awaiting admin review

#4816 Cargo budget station objective
  code/modules/station_goals/budget.dm
  tgstation.dme
Labels: Feature: Feature

#5946 Make the Recolorable Turtleneck available to all (though donators still get the item for free)
  code/modules/vending/clothesmate.dm
  monkestation/code/modules/donator/code/datum/loadout.dm
  monkestation/code/modules/donator/code/item/clothing.dm
  monkestation/code/modules/loadouts/items/under/under.dm
  monkestation/code/modules/store/store_items/under.dm
Labels: Feature: enhancement, Approval: admin approved

#4814 3D printed guns.
  code/_globalvars/lists/maintenance_loot.dm
  monkestation/code/modules/antagonists/brother/gear/misc.dm
  monkestation/code/modules/cargo/crates/imports.dm
  monkestation/code/modules/cargo/markets/market_items.dm
  monkestation/code/modules/projectiles/guns/ballistic/fss.dm
  monkestation/code/modules/uplink/uplink_items/weapons.dm
  monkestation/icons/mob/inhands/weapons/guns_lefthand.dmi
  monkestation/icons/mob/inhands/weapons/guns_righthand.dmi
  monkestation/icons/obj/guns/guns.dmi
  tgstation.dme
Labels: Severity: Minor, Feature: Feature, Approval: admin approved, Process: should testmerge

#5866 Me when i fix and the
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Graveyard/Graveyard.dmm
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/virtual_domains/pipedream.dmm
  code/datums/ruins/lavaland.dm
  code/modules/bitrunning/virtual_domain/domains/clown_planet.dm
  monkestation/code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  monkestation/icons/mob/sprite_accessories/hair.dmi
Labels: Change: Mapping, Removal, Code: Fix

#5744 Chatbox Websocket client
  tgui/packages/tgui-panel/index.jsx
  tgui/packages/tgui-panel/settings/SettingsPanel.jsx
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/websocket.ts
Labels: peak, Feature: Feature

#5924 Log BYOND version and build in connection_log table
  SQL/database_changelog.md
  SQL/tgstation_schema.sql
  code/__DEFINES/subsystems.dm
  code/modules/client/client_procs.dm
Labels: Code: Improvement

#5945 Some misc upstream fixes (mostly 516 and movement related)
  code/__DEFINES/text.dm
  code/datums/components/jetpack.dm
  code/datums/components/scope.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/mob_movement.dm
  code/modules/tgui_input/alert.dm
  code/modules/tgui_input/checkboxes.dm
  code/modules/tgui_input/list.dm
  code/modules/tgui_input/number.dm
  code/modules/tgui_input/text.dm
  tgui/packages/tgui/interfaces/TextInputModal.tsx
  tgui/public/tgui.html
Labels: Code: Fix, Code: Improvement, Code: TGUI

#5957 Properly replace all /tg/ hydrotrays/soil with Monke versions; add a lint against them
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/Theseus/Theseus.dmm
  tools/maplint/lints/old_botany.yml
Labels: Change: Mapping, Code: Fix

#5775 [s] removes the stupid progress bar for depositing monkecoins
  code/__DEFINES/do_afters.dm
  monkestation/code/modules/store/atm/_atm.dm
Labels: Severity: Major, Code: Fix, FUCK

#5931 Fixes wings in loadout, Adds walkman to loadout
  monkestation/code/modules/loadouts/items/inhand.dm
  monkestation/code/modules/loadouts/items/toys.dm
  monkestation/code/modules/store/store_items/toys.dm
Labels: Code: Fix, Feature: Feature

#5916 Move Research techweb to serveral files rather than one big one
  code/modules/bitrunning/designs.dm
  code/modules/research/techweb/alien_node.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/atmos_nodes.dm
  code/modules/research/techweb/bepis_nodes.dm
  code/modules/research/techweb/biology_nodes.dm
  code/modules/research/techweb/circuit_nodes.dm
  code/modules/research/techweb/cyborg_nodes.dm
  code/modules/research/techweb/engi_nodes.dm
  code/modules/research/techweb/mech_nodes.dm
  code/modules/research/techweb/medbay_nodes.dm
  code/modules/research/techweb/mining_nodes.dm
  code/modules/research/techweb/modsuit_nodes.dm
  code/modules/research/techweb/research_nodes.dm
  code/modules/research/techweb/robo_nodes.dm
  code/modules/research/techweb/security_nodes.dm
  code/modules/research/techweb/service_nodes.dm
  code/modules/research/techweb/surgery_nodes.dm
  code/modules/research/techweb/syndicate_nodes.dm
  tgstation.dme
Labels: Code: Improvement

#5950 [Bounty] Head of __
  monkestation/code/modules/client/preferences/alt_jobs/titles.dm
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
Labels: Feature: enhancement, Severity: Minor

#5958 Fix the regenerator component (i.e teratomas) sometimes not triggering
  monkestation/code/datums/components/regenerator.dm
  tgstation.dme
Labels: Code: Fix

#5979 [PORT] Bumps the sleep on the map_popup load hack from 0.1 seconds to 0.2 seconds.
  code/_onclick/hud/map_popups.dm
Labels: Code: Fix

#5881 [PORT] Import/export chat settings; fixes resizable textareas; + more
  code/modules/tgui_panel/tgui_panel.dm
  config/admins.txt
  tgui/package.json
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/reducer.js
  tgui/packages/tgui-panel/chat/reducer.ts
  tgui/packages/tgui-panel/chat/types.ts
  tgui/packages/tgui-panel/settings/SettingsPanel.tsx
  tgui/packages/tgui-panel/settings/actions.ts
  tgui/packages/tgui-panel/settings/middleware.ts
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/settings/reducer.ts
  tgui/packages/tgui-panel/settings/settingsImExport.ts
  tgui/packages/tgui-panel/telemetry.js
  tgui/packages/tgui/components/TextArea.jsx
  tgui/packages/tgui/styles/components/TextArea.scss
  tgui/webpack.config.js
  tgui/yarn.lock
Labels: Feature: enhancement, Feature: Feature, Code: TGUI

#5992 Fixes basic mobs not idling due to nearby ghosts
  code/datums/ai/_ai_controller.dm
Labels: Code: Fix

#5993 [PORT] Makes Bioware into Status Effects because they're just Status Effects but their own datum
  code/__DEFINES/mobs.dm
  code/datums/status_effects/buffs/bioware/_bioware.dm
  code/datums/status_effects/buffs/bioware/circulation.dm
  code/datums/status_effects/buffs/bioware/cortex.dm
  code/datums/status_effects/buffs/bioware/ligaments.dm
  code/datums/status_effects/buffs/bioware/nerves.dm
  code/datums/status_effects/buffs/stun_absorption.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/surgery/advanced/bioware/bioware.dm
  code/modules/surgery/advanced/bioware/bioware_surgery.dm
  code/modules/surgery/advanced/bioware/cortex_folding.dm
  code/modules/surgery/advanced/bioware/cortex_imprint.dm
  code/modules/surgery/advanced/bioware/ligament_hook.dm
  code/modules/surgery/advanced/bioware/ligament_reinforcement.dm
  code/modules/surgery/advanced/bioware/muscled_veins.dm
  code/modules/surgery/advanced/bioware/nerve_grounding.dm
  code/modules/surgery/advanced/bioware/nerve_splicing.dm
  code/modules/surgery/advanced/bioware/vein_threading.dm
  tgstation.dme
Labels: Feature: Refactor/Rework

#5990 fixes windows being colored when they shouldnt
  monkestation/code/modules/aesthetics/objects/windows.dm
Labels: Code: Fix

#5986 [PORT] Prevents loot duping via corpse revival
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Code: Fix

#5949 Brig physician voucher
  code/modules/mining/voucher_sets.dm
  code/modules/vending/security.dm
  monkestation/code/modules/jobs/job_types/brig_physician.dm
  monkestation/code/modules/security/code/officermonitor.dm
  monkestation/icons/obj/items/security_voucher.dmi
  tgstation.dme
Labels: Feature: enhancement

#5954 Pirate and bounty hunter balance
  _maps/shuttles/hunter_bounty.dmm
  _maps/shuttles/hunter_psyker.dmm
  _maps/shuttles/hunter_russian.dmm
  _maps/shuttles/hunter_space_cop.dmm
  _maps/shuttles/pirate_default.dmm
  _maps/shuttles/pirate_dutchman.dmm
  _maps/shuttles/pirate_geode.dmm
  _maps/shuttles/pirate_grey.dmm
  _maps/shuttles/pirate_silverscale.dmm
  code/game/machinery/doors/airlock.dm
  code/modules/antagonists/fugitive/hunters/hunter_gear.dm
  code/modules/antagonists/pirate/pirate_shuttle_equipment.dm
  code/modules/events/ghost_role/fugitive_event.dm
  code/modules/wiremod/shell/airlock.dm
  monkestation/code/modules/aesthetics/walls/mineral_walls.dm
  tgstation.dme
Labels: Balance, Approval: admin approved, Code: Improvement

#6003 Remove the wooden boards from chem lab
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Change: Mapping, Removal

#5987 Fixes a proc arg
  code/modules/mob/living/basic/lavaland/legion/legion_tumour.dm
Labels: Code: Fix

#6011 Fix the Theseus gravgen SMES backfeeding
  _maps/map_files/Theseus/Theseus.dmm
Labels: Change: Mapping, Code: Fix

#6002 Elance is no longer always make-able
  monkestation/code/datums/components/crafting.dm
Labels: Code: Fix

#5935 Adds lesser strange seeds
  code/modules/hydroponics/seeds.dm
  monkestation/code/modules/hydroponics/grown/random.dm
  monkestation/code/modules/research/designs/biogenerator_designs.dm
  tgstation.dme
Labels: Balance, Approval: admin approved

#6025 Fix xenobio UI scrolling on BYOND 516
  tgui/packages/tgui/interfaces/SlimePenController.jsx
  tgui/packages/tgui/interfaces/XenobioMarket.jsx
Labels: Code: Fix, Code: TGUI

#6017 [BALANCE] Make the Super syndie kittie not a freedom implant anymore.
  monkestation/code/modules/mapfluff/ruins/spaceruin_code/mrow_thats_right.dm
Labels: Balance, Approval: admin approved

#5745 The 132005th Cybernetics PR
  code/__DEFINES/research/research_categories.dm
  code/datums/station_traits/positive_traits.dm
  code/game/objects/items/storage/medkit.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/cyborg_nodes.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  icons/mob/augmentation/advanced_augments.dmi
  icons/obj/medical/organs/organs.dmi
  monkestation/code/game/objects/items/storage/uplink_kits.dm
  monkestation/code/modules/ERT/ERT_outfits.dm
  monkestation/code/modules/blueshield/gun.dm
  monkestation/code/modules/cybernetics/augments/_base_changes.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/jobs.dm
  monkestation/code/modules/cybernetics/augments/arm_augments/item_sets/weapons.dm
  monkestation/code/modules/cybernetics/augments/eye_implants.dm
  monkestation/code/modules/cybernetics/augments/internal_implants.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/chemplants.dm
  monkestation/code/modules/cybernetics/augments/leg_augments/traits.dm
  monkestation/code/modules/cybernetics/designs/item_sets.dm
  monkestation/code/modules/cybernetics/designs/security.dm
  monkestation/code/modules/cybernetics/implant_items/autosurgeons.dm
  monkestation/code/modules/cybernetics/tech_nodes.dm
  monkestation/code/modules/factory_type_beat/yummy.dm
  monkestation/code/modules/research/designs/medical_designs.dm
  monkestation/code/modules/research/techweb/cyborg_node.dm
  monkestation/code/modules/surgery/organs/augments.dm
  monkestation/code/modules/surgery/organs/internal/appendix/fidgetappendix.dm
  monkestation/code/modules/surgery/organs/internal/eyes.dm
  tgstation.dme
Labels: Feature: Expansion, Balance, Approval: admin approved

#5970 Adding some substance to the detective role + a port from TG
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/detectivework/scanner.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/research/designs/autolathe/security_designs.dm
  monkestation/code/modules/loadouts/items/gloves.dm
  monkestation/code/modules/security/code/undercover_id.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/ForensicScanner.tsx
Labels: Feature: enhancement, Balance, Approval: awaiting admin review

#6048 Fix lights sometimes not properly updating when turned on/off
  code/modules/lighting/lighting_atom.dm
  code/modules/power/lighting/light.dm
Labels: Code: Fix, Process: should testmerge

#6030 Interaction component fixes + improvements
  _maps/map_files/debug/runtimestation.dmm
  code/__DEFINES/traits/monkestation/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/controllers/configuration/entries/monkestation.dm
  code/datums/elements/food/fried_item.dm
  code/modules/unit_tests/mob_faction.dm
  code/modules/unit_tests/unit_test.dm
  config/game_options.txt
  monkestation/code/modules/mech_comp/objects/interactor.dm
  monkestation/code/modules/mech_comp/objects/messages/regex/_regex.dm
  monkestation/code/modules/mech_comp/vending_machine.dm
  tgstation.dme
Labels: Severity: Major, Code: Fix, Code: Improvement

#6050 You thought you could escape huh nice try you glorified water dispenser. you. will. never. escape. me
  icons/obj/watercloset.dmi
Labels: Change: spriting

#5920 quick fix to allow mentors and admins through interview
  code/modules/client/client_procs.dm
Labels: Tools, Code: Fix

#6073 Fix (un)installing git hooks erroring if you have any global merge drivers
  tools/hooks/install.py
Labels: Tools, Code: Fix

#6076 Move `/world/Genesis` to the top of the dme
  code/genesis_call.dme
  tgstation.dme
Labels: Code: Fix

#5353 Custom Command Report Updates!
  code/__DEFINES/~monkestation/admin.dm
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/communications.dm
  code/modules/admin/verbs/commandreport.dm
  monkestation/code/modules/admin/verbs/commandreport.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/CommandReport.tsx
Labels: Severity: Minor, Feature: Feature, QoL

#6023 monsterhunter trick weapon code improvements
  code/__DEFINES/~monkestation/antagonists.dm
  code/__DEFINES/~monkestation/dcs/signals/signals_monster_hunter.dm
  monkestation/code/modules/antagonists/monster_hunters/tools/rabbit_eye.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/_trick_weapon.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/beast_claw.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/darkmoon.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/hunter_axe.dm
  monkestation/code/modules/antagonists/monster_hunters/weapons/threaded_cane.dm
Labels: Code: Improvement

#6082 Plexora: Asay/Msay bridge
  code/modules/admin/verbs/adminsay.dm
  monkestation/code/controllers/subsystem/plexora.dm
  monkestation/code/modules/mentor/mentor_say.dm
Labels: Process: testmerge only, Feature: Feature, QoL

#6072 Gives admins byond member features, except the icon in ooc
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
Labels: Feature: enhancement

#6032 Adds Altjira XC's epic cool office to CC
  _maps/map_files/generic/CentCom.dmm
Labels: Change: Mapping

#6091 Fix more list qdels
  monkestation/code/modules/NTSL/code/machinery/traffic_control.dm
  monkestation/code/modules/cybernetics/minigame/hacking_minigame.dm
Labels: Code: Fix

#6051 Makes it so icemoon openspace turfs can't spawn on top of station turfs, in preparation for CraterStation
  code/game/turfs/open/openspace.dm
  monkestation/code/game/turfs/open/openspace.dm
  tgstation.dme
Labels: Approval: admin approved, Code: Improvement

#6101 Run prettier on tgui.html
  tgui/.prettierignore
  tgui/public/tgui.html
Labels: Code: TGUI

#6056 Lowers depot TC from 25 to 5
  _maps/RandomRuins/SpaceRuins/syndicate_depot.dmm
Labels: Balance, Approval: admin approved

#6080 Fix cleaner slimes not targeting other types of trash
  code/modules/mob/living/basic/bots/cleanbot/cleanbot_ai.dm
  monkestation/code/modules/slimecore/slime_traits/cleaner.dm
Labels: Code: Fix

#6110 Revert "Run prettier on tgui.html" [ci skip]
  tgui/.prettierignore
  tgui/public/tgui.html
Labels: what

#6119 Heretic Summon mob rites now properly take parts
  code/modules/antagonists/heretic/heretic_knowledge.dm
Labels: Severity: Major, Code: Fix

#6036 Makes the heroic laser musket rarer
  monkestation/code/modules/cargo/markets/market_items.dm
Labels: Balance

#5905 [Code Bounty] Lisp Quirk
  code/controllers/subsystem/processing/quirks.dm
  monkestation/code/datums/quirks/negative_quirks/lisp.dm
  tgstation.dme
Labels: Feature: Feature, Approval: admin approved

#6103 Fixes several crusher and pka bugs, makes crushers more modular, crusher mark change
  code/datums/status_effects/debuffs/debuffs.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  monkestation/code/game/objects/items/miningweapons.dm
Labels: Code: Fix, Balance

#6035 Death sandwich requirement changes
  code/game/objects/items/food/sandwichtoast.dm
Labels: peak, Tweak

#6124 Run prettier on tgui.html (515 compatible edition)
  tgui/.prettierignore
  tgui/.prettierrc.yml
  tgui/public/tgui.html
Labels: Code: TGUI

#6128 Fix the shuttle only taking 5 minutes during yellow and amber alert
  code/modules/shuttle/emergency.dm
Labels: Code: Fix

#6112 Fixes some stuff with afterimages
  code/__HELPERS/icons.dm
  monkestation/code/modules/datums/components/glitching_state.dm
  monkestation/code/modules/ranching/components/afterimage.dm
Labels: Code: Fix

#6123 some more bugfixes (as a treat)
  code/_onclick/hud/hud.dm
  code/datums/actions/mobs/projectileattack.dm
  code/game/atom_defense.dm
  code/game/objects/items/cards_ids.dm
  code/modules/antagonists/heretic/status_effects/void_chill.dm
  code/modules/mob/living/basic/bots/_bots.dm
  monkestation/code/modules/loadouts/items/_loadout_datum.dm
  monkestation/code/modules/virology/disease/symptom_cracker/symptom_component.dm
Labels: Code: Fix

#6027 New surgeries for IPCs to resolve damage edgecases
  monkestation/code/modules/research/designs/medical_designs.dm
  monkestation/code/modules/surgery/robot_oxy_clean.dm
  monkestation/code/modules/surgery/robot_tox_clean.dm
  tgstation.dme
Labels: Feature: Feature

#6031 Blocks the clone pod from creating MOB_ROBOTIC mobs
  monkestation/code/game/machinery/cloning.dm
Labels: Balance

#5918 [Mirror/Ports] Research queue
  code/controllers/subsystem/research.dm
  code/modules/modular_computers/file_system/programs/techweb.dm
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/_techweb_node.dm
  tgui/packages/tgui/interfaces/Techweb.jsx
Labels: Feature: Expansion, QoL, Approval: admin approved, Code: TGUI

#6147 You can now attach internals to Vims without any
  code/game/objects/items/tanks/tanks.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/vehicles/cars/vim.dm
  monkestation/code/modules/vehicles/cars/vim.dm
  tgstation.dme
Labels: Feature: Feature, QoL, Approval: admin approved

#6152 Fix freerange radios/intercoms being able to broadcast over the radio frequency
  code/__HELPERS/radio.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Code: Fix

#6141 [s] Revert "Blocks the clone pod from creating MOB_ROBOTIC mobs"
  monkestation/code/game/machinery/cloning.dm
Labels: Severity: Major, Process: do not merge, Code: Fix, Process: should testmerge, FUCK
